### ISSUE TITLE
Commenter

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#100]
Use [guide](https://confluence.jetbrains.com/display/IntelliJIDEA/Commenter) to add commenter to allow bulk commenting of code when debugging or reworking code.  Test using [guide](http://www.jetbrains.org/intellij/sdk/docs/tutorials/writing_tests_for_plugins/commenter_test.html)

**Comment by h4cc** [comment]
This would be a usable feature! :+1:
