### ISSUE TITLE
"Test framework quit unexpectedly" when running a test that has a compile error

### ISSUE THREAD

**Issue by sparta-developers** [KronicDeth/intellij-elixir#1023]
When a test has a compilation error, the left pane of the test runner just shows a "Test framework quit unexpectedly" error, and the right pane of the test runner does not show any output beyond "Suite started with seed nnnnnn". It would be nice to see the compilation error there. 

Compilation errors in non-test files do show up in the right pane of the test runner.

We created a [repo](https://github.com/sparta-science/intellij_elixir_bug) that demonstrates the error when you run `UnsuccessfulTest`.

Here's what it looks like in IntelliJ:

<img width="1247" alt="screen shot 2018-02-06 at 10 23 11 am" src="https://user-images.githubusercontent.com/31809836/35876662-c9204ab4-0b27-11e8-8886-50c78edfba1b.png">

Here's what it looks like on the command line:

```
~/Development/intellij_elixir_bug$ mix test                                                                                                                                                                [10:13:52]
** (CompileError) test/unsuccessful_test.exs:6: undefined function this_function_does_not_exist/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:376: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

**Comment by sparta-developers** [comment]
Also, thanks for creating this plugin! We love it!  ❤️

**Comment by eahanson** [comment]
In case it's helpful for when you redo the build project support, I tried some older versions of the plugin and found that it fails with 6.0.0 and newer, but gives the expected output with version 5.1.0 of the plugin:

<img width="1263" alt="screen shot 2018-02-07 at 1 03 15 pm" src="https://user-images.githubusercontent.com/31809836/35941534-690c8e40-0c07-11e8-8fed-57267d23057b.png">

(This is with IntelliJ IDEA 2017.3.4 (Ultimate Edition))
