### ISSUE TITLE
v0.2.0 does not appear to work with Rubymine 7.0.4

### ISSUE THREAD

**Issue by sinobra** [KronicDeth/intellij-elixir#103]
For example Elixir File is not a selection on the New drop-down list,
Elixir file is not in the list of Recognized File Types,
Elixir is not listed under Editor->Inspections

**Comment by sinobra** [comment]
9:13:39 AM PluginException: class with name "org.elixir_lang.action.CreateElixirFileAction" not found [Plugin: org.elixir_lang]

**Comment by KronicDeth** [comment]
Did you install using the Plugin Browser in Rubymine or the zip here on Github?  I'm unable to reproduce the error with either zip when uninstalling and reinstalling the plugin.

**Comment by sinobra** [comment]
Hi Luke,

Thank you for your response.  I had downloaded the zipfile from Github.
But after your receiving email, I uninstalled the plugin and re-installed
it using the plugin browser.  Everything appears to be fine.  Thanks!!!!!

Best regards,

Fred Obermann
