### ISSUE TITLE
Support using Espec instead of ExUnit for tests 

### ISSUE THREAD

**Issue by drl123** [KronicDeth/intellij-elixir#1035]
Coming from the Ruby/Rspec world, I much prefer Espec syntax over ExUnit as the tests are much more readable.  I was able to get it working in my project, but unable to get a Run Configuration that would run in the Rubymine test runner, even with the `spec` directory marked as `Tests` in the Project Structure.    The command will run, but it runs in a normal Run Window, not a Test Runner Window.

Is there any way to build a Run Configuration that will allow `mix espec` to run the IDE Test Runner Window.  Could this option be added to the plugin?

**Comment by KronicDeth** [comment]
The ExUnit runner is all under [src/org/elixir_lang/mix/runner/exunit](https://github.com/KronicDeth/intellij-elixir/tree/master/src/org/elixir_lang/mix/runner/exunit) you'd have to copy or adapt some of that directories code to work with `mix espec` instead of `mix test`.
