### ISSUE TITLE
syntax Highlight broken by declare Map brace

### ISSUE THREAD

**Issue by RazgrizHsu** [KronicDeth/intellij-elixir#1091]
just put code like this..
```
#this declare will broken
newModel = %Ecto.DataModel
{
    id: 0, name: "test brace"
}

#but this will work
newModel = %Ecto.DataModel{
    id: 0, name: "test brace"
}
```

any options to allow syntax like this?

**Comment by KronicDeth** [comment]
An optional EOL needs to be added after `mapExpression` in `structOperation` in the parser BNF.

https://github.com/KronicDeth/intellij-elixir/blob/9d23bc7c91fa712a61afcd68dba3df11003ebaf0/src/org/elixir_lang/Elixir.bnf#L2131-L2132
