### ISSUE TITLE
Can't rename bracket operation variable

### ISSUE THREAD

**Issue by RazgrizHsu** [KronicDeth/intellij-elixir#1113]
Hi, another issue,

when using Atom Key to get Map inner variable,
trying to rename Map variable, IDE cannot rename it

source..
```
def testRenameMapVariable() do
		
	#trying using shift+F6 to rename this variable
	map = %{}
				
	#will be renamed
	key1 = map.atomkey1
		
	#cannot rename by F6 
	key1 = map[:atomkey1]
end
```
when you using shift + F6 try to rename "map" variable, will be this...
![Example](https://i.imgur.com/jfhOWih.png "Example")

you can see the last map variable cannot be rename

Thank you very much for awesome plugin 👍

**Comment by KronicDeth** [comment]
This is related to #306.
