### ISSUE TITLE
Debug not stopping at breakpoint

### ISSUE THREAD

**Issue by leggebroten** [KronicDeth/intellij-elixir#1140]
(First off, thanks you VERY much for this awesome plugin.  I tried donating but the Paypal landing page would not let me change the amount from $0.00)

Debugger does not stop at break point (Windows 10 issue?)

I have a very simple project.  
One "go.ex" file with a single, one-line function.
I set the break point on that line, invoke the method via a unit test and while the test completes the debugger doesn't stop on the break point

I'm running Windows 10 Pro
![debug not break](https://user-images.githubusercontent.com/5223530/41502735-64b293e4-717e-11e8-8dc3-547d3f8ff951.png)

**Comment by KronicDeth** [comment]
> (First off, thanks you VERY much for this awesome plugin. I tried donating but the Paypal landing page would not let me change the amount from $0.00)

Did you try just typing numbers first after you get the $0.00 prompt?  For me, I can't use the arrow keys until I first type numbers, then I can edit with number keys or arrow keys.  Visually, the initial $0.00 is grey, but once I type numbers, they turn black, so I think the grey is placeholders in Paypal's UI while black is user input, so editable.  I don't really have a lot of control with that UI, so all I can do is explain what works here.

**Comment by leggebroten** [comment]
Yup.

Tried typing, arrow keys, delete, backspace ... noth'n worked


________________________________

**Comment by IljaN** [comment]
Same for me with unit-tests, didn; try normal debuggig yet

**Comment by KronicDeth** [comment]
The debugger has been rewritten in #1175.  Reopen after 7.6.0 is released if the issue persists with the rewrite.
