### ISSUE TITLE
Unable to add Elixir SDK nor gets the installed one detected

### ISSUE THREAD

**Issue by joetjen** [KronicDeth/intellij-elixir#119]
I am running on OSX and have (using brew) Elixir 1.0.2, 1.0.3 and 1.0.4 installed. Nevertheless I am not able to add the SDK to IntelliJ Ultimate as I don't have the option to choose "Elixir SDK" as SDK type and therefore selecting the directory displays an error that no JDK was found in the given path. For testing purposes I disabled almost all other PlugIns, but the problem persists. I also have no PlugIn exception to report. Last but not least I installed the official Ruby PlugIn to check if SDK Detection and Configuration (other that JDKs) works in general and it does, it - as expected - also picks up the rvm installed rubies by default.

**Comment by KronicDeth** [comment]
The Elixir SDK detection and setup is on master, but not in a released version yet.  I'll release a version sometime this week for you.  Just so you're aware, the SDK detection just makes it appear in the External Libraries view of the project.  It's not used for anything else yet.  I haven't written the mix task runner or anything using `iex` or `elixirc`.

**Comment by KronicDeth** [comment]
The latest release is 0.3.0 and here's it's [README](https://github.com/KronicDeth/intellij-elixir/blob/v0.3.0/README.md).

**Comment by KronicDeth** [comment]
[v0.3.1](https://github.com/KronicDeth/intellij-elixir/releases/tag/v0.3.1) has been released.  You can either update it through IntelliJ or get the zip directly from that link if it's not showing up on the Jetbrains Plugin Repository yet.  If you do try to install with the zip you''ll need to uninstall the old version, restart, install the zip, and restart.
