### ISSUE TITLE
Atoms with "@" symbol require quotes for IntelliJ to not complain

### ISSUE THREAD

**Issue by emhagman** [KronicDeth/intellij-elixir#1211]
When using the "@" symbol in atoms, the plugin highlights the file as if there is a syntax error that breaks the module. Since `mix format` removes quotes from atoms that don't need it, any time I format my code, the IntelliJ plugin highlights the file incorrectly.

Example:
```
%{ name@en: "Eric" }
```

That is a valid atom and when it is quoted such as below, the plugin highlights the file properly but when written as above, the plugin turns most of the code to plain white indicating it can't read the file syntax.

```
%{ "name@en": "Eric" }
```

`mix format` removes the quotes around the atom as they are not needed.

**Comment by KronicDeth** [comment]
Weird.  It's in `ATOM_MIDDLE` and should be in `ATOM` therefore:

https://github.com/KronicDeth/intellij-elixir/blob/d20337195b655c690dbc3025d6ec717de8148662/src/org/elixir_lang/Elixir.flex#L341-L344

**Comment by KronicDeth** [comment]
Ah, ok, so `ATOM_START` is only used after `COLON`:

https://github.com/KronicDeth/intellij-elixir/blob/d20337195b655c690dbc3025d6ec717de8148662/src/org/elixir_lang/Elixir.flex#L755-L765

Which, means it is **NOT** used for keywords where the `COLON` trails.

`keywordKey` only contains `IDENTIFIER_TOKEN`, not `ATOM`:

https://github.com/KronicDeth/intellij-elixir/blob/d20337195b655c690dbc3025d6ec717de8148662/src/org/elixir_lang/Elixir.bnf#L3040-L3080

Which means that atoms for wordish things that aren't reserved words is being matched in the lexer by

https://github.com/KronicDeth/intellij-elixir/blob/d20337195b655c690dbc3025d6ec717de8148662/src/org/elixir_lang/Elixir.flex#L827-L828

What needs to happen is that a clause for `{ATOM} / {COLON}` needs to be made before that and `IDENTIFIER` needs to no longer check for a trailing `COLON`.

**Comment by emhagman** [comment]
Glad I'm not crazy :) I'd be happy to try out the fix before merging if somehow can commit one.
