### ISSUE TITLE
Function autocompletion inside module not working when it has inline module

### ISSUE THREAD

**Issue by nulian** [KronicDeth/intellij-elixir#1270]
When you have a module inside a module autocompletion of functions breaks.
Probably because the local method scope switches to the module inside it.

Probably the same issue #1254 as I previously reported but didn't see that it was caused by inline modules.

```
defmodule Autocomplete do

  defmodule State do
    def another_test do
    end
  end

  def test do
    # you will see `test` here in the list and `another_test`
    # But you will not see `internal_test`
  end

  defp internal_test do
  end

end

```

**Comment by KronicDeth** [comment]
Thanks for the simple reproduction case.  I should be able to use it in a regression test.  ❤️
