### ISSUE TITLE
Using -1 as the matching clause in a "case" block is not recognized by the plugin

### ISSUE THREAD

**Issue by samhagman** [KronicDeth/intellij-elixir#1316]
Hello!  First off, thank you so much for this plugin I don't know what I would do without it.

The plugin is having a problem highlighting a `case` block where one of the matching clauses is `-1`

My setup info:
Plugin version `v9.0.0`
IntelliJ Info
![image](https://user-images.githubusercontent.com/5010240/47310609-9fdc5e00-d605-11e8-8dc1-7fc86bb9c661.png)

Here is a simple case block in a scratch file
![image](https://user-images.githubusercontent.com/5010240/47309108-9e109b80-d601-11e8-8bde-249e19d14e7d.png)

Here are the highlighted errors:
![image](https://user-images.githubusercontent.com/5010240/47309132-ac5eb780-d601-11e8-9763-1f3736ede3ff.png)
![image](https://user-images.githubusercontent.com/5010240/47309150-b2549880-d601-11e8-888d-644c2f1a3db6.png)

If I put parenthesis around the `-1` it highlights fine, but unfortunately `mix format` removes them
![image](https://user-images.githubusercontent.com/5010240/47310656-c0a4b380-d605-11e8-96e9-98fb7dbd750e.png)

**Comment by KronicDeth** [comment]
I really hate the rules for whether `-` and `+` works as a infix or prefix operator.  They've been nothing, but trouble.

**Comment by KronicDeth** [comment]
This is affecting the update to Elixir 1.11 as `list.ex` has a case with `-1` in its match.
