### ISSUE TITLE
Syntax highlight module attributes

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#132]
Module attributes should be colored so they pop like in vim-elixir:

![screen shot 2015-06-05 at 9 17 46 am](https://cloud.githubusercontent.com/assets/298259/8007786/c3764454-0b63-11e5-867d-0889defa7df0.png)

vs the plain white, no highlighting currently in intellij-elixir v0.3.4:

![screen shot 2015-06-05 at 9 18 28 am](https://cloud.githubusercontent.com/assets/298259/8007812/dd1af788-0b63-11e5-9a8b-89fc31a942a1.png)

**Comment by tylerhc** [comment]
This would help massively and was what I was coming to the issues section to verify someone had raised the request
