### ISSUE TITLE
README Debugger -> Configuration link broken

### ISSUE THREAD

**Issue by kekko1212** [KronicDeth/intellij-elixir#1326]
The link at `run/debug configuration` and `run configuration ` in the `Debugger` section of the README are both pointing to an anchor https://github.com/KronicDeth/intellij-elixir#run-configuration which is broken.

Is there any reference to how to define a run/debug configuration?

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir#rundebug-configurations
