### ISSUE TITLE
Debugger crashes

### ISSUE THREAD

**Issue by tungnt244** [KronicDeth/intellij-elixir#1338]
Hi every one, i try to run debugger on my project and met this issue, i exclude not interpreted module :jose, :jose*, JOSE, JOSE.*, public_key*. It run normally without debug mode. I'm using OTP 20, elixir 1.5.1
```

** (Mix) Could not start application jose: :jose_app.start(:normal, []) returned an error: shutdown: failed to start child: :jose_server
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:asn1, {{:nif_not_loaded, :module, :asn1rt_nif, :line, 107}, [{:erlang, :nif_error, [{:nif_not_loaded, :module, :asn1rt_nif, :line, 107}], []}, {:asn1rt_nif, :decode_ber_tlv_raw, 1, [file: 'asn1rt_nif.erl', line: 107]}, {:asn1rt_nif, :decode_ber_tlv, 1, [file: 'asn1rt_nif.erl', line: 83]}]}}}
            (public_key) public_key.erl:242: :public_key.der_decode/2
            (jose) src/jose_server.erl:178: :jose_server.check_ec_key_mode/2
            (stdlib) lists.erl:1263: :lists.foldl/3
            (jose) src/jose_server.erl:143: :jose_server.support_check/0
            (jose) src/jose_server.erl:89: :jose_server.init/1
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

```

**Comment by DenisGorbachev** [comment]
Excluding does _not_ work:

![image](https://user-images.githubusercontent.com/829578/48311772-ba6a7d00-e59c-11e8-8e80-4f0aa65016a6.png)

**Comment by DenisGorbachev** [comment]
Solved it by excluding `:asn1rt_nif`:

![image](https://user-images.githubusercontent.com/829578/48311826-7a57ca00-e59d-11e8-9909-248568724abc.png)

**Comment by tungnt244** [comment]
Thanks, after trying that, i bump into this, i'm new with elixir.
```
** (Mix) Could not start application jose: :jose_app.start(:normal, []) returned an error: shutdown: failed to start child: :jose_server
    ** (EXIT) an exception was raised:
        ** (ErlangError) Erlang error: {:nif_not_loaded, :module, :crypto, :line, 310}
            :erlang.nif_error({:nif_not_loaded, :module, :crypto, :line, 310})
            (crypto) crypto.erl:73: :crypto.nif_stub_error/1
            (crypto) crypto.erl:306: :crypto.strong_rand_bytes/1
```

**Comment by DenisGorbachev** [comment]
* Close IDE.
* Locate your `debugger.xml` file (mine was in `~/.WebStorm2018.2/config/options/debugger.xml`).
* Add extra exclusions ([full example](https://gist.github.com/DenisGorbachev/705f5a3f7773d1b84d03a94de97cec31)).
* Open IDE.
* Launch debugger.

**Comment by tungnt244** [comment]
Thank you, after adding :crypto, it finally run

**Comment by leonardo-dev-kenzie** [comment]
where is this file(~/.WebStorm2018.2/config/options/debugger.xml) today?

**Comment by KronicDeth** [comment]
@leonardo-dev-kenzie you shouldn’t need to edit the XML directly.  There is an Interpreted Modules tab on each Run configuration too.

**Comment by leonardo-dev-kenzie** [comment]
@KronicDeth thank you for quick answer.
I have to add 30 libs to ignore. There a way to do that all at once?

**Comment by leonardo-dev-kenzie** [comment]
yes! Thank You again!
I just put :* as you said.
I believe that just put :asn1rt_nif solve the problem, but in my case others libraries show errors(doesn't crash debugger), have making the debugger slow.
