### ISSUE TITLE
Build fails to open Terminal Session Windows (Alt + F4)

### ISSUE THREAD

**Issue by joaquinalcerro** [KronicDeth/intellij-elixir#1352]
I am having the following error:

Error running ‘run_in_iex’: com.intellij.terminal.JBTerminalWidget.createTerminalSession(Lcom/jediterm/terminal/TtyConnector;)Lcom/jediterm/terminal/ui/TerminalSession;

OS: OpenSuse Leap 15

IntelliJ IDEA 2018.3 (Community Edition)
Build #IC-183.4284.148, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.12.14-lp150.12.25-default

Java Version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-suse-lp150.2.3.2-x8664)
OpenJDK 64-Bit Server VM (build 10.0.2+13-suse-lp150.2.3.2-x8664, mixed mode)

The application does start but the error show up and unable to access the terminal (ALT+4) window.

The error showed up when I upgraded from IntelliJ IDEA 2018.2 -> IntelliJ IDEA 2018.3

**Comment by KronicDeth** [comment]
I think this has to do with a change to the Jediterm dependency in 2018.3.

**Comment by elaurendeau** [comment]
I have the same issue with the following version:

IDE version:
IntelliJ IDEA 2018.3.1 (Ultimate Edition)
Build #IU-183.4588.61, built on December 4, 2018
Licensed to Elliot Laurendeau
Subscription is active until June 16, 2019
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Error:
7:45 PM	Error running 'IEX': com.intellij.terminal.JBTerminalWidget.createTerminalSession(Lcom/jediterm/terminal/TtyConnector;)Lcom/jediterm/terminal/ui/TerminalSession;

**Comment by christiaan-janssen** [comment]
I'm having the same issue on Ubuntu:

```IntelliJ IDEA 2018.3.2 (Community Edition)
Build #IC-183.4886.37, built on December 17, 2018
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-42-generic```

```9:35	Error running 'IEx Mix': com.intellij.terminal.JBTerminalWidget.createTerminalSession(Lcom/jediterm/terminal/TtyConnector;)Lcom/jediterm/terminal/ui/TerminalSession;
```

**Comment by joaquinalcerro** [comment]
Totally working with 10.2.0. Thanks
