### ISSUE TITLE
Plugin Crash v10.1.0

### ISSUE THREAD

**Issue by fireproofsocks** [KronicDeth/intellij-elixir#1373]
# Description

Sorry again if this is a duplicate.  I have tried uninstalling the plugin and re-installing the latest version (10.1.0), but it still crashes about once per day, especially when working in EEx template files.  

# Exception

## Stacktrace

```
Don't know how to resolve variable in match
```

### Excerpt

```

            <li>
```
 Line(s) 14-15 in /Users/everettgriffiths/DropboxDM/rumbl/lib/rumbl_web/templates/layout/app.html.eex

### Element Class Name

```
org.elixir_lang.psi.impl.ElixirEexImpl
```

org.elixir_lang.errorreport.Logger.error(Logger.java:51)
org.elixir_lang.errorreport.Logger.error(Logger.java:34)
org.elixir_lang.psi.scope.Variable.execute(Variable.java:144)
org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarationsInPreviousSibling(ProcessDeclarationsImpl.kt:289)
org.elixir_lang.psi.impl.ProcessDeclarationsImpl.processDeclarations(ProcessDeclarationsImpl.kt:144)
org.elixir_lang.psi.impl.ElixirPsiImplUtil.processDeclarations(ElixirPsiImplUtil.java:591)
org.elixir_lang.psi.impl.ElixirStabBodyImpl.processDeclarations(ElixirStabBodyImpl.java:63)
com.intellij.psi.util.PsiTreeUtil.treeWalkUp(PsiTreeUtil.java:1140)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:90)
org.elixir_lang.psi.scope.variable.MultiResolve.resolveResultList(MultiResolve.java:68)
org.elixir_lang.reference.resolver.Callable.resolveElement(Callable.kt:34)
org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:20)
org.elixir_lang.reference.resolver.Callable.resolve(Callable.kt:13)
com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:595)
org.elixir_lang.reference.ResolveWithCachingComputable.compute(Callable.kt:587)
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
org.elixir_lang.reference.CallableKt.resolveWithCaching(Callable.kt:585)
org.elixir_lang.reference.CallableKt.access$resolveWithCaching(Callable.kt:1)
org.elixir_lang.reference.Callable.multiResolve(Callable.kt:108)
org.elixir_lang.reference.Callable.resolve(Callable.kt:115)
com.intellij.codeInsight.intention.AddAnnotationPsiFix.getContainer(AddAnnotationPsiFix.java:73)
com.intellij.codeInspection.dataFlow.EditContractIntention.getTargetMethod(EditContractIntention.java:46)
com.intellij.codeInspection.dataFlow.EditContractIntention.isAvailable(EditContractIntention.java:56)
com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:127)
com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:284)
com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:152)
com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:282)
com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:254)
com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:220)
com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by KronicDeth** [comment]
Bugs like this often occur when the resolver is running while you're typing or when you paused typing and the code is currently invalid.  This error is specific in the code, so that I can develop heuristics to make the resolver work when the code is only partially typed.  If you could include the contents of the file when the bug happens I can attempt to retry typing different section to reproduce the bug.

**Comment by KronicDeth** [comment]
No feedback received.
