### ISSUE TITLE
IEx and IEx Mix Not Working in Webstorm 2018.3

### ISSUE THREAD

**Issue by robpark** [KronicDeth/intellij-elixir#1377]
I'm trying to run Phoenix with it. `iex -S mix phx.server` 
The run configuration appears to be starting the server, because I have to kill the process (through ps) from the terminal, but this is the error I get: "Error running 'Run Interactive Server': com.intellij.terminal.JBTerminalWidget.createTerminalSession(Lcom/jediterm/terminal/TtyConnector;)Lcom/jediterm/terminal/ui/TerminalSession;"

**Comment by KronicDeth** [comment]
This is a duplicate of #1352.  It was fixed in https://github.com/KronicDeth/intellij-elixir/pull/1368, which was released in 10.2.0.  Update to 10.2.0.

**Comment by robpark** [comment]
👍 Thanks!
