### ISSUE TITLE
Issue with Elixir Module SDK in small IDEs

### ISSUE THREAD

**Issue by JerryBels** [KronicDeth/intellij-elixir#1378]
Hello,

(On PHPStorm).

Having already two projects configured correctly, I know that I have to select the Elixir facet SDK - but today I cloned two projects, an umbrella app from our company and https://github.com/socialpaymentsbv/ex_phone_number - and had issues.

First, the "Setup Elixir Module SDK" (and not `facet` now as it appears ?) link on top is not opening settings like it always did. And if I go to settings, I have no option in the `Elixir` menu. I can select a SDK in the `SDKs` menu and in the `Internal Erlang SDKs` menu, but it doesn't change anything.

One more issue with the umbrella project : it shows on the menu the list of apps that are in the "apps" directory, instead of root of the project. I'm not sure whether it's intended or not - I read something about that in the last update but I'm not sure how to understand it. Also, the root folders `config`, `deps` and `env` doesn't appear anywhere, and `tools` appears at the same level as folders from the `apps` folder.

**Comment by Flaires** [comment]
I can confirm this issue. The same problem occurs in WebStorm. You cannot click on the SDK link to the Setting Menu. Also the SDK isn't found. The warning message `ELIXIR_MODULE cannot found` is showed.

**Comment by wernerlaude** [comment]
I can confirm this issue in both WS and RM latest versions.
It is possible to open a phx project created with the WS Version before and all works fine. The Elixir env. is editable in the preferences and shows the correct env.
But not in latest WS and fresh created "mix new projectname". Link is is clickable but does not do anything, which is in a way logically because there is nothing to choose in the box

![bildschirmfoto 2019-01-08 17-46-56](https://user-images.githubusercontent.com/47493/50845645-a5785300-136d-11e9-91ff-e1258a7dbbdf.png)

![preferences 2019-01-08 17-44-18](https://user-images.githubusercontent.com/47493/50845440-2a16a180-136d-11e9-9d07-686f9ab241f8.png)

**Comment by drl123** [comment]
Having the same issue here on RM OSX.  What I noticed is a newly created project is not getting the `project-name.iml` file created in the `.idea` directory, which is where my Elixir facet was listed in an older project...not sure if that is expected behavior or not.

**Comment by mike-kasianov** [comment]
Got same issue on RubyMine. Here are some steps helped me to get rid of this message:

1. Open ```your_project_name.iml``` file in the root of your project and change ```ELIXIR_MODULE``` to ```RUBY_MODULE```.
2. Restart IDE. Now you are allowed to select Elixir SDK in IDE setting.

**Comment by wernerlaude** [comment]
Thanks Mike..
That really works..
WebStorm 2018.3.4

**Comment by storm255** [comment]
Can confirm it works with RubyMine 2018.3.4 as well.

Thanks

**Comment by drl123** [comment]
Yep, works for me too. RubyMine 2018.3.4 on OSX.

**Comment by rossvz** [comment]
Had the same issue recently with Webstorm 2018.3.4 and a new Phoenix/Elixir project. Deleted the `<project-name.iml` file along with `.idea` folder for the project and reopened Webstorm. Had to reconnect the SDK, but after that, plugin seems to be working as far as I can tell.

**Comment by JerryBels** [comment]
> Got same issue on RubyMine. Here are some steps helped me to get rid of this message:
> 
> 1. Open `your_project_name.iml` file in the root of your project and change `ELIXIR_MODULE` to `RUBY_MODULE`.
> 2. Restart IDE. Now you are allowed to select Elixir SDK in IDE setting.

This does work - for PHPStorm you got to user `WEB_MODULE` - but ... If then you browse one of your deps' code, the error message appears anew - and IDE is not friendly, not following ctrl+clicks or anything.

**Comment by KronicDeth** [comment]
Confirmed on https://github.com/socialpaymentsbv/ex_phone_number.  Doesn't do it on 8.0.0, does do it on latest.
