### ISSUE TITLE
Caching modules

### ISSUE THREAD

**Issue by nulian** [KronicDeth/intellij-elixir#1390]
Would it be possible to cache modules with the indexing that happens in the background. Because with a fairly large elixir project it currently takes the first time about a minute to load all the modules in the project before I get instant module autocomplete.
And that works for a while and then it needs to redo that cache again which makes it a bit hard to use the module autocomplete.

**Comment by KronicDeth** [comment]
The modules are already cached.  That's what the indexing is doinh.  The indexing creates a stub index for names in general (so modules, macros, and functions) and for Module in particular.  The Module-only one is used for Go To Class.

**Comment by nulian** [comment]
Then why does it take a minute for the first time in the day take and some other times after refresh take 1 minute to load the modules in the autocomplete.

I see the autocomplete on module with a spinner for 1 minute after that the modules are loaded and are autocompleted instantly for a while.
