### ISSUE TITLE
Select SDK step doesn't detect Elixir binaries for kiex + homebrew Erlang

### ISSUE THREAD

**Issue by svileng** [KronicDeth/intellij-elixir#1441]
I installed IntelliJ IDEA CE, installed the Elixir plugin and started importing an Elixir project. I followed the instructions and selected Mix from the first screen. Now I'm asked to select a project SDK and the README says:

```
If the automatic detection doesn't find your Elixir SDK or you want to use an older version, manually select select the directory above the bin directory containing elixir, elixirc, iex, and mix.
```

I tried adding `/Users/Svilen/.kiex/elixirs/elixir-1.8` (which has the `bin` folder and binaries) but that didn't produce any results and the screen still says "Nothing to show".

**To Reproduce**
1. Install Elixir 1.8 with Kiex 
2. Create Elixir project
3. Try to Import in IntelliJ idea 2019.1 with Elixir plugin

**Expected behavior**
Elixir is detected when I select the folder containing the binaries.

**Desktop:**
 - OS: MacOS
 - Version 10.14.3 (Mojave)

**Erlang:**
- Installer homebrew
- Version 21

**Elixir:**
- Installer kiex
- Version 1.8

**Plugin:**
- Version 10.4.0

**Comment by KronicDeth** [comment]
`.kiex` is one of the package managers that has a false `bin` directory that contains only links.  In your case, select `~/.liex/elixirs/elixir-1.8/lib/elixir` and the SDK will be setup correctly.

![Screen Shot 2019-04-12 at 9 55 40 PM](https://user-images.githubusercontent.com/298259/56073715-2597c580-5d6e-11e9-88a6-6c8a68d62d9b.png)

If you do that, you'll see that the Elixir `ebin` directories is included in the Classpath tab.

![Screen Shot 2019-04-12 at 9 56 08 PM](https://user-images.githubusercontent.com/298259/56073710-1fa1e480-5d6e-11e9-8b61-62629b92f567.png)
