### ISSUE TITLE
Underscore in binary and hexadecimal numbers causes a syntax error

### ISSUE THREAD

**Issue by gerritwalther** [KronicDeth/intellij-elixir#1478]
**Describe the bug**
When writing numbers one can use underscores to improve readability. The plugin allows underscores in decimal numbers, but not in other formats like hexadecimal, binary or octal base numbers:
0b000_1111
0o12_34
0xFF_00

**To Reproduce**
Create a module and write any of the above numbers into the module.

**Expected behavior**
No syntax errors

**Screenshots**
![2019-05-13-154032_166x112_scrot](https://user-images.githubusercontent.com/1128084/57626081-767d2280-7595-11e9-9d59-7952eff2be3c.png)

**Logs**
None

**Desktop:**
 - OS: Manjaro
 - Version: Linux Kernel 4.19.36-1-MANJARO

**Erlang:**
- Installer pacman/yay
- Version 21.3.2-1

**Elixir:**
- Installer pacman/yay
- Version 1.8.1-1

**Plugin:**
- Version 10.5.0

**Additional context**

**Comment by gerritwalther** [comment]
I guess you would have to adjust `https://github.com/KronicDeth/intellij-elixir/blob/0ed51042d2a3b827abfbdb22fe66ee2765b1a13b/src/org/elixir_lang/Elixir.flex`, especially `VALID_xyz_DIGITS` (xyz = [BINARY, OCTAL, HEXADECIMAL]). But that would also allow `0b_0001` or `0o1234_`, which is not allowed in Elixir.

**Comment by gerritwalther** [comment]
I now cloned the project, added SEPARATOR variables to the `Elixir.bnf` and adjusted the `*WholeNumber` to include possible  separators inbetween the digits. I adjusted the `Elixir.flex` accordingly. The next step would be to extend the `ElixirSyntaxHighlighter` and rebuild `ElixirFlexLexer`. 

Could you give me a hint on how to use jflex for Intellij Platform? Just running jflex-1.7.0 edits quite a lot of the file.

And if you could tell me how to rebuild the ElixirTypes, I might be able to create a PR.

**Comment by KronicDeth** [comment]
`ElixirTypes` is regenerated when you regenerate the parser from the BNF file.  Like the `.flex` file IntelliJ has hooks that Cmd+Shift+G will regenerate the code.

**Comment by gerritwalther** [comment]
Would you mind to share your import order config? I have 454 files changed, mostly because the order of the imports was changed.

The generator also adds a ton of `@Override`'s.

It also omits about 10 to 15 casts, which leads to some ambiguous calls (easy to fix).

**Comment by KronicDeth** [comment]
I temporarily unmark the gen folder as generated and run Optimize Imports on the folder to keep the import order consistent across versions of Grammar Kit.

The ambiguous calls I fix by hand.  Just use the change indicators from the gutter to restore the old casts.  That’s what I do.
