### ISSUE TITLE
Saves files without changes

### ISSUE THREAD

**Issue by Meldanor** [KronicDeth/intellij-elixir#1535]
**Describe the bug**
I'm working on a Phoenix projects with has auto compile enabled. It will not compile if there is a change in any of the config files (`config/dev.exs` for example) or the `mix.exs`. The IDE will randomly save the file (even if there is no change) to the disc and phoenix will recognize this as a change and will not compile anymore.

My settings for "Appearance & Behavior/System Settings/Synchronization" are:
 
- [x] Synchronize files on frame or editor tab activation
- [x] Save files on frame deactivation
- [ ] Save files automatically if application is idle for x seconds
- [ ] Use safe write (Save changes to a temporary file first)

It tried it with the 2nd, 3rd and 4th on/off without any changes.

**To Reproduce**
No way to reproduce. It is random. 

**Expected behavior**
The IDE should not write to file if there aren't any changes.

**Desktop:**
 - OS: macOs
 - Version [e.g. 10.14.3]

**Erlang:**
- Installer homebrew
- Version Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

**Elixir:**
- Installer homebrew
- Version 1.9.1  (compiled with Erlang/OTP 22)

**Plugin:**
- Version 10.6.0

**Comment by KronicDeth** [comment]
This is a base feature of JetBrains IDEs not something I specialized for Elixir.  Please open an issue with JetBrains' YouTrack for your IDE.
