### ISSUE TITLE
v11.0.0 works in IntelliJ 2019.2, but not Rubymine 2019.2

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#1547]
Amazing @KronicDeth : I re-installed from the release (from disk). RubyMine does not crash anymore, but I have no syntax highlighting.
The plugin seems to be installed correctly though. Most likely a user error. Appreciate all the hard work you put into this in any cases
<img width="530" alt="Screen Shot 2019-08-16 at 8 17 25 am" src="https://user-images.githubusercontent.com/3260198/63147450-837b3900-bffe-11e9-86c0-f20d42ee3f54.png">
<img width="1014" alt="Screen Shot 2019-08-16 at 8 17 46 am" src="https://user-images.githubusercontent.com/3260198/63147459-883fed00-bffe-11e9-991b-bbc3d8b92624.png">

_Originally posted by @olivierpichon in https://github.com/KronicDeth/intellij-elixir/issues/1527#issuecomment-521899131_

**Comment by KronicDeth** [comment]
![Screen Shot 2019-08-16 at 8 52 47 AM](https://user-images.githubusercontent.com/298259/63172423-46fe0c00-c003-11e9-8ed3-609cf4580884.png)

**Comment by olivierpichon** [comment]
Fantastic, I can confirm this works! Thanks for all the hard work and support! Really amazing ❤️
