### ISSUE TITLE
Indentation misalignment in .eex templates

### ISSUE THREAD

**Issue by nshafer** [KronicDeth/intellij-elixir#1594]
**Describe the bug**
When editing files marked as "Embedded Elixir", hitting enter after an opening tag results in the closing tag getting punted to column 1 and the cursor not being indented properly. I have configured both `*.eex` and `*.leex` and I get the same behavior. I have also recreated my `.IntelliJIdea2019.2` setting folder, and completely recreated the `project.iml` and `.idea/` directories in an attempt to fix this behavior, and nothing has worked. Renaming the file from `test.html.eex` to just `test.html` fixes the behavior, but then of course I don't have formatting of the Elixir components. Thanks for the help!

**To Reproduce**
1. Create a file with `.eex` extension.
2. Write an opening tag, such as `<div>` which will result in `<div>I</div>` where the `I` is the cursor.
3. Hit Enter

**Expected behavior**
I expect the closing tag to be indented to match the opening tag, and the cursor to be indented one more level in between with a blank line.

**Screenshots**
This is the behavior I expect:

![Screenshot_2019-09-27_10-00-21](https://user-images.githubusercontent.com/3673047/65787384-ad4f7180-e10d-11e9-8fb7-fe808e82eb20.png)

This is the behavior I observe:

![ezgif-2-950ddbcf9bad](https://user-images.githubusercontent.com/3673047/65788213-6cf0f300-e10f-11e9-9554-23c292dfbe0e.gif)

**Desktop:**
 - OS: Ubuntu Xenial
 - Version 16

**Erlang:**
- Installer erlang-solutions
- Version 22

**Elixir:**
- Installer erlang-solutions
- Version 1.9.1

**Plugin:**
- Version 11.1.0

**Comment by nshafer** [comment]
Oh yeah, this is with IntelliJ IDEA Ultimate 2019.2.3, the latest at this time. Thanks!

**Comment by niknetniko** [comment]
Some information: I have done some experimenting with registering `SimpleTemplateLanguageFormattingModelBuilder` as the formatter for eex files. This seems to work fine and formats most of the file correctly.

One complication is that code inside eex blocks (e.g. <% if ... do %>) is not indented. I have tried implementing the `AbstractXmlTemplateFormattingModelBuilder`, but getting that to work is non-trivial, and I haven't found a way to do that yet.

Would there be interest in a small PR enabling the `SimpleTemplateLanguageFormattingModelBuilder`?
