### ISSUE TITLE
New file dialog order

### ISSUE THREAD

**Issue by jaketrent** [KronicDeth/intellij-elixir#161]
This plugin is awesome.  Thank you for your work on it.  

I have a suggestion to change the location of the 'Exilir File'  option in the `ctrl-N`-activated 'New file' popup dialog.  I propose that it go below the separator line with the other language-specific file options so that the options above the separator line remain generic.  

This will:
- Keep the separation in this dialog clear between generic and specific file types
- Keep the `ctrl-N enter` keyboard shortcut workflow as it is be default, selecting `New > file`

What do you think?

**Comment by KronicDeth** [comment]
I'm not actually sure how the ordering is controlled.  I just copied what intellij-erlang did and it's also above the separator.

![screen shot 2015-07-16 at 10 32 12 am](https://cloud.githubusercontent.com/assets/298259/8727609/39a37f22-2ba6-11e5-970f-54d800f1d8f9.png)

Do you know an open source plugin where it has the '<language> File' below the separator, so I can figure out how they did it?

**Comment by jaketrent** [comment]
Great question.  I'm not sure right now.  I'll keep an eye out.
