### ISSUE TITLE
Unknown elixir version - Windows

### ISSUE THREAD

**Issue by Jasperav** [KronicDeth/intellij-elixir#1615]
**Describe the bug**
I get IntelliJ errors when trying to create a project with Elixir as project SDK

**To Reproduce**
Install elixir 1.9.2
Install erlang 22.1
Install IntelliJ 2019.2.3
New project, select elixir, than first I need to select the erlang installion directory which I did. After I selected the elixir directory the following error appears:

![image](https://user-images.githubusercontent.com/20363565/68074817-14f97c00-fda0-11e9-8f9a-562415e7ad8f.png)

Worth noting I tried the exact thing a few months ago and got the same error. All the other related issues is about OSX

**Comment by KronicDeth** [comment]
This should be fixed by 11.3.0, which was released 4 days ago.  If it is still not fixed for you on Windows, please comment and I'll reopen.

**Comment by PatrickSachs** [comment]
Still getting this error on 11.7.0 on Linux. I am not using a release of Elixir but a self compiled version on master. 

![image](https://user-images.githubusercontent.com/7840502/88703108-94886180-d10c-11ea-891c-244a63fe0fc2.png)
