### ISSUE TITLE
Autocomplete for Erlang modules

### ISSUE THREAD

**Issue by trucndt** [KronicDeth/intellij-elixir#1631]
Hello,

Could you add support for Erlang modules? For example, if I type in
```elixir
:ets.
```
and then press Ctrl + Space, it will say `No suggestions`. I hope it can suggests some methods like `insert`, `new`, etc.

Thank you !

**Comment by KronicDeth** [comment]
This works for me.  If it doesn't work for you, make sure your External Libraries shows your SDK and has an ebin directory for Erlang containing `ets.beam`.

![Screen Shot 2020-04-10 at 12 05 34 PM](https://user-images.githubusercontent.com/298259/79008818-cce73e00-7b23-11ea-8f05-9ef7b72e1325.png)

![Screen Shot 2020-04-10 at 12 06 13 PM](https://user-images.githubusercontent.com/298259/79008825-d2448880-7b23-11ea-93fb-ff4b9413a7ce.png)

Make sure both your Project and Module level SDKs are set

![Screen Shot 2020-04-10 at 12 09 50 PM](https://user-images.githubusercontent.com/298259/79009013-37987980-7b24-11ea-9312-19f4724aac12.png)

![Screen Shot 2020-04-10 at 12 09 58 PM](https://user-images.githubusercontent.com/298259/79009025-3bc49700-7b24-11ea-8ad4-ef3568585938.png)
