### ISSUE TITLE
Installation of plugin on fresh install of IntelliJ Idea 2019 causes the IDE to hang

### ISSUE THREAD

**Issue by nyxcharon** [KronicDeth/intellij-elixir#1653]
**Describe the bug**
When using a fresh install of IntelliJ IDEA Community 2019.2.4 and installing the elixir plugin, the ide essentially hangs on the welcome page after restarting.

**To Reproduce**
1. Install IntelliJ IDEA Community 2019.2.4 (or wipe your settings folder) 
2. Open IntelliJ.  Install the Elixir Plugin
3. Restart the IDE after installing the plugin
4. You should see a red (!) icon in the bottom, and the welcome screen should be generally unresponsive.

**Expected behavior**
The IDE to respond after installing the plugin

**Logs**
The message
`llij.ide.plugins.PluginManager - null`
is show over and over in the logs

**Desktop:**
 - OS: Ubuntu 18.04

**Erlang:**
- Installer: Ubuntu Package Manager
- Version 22

**Elixir:**
- Installer: Ubuntu Package Manager 
- Version 1.9.4

**Plugin:**
- Version 11.5.0/11.4.0

**Comment by KronicDeth** [comment]
Not enough information to reproduce.  I'll reopen if someone reports with a longer long.
