### ISSUE TITLE
Test Runner Crashes with invalid iolist

### ISSUE THREAD

**Issue by jeresis** [KronicDeth/intellij-elixir#1674]
**Describe the bug**
When running my tests (via the Elixir Mix ExUnit template) when a test fails the entire test suite seems to crash. Running "mix test" works correctly when run directly in the console.

The following error is in the test log.

`15:33:59.102 [error] GenServer #PID<0.413.0> terminating
** (ArgumentError) argument error
    :erlang.iolist_to_binary([[[[] | "\e[31m"], {:doc_cons, {:doc_cons, "\"effective_end_date\"", " => "}, "\"2011-05-18T15:01:01Z\""}] | "\e[0m"])
    c:/Users/USER/AppData/Local/Temp/intellij_elixir3/exunit/1.6.0/team_city_ex_unit_formatting.ex:236: TeamCityExUnitFormatting.colorize/2
    (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ex_unit 1.10.1) lib/ex_unit/diff.ex:970: ExUnit.Diff.container_to_algebra/5
    (ex_unit 1.10.1) lib/ex_unit/formatter.ex:377: ExUnit.Formatter.format_sides/6
    (ex_unit 1.10.1) lib/ex_unit/formatter.ex:365: ExUnit.Formatter.format_context/4
    (ex_unit 1.10.1) lib/ex_unit/formatter.ex:158: ExUnit.Formatter.format_assertion_error/6
    (ex_unit 1.10.1) lib/ex_unit/formatter.ex:190: ExUnit.Formatter.format_kind_reason/6
    (ex_unit 1.10.1) lib/ex_unit/formatter.ex:130: anonymous fn/7 in ExUnit.Formatter.format_test_failure/5
    (elixir 1.10.1) lib/enum.ex:1495: anonymous fn/2 in Enum.map_join/3
    (elixir 1.10.1) lib/enum.ex:3359: Enum.map_intersperse_list/3
    (elixir 1.10.1) lib/enum.ex:1495: Enum.map_join/3
    (ex_unit 1.10.1) lib/ex_unit/formatter.ex:129: ExUnit.Formatter.format_test_failure/5
    c:/Users/USER/AppData/Local/Temp/intellij_elixir3/exunit/1.6.0/team_city_ex_unit_formatting.ex:126: TeamCityExUnitFormatting.put_event/2
    c:/Users/USER/AppData/Local/Temp/intellij_elixir3/exunit/1.6.0/team_city_ex_unit_formatter.ex:11: TeamCityExUnitFormatter.handle_cast/2
    (stdlib 3.6) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.6) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.6) proc_lib.erl:249: :proc_lib.init_p_do_apply/3`

**Desktop:**
 - OS: Windows
 - Version 10

**Erlang:**
- Installer Installed when installing elixir.
- Version 21

**Elixir:**
- Installer The elixir web installer
- Version 1.10.1

**Plugin:**
- Version 11.5.0

**Comment by KronicDeth** [comment]
It looks like you're output non-`iolist` content to your logger.  Are you using a special logger format?

**Comment by jeresis** [comment]
I don’t believe so, I didn’t manually change anything from the default settings.

Sent from Mail for Windows 10

**Comment by i1t** [comment]
I confirm the issue. The plugin fails with the latest version of Elixir 1.10, since the introduction of "pattern-matching diffing" (see https://github.com/elixir-lang/elixir/releases/tag/v1.10.0).

**Comment by IvanShpotenko** [comment]
I had the same issue, but it is fixed for me in v11.6.1 after #1762 pr

**Comment by KronicDeth** [comment]
Considered fixed by #1762 based on https://github.com/KronicDeth/intellij-elixir/issues/1674#issuecomment-633512860
