### ISSUE TITLE
Syntax highlight of .leex files

### ISSUE THREAD

**Issue by D4no0** [KronicDeth/intellij-elixir#1678]
Currently only `.eex` template files are highlighted. With introduction of LiveView, the LiveView template files have extension `.leex`, witch currently is displayed only as white text.

**Comment by tschmidleithner** [comment]
As a temporary workaround you could register `*.leex` as an additional pattern for the "Embedded Elixir" file type.

1. Make sure that intellij-elixir plugin is installed.
2. Go to Settings/Preferences dialog `Ctrl+Alt+S`, select Editor | File Types.
3. Under "Recognized file types", select "Embedded Elixir".
4. Below you can find "Registered patterns". Click the "+" symbol (or `Ctrl + Insert`) and insert `*.leex`  in the field "Enter a new wildcard" (leave "Template data language" unselected).
5. Click "OK" and "Apply".
6. All LiveView templates with file extension `.leex` should have the same syntax highlighting as your `.eex` files have.

![image](https://user-images.githubusercontent.com/6713737/76416199-e49f9b00-639a-11ea-861c-b74111bf43c9.png)

**Comment by D4no0** [comment]
That's exactly what I've done. It seems to work without any problems.
