### ISSUE TITLE
Autocomplete does not work inside module/function scope

### ISSUE THREAD

**Issue by IvanShpotenko** [KronicDeth/intellij-elixir#1780]
**Describe the bug**
Autocomplete for Kernel functions (guards, macros etc.) does not appear to work for me inside a module or inside a function. 

However, it works just fine when you start typing outside the module.
Otherwise, autocomplete seems to work ok, eg. for other built-in functions like Map.get() or Enum.map()

**To Reproduce**
1. Go to the outside of module scope
2. Start typing `is_`, suggestions appear
3. Go to inside a module, start editing function
4. Start typing `is_`
5. Suggestions do not appear

**Expected behavior**
Autocomplete for Kernel functions and macros to work inside module/function.

**Screenshots**
![Screen Recording 2020-05-22 at 13 25 18](https://user-images.githubusercontent.com/16348408/82790992-a8e28080-9e75-11ea-9dc0-e54fb6951bef.gif)

**Desktop:**
 - OS: macOS Catalina
 - Version: 10.15.4 (19E287)

**Erlang:**
- Installer: asdf with erlang plugin
- Version 22.2.8

**Elixir:**
- Installer: asdf with elixir plugin
- Version: 1.10.2-otp-22

**Plugin:**
- Version: 11.7.0

**IntellijIdea**
- Version: Ultimate 2020.1.1

Nevertheless, thanks for a great plugin and a great IDE experience!

**Comment by markomitranic** [comment]
@KronicDeth I have noticed this as well and can confirm. I was wondering, what is the state of this issue, and what does the "Version Manager:asdf" tag mean?

btw It is weird in general how autocomplete decides what to show. 
- `is_list` works normally outside module scope.
- `Enu` offers Enum only after a huge delay.
- `Faker.Address.` will offer submodules, but not actual useful functions.

Just testing around i have noticed that VSC-ElixirLS, with all its flaws (and there are tons) performs this particular job pretty well, and we don't even tho we have a more powerful IDE at our disposal - why is that? Is it a technical limitation of some sort?
