### ISSUE TITLE
Indexing runs forever (Intellij IDEA 2020.1.2)

### ISSUE THREAD

**Issue by eoh1980** [KronicDeth/intellij-elixir#1791]
**Describe the bug**
Downloaded the latest version of Intellij IDEA Ultimate 2020.1.2 paired with this Elixir plugin version 11.7.0 and Erlang plugin version 0.11.1059.  (all the latest) When opening an elixir umbrella project, Intellij starts to index all of the project files.  Then towards the end of indexing, it starts to index the bundled plugins that come with Intellij and gets stuck (spins forever) on:
`/Applications/IntelliJ IDEA.app/Contents/plugins/restClient/lib/restClient.jar!/com/intellij/ws/rest/client/requests/collection`

From here, I thought to disable all of the bundled plugins that come with 2020.1.2 except for Elixir and Erlang.  This results in getting stuck on:
`/Applications/IntelliJ IDEA.app/Contents/lib/intellij-xml.jar!/standardSchemas/xhtml-mobile` 

I'm using asdf and set up the SDK for both Erlang and elixir.  As a result of this index hang, i'm unable to `Command + Click` on aliases or functions since indexing is always in progress.  I've also been `File -> Invalidate Caches / Restart` to reindex every time.

**To Reproduce**
I acknowledge this will be tough to reproduce if it has something to do with our github repo. But I'm hoping that with the provided information, some headway can be made with any elixir repo or if others experience the same thing, they can _like_ this issue.

**Expected behavior**
Indexing should complete resulting in `Command + Clicking` on aliases

**Screenshots**
Hangs forever on:
![image](https://user-images.githubusercontent.com/23371562/84928572-3ccdf380-b094-11ea-9a29-e80c90c08ec4.png)

After removing ALL plugins except for elixir and erlang, hangs forever on:
![image](https://user-images.githubusercontent.com/23371562/84929234-270cfe00-b095-11ea-9ccd-e169bedb3c5f.png)

SDK Setup:
![image](https://user-images.githubusercontent.com/23371562/84929034-e57c5300-b094-11ea-831f-37e53bd2b0b6.png)

**Logs**
[thread_dump.txt](https://github.com/KronicDeth/intellij-elixir/files/4794328/thread_dump.txt)

**Desktop:**
 - OS: macOS Mojave
 - Version 10.14.6

**Erlang:**
- Installer asdf
- Version 22.3.4.1

**Elixir:**
- Installer asdf
- Version 1.10.3-otp-22

**Plugin:**
- Version 11.7.0

**Comment by KronicDeth** [comment]
There's no reason for my plugin to index jars.  It wouldn't even know those are there since they're not part of the Elixir or Erlang SDK Class Paths.

You should report this as a bug to JetBrains about the performance of their Java Indexing since it is indexing Java Jars.
