### ISSUE TITLE
Plugin cannot setup Erlang/Elixir that was installed with asdf

### ISSUE THREAD

**Issue by locopati** [KronicDeth/intellij-elixir#1794]
**Describe the bug**
When elixir & erlang are installed with asdf, you cannot add an Erlang SDK for Elixir SDK

**To Reproduce**
1. Install a version of Erlang and Elixir via asdf (which will place them in the ~/.asdf directory)
2. `which erl` should indicate `$HOME/.asdf/shims/erl`
3. Create a new Elixir project in IDEA
4. Add an Erlang SDK for Elixir SDK 
5. Point to the ~/.asdf/shims directory

**Expected behavior**
It accepts that directory as a valid home 

**Actual Behavior**
It displays an error message "The selected directory is not a valid home for Erlang SDK for Elixir SDK"

**Desktop:**
 - OS: Linux
 - Version Arch

**Erlang:**
- Installer asdf
- Version 21

**Elixir:**
- Installer asdf
- Version 1.8

**Plugin:**
- Version 11.7

**Comment by IvanShpotenko** [comment]
Hey, as stated in readme, you can specify `installs` directory instead of shims, eg. `~/.asdf/installs/erlang/23.0.2`. Same goes for elixir, eg. `~/.asdf/installs/elixir/1.10.3-otp-22`.
Works for me this way with erland & elixir installed with `.asdf`.
Hope this helps!

**Comment by noozo** [comment]
What worked for me was adding ~/bin to the path and adding the following symlinks to ~/bin:
`lrwxrwxrwx  1 void void       29 set 21 11:38 elixir -> /home/void/.asdf/shims/elixir
lrwxrwxrwx  1 void void       26 set 21 11:38 erl -> /home/void/.asdf/shims/erl
lrwxrwxrwx  1 void void       26 set 21 11:38 iex -> /home/void/.asdf/shims/iex
lrwxrwxrwx  1 void void       26 set 21 11:38 mix -> /home/void/.asdf/shims/mix`

With that all set, restarting the IDE and adding the SDKs again (erlang first then elixir) it works properly.

**Comment by x984a** [comment]
Neither of the above solutions (selecting installs/erlang/<version>, or creating ~/bin dir with sym links) will resolve this issue. Any selected folder generates the same "selected directory is not a valid home for Erlang SDK for Elixir SDK" even after restarts, globals, etc.  This is on Ubuntu 20.10 with the erl/elixir installation working properly.

Are there any other workarounds that will get this working?
