### ISSUE TITLE
Can't ctrl click on modules in IntelliJ 2020.2

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#1799]
**Describe the bug**
In IntelliJ 2020.2 BETA, you can't ctrl click on modules.

**To Reproduce**
1. Install IntelliJ 2020.2 BETA
2. In a module, ctrl+click on another module
3. It doesn't work

**Expected behavior**
It goes to a module.

**Logs**
None?

**Desktop:**
 - OS: [e.g. macOS]
 - Version [e.g. 10.14.3]

**Erlang:**
- Installer: asdf
- Version: 23

**Elixir:**
- Installer: asdf 1.10.3

**Plugin:**
- Version 11.7.0

**Comment by muspellpete** [comment]
I realized that if i hover a part of the module name (e.g. "Adapters" in Ecto.Adapters.Postgres) it will fail to navigate, but if i hover a period it will mark the whole thing and navigate correctly.

**Comment by odk211** [comment]
Same in IntelliJ IDEA 2020.2 (Ultimate Edition).

**Comment by joshuataylor** [comment]
Hey @KronicDeth , do you know if this is an issue on IntelliJ's side, or the plugins side? I can raise an issue with IntelliJ or something, maybe?

**Comment by joshuataylor** [comment]
I'm putting a $200USD bounty on getting this fixed.

**Comment by kreba** [comment]
I'll be donating about that amount, too, as I have the past couple years. And I'd love to see this improved!
Go to definition is such a productivity boost, it should work for all things and everywhere.

**Comment by odk211** [comment]
Same in v11.9.0.

**Comment by KronicDeth** [comment]
The references resolve for Aliases fine when I debug, so it is some change in the Target system.  When I first got Find Usage/Go To Declaration working, I had to do some hacks to stop usages as being declaration, but it could be that those hacks are now broken due to upstream fixes.

**Comment by ghenry** [comment]
Is this the same thing as attached? I can't ctrl click in my Phoenix app.
[Screencast from 11-07-22 15:23:32.webm](https://user-images.githubusercontent.com/159608/178287107-70623e38-57ce-49fb-87ad-a02bc65d26d3.webm)
