### ISSUE TITLE
Travis-ci got `cannot find symbol` error

### ISSUE THREAD

**Issue by zyuyou** [KronicDeth/intellij-elixir#180]
![2015-07-31 12 44 06](https://cloud.githubusercontent.com/assets/1913492/9000928/5972beb6-3782-11e5-8a80-c63e4c0702fe.png)

As showed in [travis-ci#291](https://travis-ci.org/KronicDeth/intellij-elixir/builds/73492887),  I got the same error before, but I don't know why, so I just suppose that I have got the newer idea's source code which contains some methods like `FileTemplateManager.getDefaultInstance()`, but these methods didn't be contained in the newest released IDEA's lib, and the travis-ci using this released IDEA , so it catched the error. am I right?

**Comment by KronicDeth** [comment]
It appears that the build cache was not invalidated correctly and the old, 14.0.2 version of IDEA Community Edition was used on master.  I manually deleted the build cache on master on travis-ci.org and restarted [the build](https://travis-ci.org/KronicDeth/intellij-elixir/builds/73492887) and it succeeded.

Sometime in the future, when there aren't more important features or bugs to work on, I'll have to figure out how to fix `idea.xml` so it invalidates on version change correctly.
