### ISSUE TITLE
Run config for a specific test file

### ISSUE THREAD

**Issue by chris** [KronicDeth/intellij-elixir#183]
Hi, first, thanks for making the Elixir plugin! I'd like to be able to run a specific test file instead of just `mix test`/the entire test suite. I'm not seeing how I could configure this. Is it possible? RubyMine has this for example.

**Comment by zyuyou** [comment]
Yes, it is possible. but I not sure that in RubyMine, I will try for that.

@KronicDeth, since this **ExUnit** feature need some powerfull parser as I said in [this comment](https://github.com/KronicDeth/intellij-elixir/pull/167#issuecomment-125969935), would you plan to do that?

**Comment by KronicDeth** [comment]
I can writing the Util methods to determine whether you're in the context of an entire file or inside a specific `test "name" do end` block.  @zyuyou have you looked into how to make test runners in general so we get the red/green/yellow dots for error/passed/failed test like the JUnit and RSpec test runners while the test is running?  If you haven't I'll have to add support for the test runners too.

**Comment by zyuyou** [comment]
Yes，I have looked into that. but I think I have no much time to do that, since I should find a new job at this month after  a short break.

**Comment by KronicDeth** [comment]
It's no problem if you don't have time to work on it.  This is all volunteer work.  Just let me know if you volunteer to do something and you find out you don't have time to finish it so that I know to reassign it to myself.

**Comment by KronicDeth** [comment]
Resolved by #482, which was released in `4.7.0` and contains ExUnit configurations from context of directory, file, and line.
