### ISSUE TITLE
Not worked syntax check

### ISSUE THREAD

**Issue by dmitrydprog** [KronicDeth/intellij-elixir#1842]
**Describe the bug**
Not worked syntax check.
On first screen i open VsCode with ElixirLS and IDEA with Elixir plugin, result from IDEA not verbose and looks ugly.
On second screen Elixir plugin do not show error.

**To Reproduce**
1. Create file foo.ex in lib directory in your project
2. Insert next code to file:
```
defmodule Foo do
  def foo do
    a = _ + 5
  end
end
```
3. Press Ctrl+S (save file)
4. Errors do not showing

**Screenshots**

![Screenshot 2020-10-28 at 19 04 33](https://user-images.githubusercontent.com/10886027/97434937-550f2280-1952-11eb-93be-d7fa3545f3dd.png)

![Screenshot 2020-10-28 at 19 06 01](https://user-images.githubusercontent.com/10886027/97434950-58a2a980-1952-11eb-87c2-5aeb6d3ea713.png)

![Screenshot 2020-10-28 at 19 15 05](https://user-images.githubusercontent.com/10886027/97434962-5b050380-1952-11eb-9f7c-ef0e2740c6e2.png)

**Desktop:**
 - OS: [macOS]
 - Version [e.g. 10.15.7]

**Erlang:**
- Installer [asdf]
- Version [22.3.4.11]

**Elixir:**
- Installer [asdf]
- Version [1.11.1-otp-22]

**Plugin:**
- Version [11.8.1]

**Comment by KronicDeth** [comment]
You're seeing compilation errors, not syntax errors; you need to compile to see compilation errors.  Because ElixirLS only works on compiled code you always see compilation errors after saving.  You compile when you want to compile in IntelliJ Elixir.
