### ISSUE TITLE
Syntax highlighting bug on `\` character in multiline string

### ISSUE THREAD

**Issue by rossvz** [KronicDeth/intellij-elixir#1843]
**Describe the bug**
When using a multiline string with `"""`, you can use the `\` character to avoid a line break. Useful for wrapping the code but not the output. In IntelliJ, however, this breaks syntax highlighting, even though the code compiles and runs fine.

**To Reproduce**
Define a multiline string with `"""` and `\` character in it. 

**Expected behavior**
Highlighting breaks below `\` character (treats it like the string isn't closed)

**Screenshots**
![image](https://user-images.githubusercontent.com/9866589/97466026-07c28f00-1919-11eb-9fb9-4c3693def3e8.png)

**Logs**

**Desktop:**
 - OS: macOS 
 - Version 10.14.6

**Erlang:**
- Installer asdf
- Version 22

**Elixir:**
- Installer asdf
- Version 1.10.0

**Plugin:**
- Version 11.8.1

**Additional context**

**Comment by KronicDeth** [comment]
This is used in `capture_io.ex`, so it affects upgrading the build to Elixir 1.11.
