### ISSUE TITLE
Use FileViewProvider to handle eex

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#186]
FileViewProviders are [documented](http://www.jetbrains.org/intellij/sdk/docs/basics/architectural_overview/file_view_providers.html) as being used to support languages embedded in each other and html.eex is Elixir embedded in HTML, so a FileViewProvider might be a way to support eex templates for Phoenix

**Comment by hipertracker** [comment]
Will it be added to intellij-elixir? *.eex is the default template extension for Phoenix

**Comment by KronicDeth** [comment]
If an issue is open, the feature will be implemented eventually.  I keep the issues very well groomed.  If I wasn't going to implement something the issue would be closed with an explanation.

**Comment by nenros** [comment]
Maybe we could make support for that task using gratipay or smth like that? It is most missing function for me!

**Comment by KronicDeth** [comment]
I opened a team application on Gratipay: https://gratipay.com/intellij-elixir/.  It says it make take up-to a week to be approved (https://github.com/gratipay/team-review/issues/155).

I also already had Paypal Donate setup.  It's linked at the bottom of the README.

**Comment by whit537** [comment]
@nenros @KronicDeth Gratipay team approved! Welcome aboard! :-)

https://gratipay.com/intellij-elixir/

**Comment by joshuataylor** [comment]
Wanting to use phoenix with this, can put up a $50USD bounty if that would help? :-)

**Comment by BenBals** [comment]
is this issue still relevant?

**Comment by douglascorrea** [comment]
I think it is relevant yet, I use this plugin and I missing eex file syntax highlight

**Comment by joshuataylor** [comment]
I just use HTML formatting for *.html.eex files. Allows highlighting + indenting.

**Comment by KronicDeth** [comment]
[This post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206765105-Tutorial-Custom-templating-language-plugin) seems like a good lead, but doesn't cover how to reuse `Elixir.bnf` once I'm inside the `<%= %>` tags.

**Comment by KronicDeth** [comment]
Peter Gromov's reply in [this post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206780275-Example-of-a-custom-language-plugin-for-a-templating-language) explains mixing the other direction

**Comment by natecox** [comment]
@KronicDeth Any updates here? Loving this plugin so far, but it would be great to see .eex support.

Sidenote/derail: I wish I could nominate this to get a standalone IDE. **JetBrains elChemist** or some such thing.

**Comment by DFilipeS** [comment]
@KronicDeth Any updates on this issue? I think this is one of the final big pieces missing from this plugin.

**Comment by KronicDeth** [comment]
@natecox, @DFilipeS I'm concentrating on decompilation, completion, and Go To Declaration for `.beam`-only modules, such as those in the Elixir standard library (when installed as a binary release, such as with homebrew) and Erlang standard library because that will lead to universal-completion and I can start marking unresolved functions and modules in future releases.  All next-release planned work is in the [`v5.0.0`](https://github.com/KronicDeth/intellij-elixir/milestone/19) milestone.

This issue will remain low-priority for me because it's both (1) hard (I still am not confident in how to implement it precisely) and (2) I don't use `.eex` in any of my work or personal projects, so it would only get regular testing by the user-base.

There has been a request by @darkbushido for me to add generators to C-S-D/calcinator, so that would would use `.eex` for the template files, which would fulfill (2) and only leave the tough part of (1) actually figuring out how to do it.

**Comment by OvermindDL1** [comment]
Do note, there is not just `*.html.eex`, there is `*.blah.eex` for anything of `blah`.  I personally have `*.ic.html.eex`, `*.un.html.eex`, `*.json.eex`, `*.css.eex`, among others.

**Comment by KronicDeth** [comment]
@OvermindDL1 I'm aware the eex isn't just for html.eex.  The injected/chameleon language system for OpenAPI doesn't care about the mixed in language.

One has to mark the triggering nodes (so the `<%`, `<%=`, and `%>` and then give a what they've referred to as a "chameleon" node for the injected language to occupy that part of OpenAPI).  My understanding of how JetBrains has explained the Ruby grammar for Rubymine is that the "Ruby" grammar is really an `.erb` grammar with some mechanism to turn off the triggering nodes and the chameleon nodes when it's a normal .rb file, so something similar has to be done for the plugin.

It's also an open question how I inform OpenAPI the injected language types based on the file extension since Rubymine appears to have some special handling for things like `.rhtml`, but that could be just a side effect that's it's `.rhtml` and not `html.erb`.

**Comment by jsrosen3** [comment]
Hey @KronicDeth , just wondering if there was any update on this. Absolutely love your plugin and this would make it even better! Many thanks.

**Comment by KronicDeth** [comment]
@jsrosen3 no, no updates.  Getting OTP 20 chunk support and updating the lexer to support unicode is the priority now.

**Comment by stefanjarina** [comment]
Just wondering if this might help - Vue.js plugin have syntax and intellisense for '.vue' files which have mixed html, js, css in one file, which seems to be similar to what eex does? Maybe worth to look how they are doing it:
https://github.com/JetBrains/intellij-plugins/tree/master/vuejs
I do lot of phoenix work and because of missing eex support can't really use this plugin and need to use atom or vscode.  All my other work, like javascript is in Webstorm, golang is in Gogland, so really miss this ;-)
Anyway, thank you for your effort.

**Comment by KronicDeth** [comment]
![screen shot 2017-11-12 at 6 39 44 pm](https://user-images.githubusercontent.com/298259/32705556-3d429202-c7db-11e7-928e-6b7afdf9ad1d.png)
![screen shot 2017-11-12 at 6 40 52 pm](https://user-images.githubusercontent.com/298259/32705555-3d32d90c-c7db-11e7-8209-a68ff8ebf0e6.png)
![screen shot 2017-11-12 at 6 45 58 pm](https://user-images.githubusercontent.com/298259/32705554-3d238394-c7db-11e7-8092-8e42889a3289.png)

**Comment by stefanjarina** [comment]
This is just awesome. Thank you a lot for your hard work :-)

**Comment by joshuataylor** [comment]
This is awesome, well done! Such hard work!

**Comment by kandeshvari** [comment]
Thanks! When 6.6.0 will be released?

**Comment by KronicDeth** [comment]
@kandeshvari now? now! https://twitter.com/KronicDeth/status/937060629566885888

**Comment by kandeshvari** [comment]
Awesome! Thanks a lot!

**Comment by x-ji** [comment]
Now there seems to be an issue where if I comment in an `.html.eex` file, IntelliJ will automatically add `#` to the beginning of the line, which is not correct. Do you know where I might be able to change this behavior? Thanks.
