### ISSUE TITLE
Syntax highlighting is still broken frequently after upgrade plugin to 11.9.2-pre+20210119174940

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#1889]
**Describe the bug**
Similar to https://github.com/KronicDeth/intellij-elixir/issues/1874 https://github.com/KronicDeth/intellij-elixir/issues/1882
Plugin version 11.9.0-pre+20201121032253 works correctly.

**To Reproduce**
1. Type `Map.put(%{}, :a, 1)`.
2. Syntax highlighting is broken at end after typing `:a`
3. Some typing completion do not work(when I type `%{` , corresponding `}` is not put).

Syntax highlighting and completion only fixed by closing the file and reopening it again.

**Screenshots**

https://user-images.githubusercontent.com/1321120/105136467-0928df80-5b35-11eb-8002-34d112bebe73.mov

**Logs**
No error occurred.

**Desktop:**
 - OS: macOS Catalina
 - Version 10.15.7

**Erlang:**
- Installer asdf
- Version 22.0.7

**Elixir:**
- Installer asdf
- Version 1.10.3-otp-22

**Editor:**
- IntelliJ IDEA 2020.2.4 (Ultimate Edition)

**Plugin:**
- Version 11.9.2-pre+20210119174940

**Comment by KronicDeth** [comment]
The new videos outside of zips on GitHub is a very useful feature :trollface:

**Comment by KronicDeth** [comment]
Pretty sure this is the same root cause as #1888.

**Comment by KronicDeth** [comment]
@odk211 try 
[intellij-elixir-11.9.2-pre+20210122060523.zip](https://github.com/KronicDeth/intellij-elixir/files/5853907/intellij-elixir-11.9.2-pre%2B20210122060523.zip).  It contains the fixes from https://github.com/KronicDeth/intellij-elixir/pull/1890.  I'll be running it myself tomorrow to see if anything else breaks.

**Comment by odk211** [comment]
@KronicDeth Thanks! I checked, but not fixed in my environment... no error occurred.

**Comment by KronicDeth** [comment]
😿

**Comment by KronicDeth** [comment]
Atom highlighting also stops working for me after awhile with intellij-elixir-11.9.2-pre+20210122060523.zip.

**Comment by KronicDeth** [comment]
The Atom highlighting is triggering an `IndexOutOfBoundsException` when typing.  I have no idea why we can't always see these exceptions and I need to run the debugger to catch them 🤷‍♂️

**Comment by KronicDeth** [comment]
@odk211, @mpinkston, @angelikatyborska try 
[intellij-elixir-11.9.2-pre+20210123050947.zip](https://github.com/KronicDeth/intellij-elixir/files/5859722/intellij-elixir-11.9.2-pre%2B20210123050947.zip).  It fixed the highlighting stoppage for me.

**Comment by odk211** [comment]
I tried and it fixed also for me! Thank you! 😄
