### ISSUE TITLE
:erlang.nif_error(:not_loaded)

### ISSUE THREAD

**Issue by julzheng** [KronicDeth/intellij-elixir#1916]
**Describe the bug**
Debugger not working as expected, has something to do with NIF

**To Reproduce**
1. Go to 'any line after calling third party library argon2 elixir'
2. Click on 'breakpoint'
3. Click debug

**Expected behavior**
Debugger break at breakpoint

**Logs**
```
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: :not_loaded
        :erlang.nif_error(:not_loaded)
        (argon2_elixir 2.4.0) Elixir.Argon2.Base.erl:63: Argon2.Base.encodedlen_nif/6
        (argon2_elixir 2.4.0) Elixir.Argon2.Base.erl:108: Argon2.Base.hash_password/3
```

**Desktop:**
 - OS: [Ubuntu]
 - Version [20.04.2]

**Erlang:**
- Version [23]

**Elixir:**
- Version [e.g. 1.11.2]

**Plugin:**
- Version [11.10]

Debugger cannot load NIF? How do I exclude it?

**Comment by KronicDeth** [comment]
You need to add (most) NIF libraries to the module exclusion list for the debugger.  NIF libraries are supposed to handle the `:int` module, but most libraries are built to do it, so you need to help `:int`, but just not passing those libraries in.

You can [exclude modules](https://github.com/KronicDeth/intellij-elixir#excluding-modules) from being interpreted by `:int` in your application settings, but also on a per Run Configuration level on the "Interpreted Modules" tab.  

![Screen Shot 2021-03-23 at 11 16 48 PM](https://user-images.githubusercontent.com/298259/112254098-fc586300-8c2d-11eb-9a08-5effebd32735.png)
![Screen Shot 2021-03-23 at 11 16 54 PM](https://user-images.githubusercontent.com/298259/112254101-fc586300-8c2d-11eb-9208-5f51d23259de.png)


For `argon2`, I'd recommend do it Application-wide as explained in the linked section of the README.
