### ISSUE TITLE
Beam Chunks Tab Labels Not Rendering

### ISSUE THREAD

**Issue by robinhilliard** [KronicDeth/intellij-elixir#1918]
**Describe the bug**
Selecting a beam file and the BEAM Chunks tab at the bottom of the editor pane, the tab bar for the chunks is rendered (you can see the hover highlights) and clicking causes the relevant chunk data to populate the editor, but the labels on the tabs are missing. Tried various themes with restarts in between but they did not appear

**To Reproduce**
1. Select a beam file
2. Click on BEAM Chunks
3. The tab labels at the top of the editor are blank

**Expected behavior**
The tabs should be labeled with the Chunk names, eg expT, Code, ...
<img width="1479" alt="Screen Shot 2021-02-25 at 5 07 36 pm" src="https://user-images.githubusercontent.com/788490/109110854-018bd480-778c-11eb-8201-74cac8eee557.png">

**Screenshots**
Attached

**Logs**
N/A

**Desktop:**
 - OS: macOS
 - Version 10.15.7

**Erlang:**
- Installer homebrew
- Version 23

**Elixir:**
- Installer homebrew
- Version 1.10.4

**Plugin:**
- Version 11.10.0

**Additional context**
None

**Comment by KronicDeth** [comment]
I have filed [this issue with JetBrains](https://youtrack.jetbrains.com/issue/IDEA-272890) since it is likely a change in the API that I missed and need them to advise how to change how I'm using `JBTabbedPane`.
