### ISSUE TITLE
Go to declaration not working

### ISSUE THREAD

**Issue by bengro** [KronicDeth/intellij-elixir#1922]
**Describe the bug**
When selecting / navigating to declaration on any module (cmd+b, right-click Go To > Declaration), nothing happens.

**To Reproduce**
1. Install fresh phoenix project `mix phx.new`
1. "File > Open" project in intellj
2. Right-click on a module in for example `endpoint.ex`. Select "Go to > Declaration"

**Expected behavior**
It takes me to the declaration/definition of the module I just clicked on.

**Screenshots**
Clicking on a module (cmd+click, same as cmd+b), https://recordit.co/EFGpIe3M8C

**Logs**

**Desktop:**
 - OS: macOS
 - Version 11.2.3

**Erlang:**
- Installer: homebrew
- Version: Erlang/OTP 23

**Elixir:**
- Installer: homebrew
- Version: 1.11.3

**Plugin:**
- Version: 11.10.0

**Additional context**
Potentially related to https://github.com/KronicDeth/intellij-elixir/issues/1799

Apart from this little glitch, amazing plugin! Thanks for maintaining it.

**Comment by 1v0dev** [comment]
Same for me, go to does not work. The same code links correctly when opened in visual studio code.

**Comment by rs-ehyde** [comment]
same here. Find Usages (⌥F7) locates what I'm looking for correctly, but it is a bit clunky to not be able to click through.

**Comment by KronicDeth** [comment]
Fixed in 11.11.0
