### ISSUE TITLE
Does this work on Community Edition?

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#193]
I read through the readme and tried to find out if this works with the community edition of IntelliJ IDEA. I couldn't find the answer, so I'm reluctant to try it out.

The readme should say whether it works on community edition or not.

**Comment by KronicDeth** [comment]
Yes, it works on community edition.  I actually develop it on community
edition most of the time.  I'll add it to the README.

Someone at ElixirConf didn't realize that the plugin and Community Edition
are free, so it's a point worth emphasizing.
