### ISSUE TITLE
SDK Paths on Nix / NixOS

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#194]
Nix is a package manager for declarative package management.

The location for Elixir SDKs  with Nix or NixOS is `/nix/store/<hash>-elixir-<version>/`. For example, for Elixir v1.1.1, the store location is `/nix/store/408lfdw0l4fzds3mkzp57gwfpgpq0w5h-elixir-1.1.1/`.

**Comment by Havvy** [comment]
This should be reopened as the fix doesn't address NixOS, just Nix on Mac.

**Comment by KronicDeth** [comment]
Let's just open a new one for NixOS specifically.  I could test the Nix on Mac PR, I can't test NixOS without setting up a Linux VM.
