### ISSUE TITLE
TeamCityExUnitFormatting does not know how to process event with elixir 1.12

### ISSUE THREAD

**Issue by reliablendn** [KronicDeth/intellij-elixir#1949]
**Versions**
Plugin Version: 11.10.0
Elixir Version: 1.12.0

**Issue**
After updating the elixir version, plugin started throwing following error when running tests from IntelliJ:

`warning: TeamCityExUnitFormatting does not know how to process event ({:suite_finished, %{async: 89790, load: nil, run: 89790}}).  Please report this message to https://github.com/KronicDeth/intellij-elixir/issues/new.`
`/private/var/folders/3x/krcl2lxn4rs4gxfj2w140z7m0000gn/T/intellij_elixir6/exunit/1.6.0/team_city_ex_unit_formatting.ex:210: TeamCityExUnitFormatting.put_event/2`
`/private/var/folders/3x/krcl2lxn4rs4gxfj2w140z7m0000gn/T/intellij_elixir6/exunit/1.6.0/team_city_ex_unit_formatter.ex:11: TeamCityExUnitFormatter.handle_cast/2`
  `(stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4`
  `(stdlib 3.15) gen_server.erl:771: :gen_server.handle_msg/6`
  `(stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3`

**Comment by peake100** [comment]
Running into the same issue here.
