### ISSUE TITLE
combined query macros and keyword lists gives error (false positive)

### ISSUE THREAD

**Issue by olivermt** [KronicDeth/intellij-elixir#195]
`Repo.one((from r in Role, where: r.name == "admin", select: r.id), log: false)`

"Keywords appear before the end of the list. Move keywords after positional arguments."

**Comment by KronicDeth** [comment]
It probably has nothing to do with it being a macro: the parser doesn't different between macros and function calls.  At the syntactic level, macros and functions are identical.  It only differentiates between whether the function calls has parentheses or not or whether it has a do block or not. (Only macros can have do blocks, but that doesn't apply here.)

This is a bug in [this anonymous class](https://github.com/KronicDeth/intellij-elixir/blob/08c55f18def5aaba601a395d7ae0ebf44f7b427c/src/org/elixir_lang/inspection/KeywordsNotAtEnd.java#L46-L97).
