### ISSUE TITLE
Comments starting in strings when using `#{...}`

### ISSUE THREAD

**Issue by h4cc** [KronicDeth/intellij-elixir#2]
There is a bug about highlighting comments:

```
# This comment will to displayed correctly
IO.puts "All your #{inspect tuple} are belong to us"
```

The last part of the second line `#{inspect tuple} are belong to us"` will be displayed as a comment.

I dont know the name for the `#{...}` syntax in strings, but it needs to be handled.

(I know its a early version, but i would like to document my findings.)

**Comment by KronicDeth** [comment]
@h4cc, #122 finally got to parsing your example correctly.  It'll be in the next release (v0.3.3 or v0.4.0).

**Comment by h4cc** [comment]
:+1: Thanks!
