### ISSUE TITLE
Plugin in not compatible with latest Intellij Version 

### ISSUE THREAD

**Issue by dbuos** [KronicDeth/intellij-elixir#2033]
**Describe the bug**
Plugin 'Elixir' (version '11.12.0') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92

**To Reproduce**
1. Update Intellij Ultimate to 2021.2
2. Open the IDE
3. See the error message

**Expected behavior**
The plugin should be compatible..

**Screenshots**
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/68216/127575310-5221a809-a21c-4dab-a529-577fb4a91134.png">

**Logs**
5:34 PM	Plugin error
				Plugin 'Elixir' (version '11.12.0') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92

**Desktop:**
 - OS: macOS 11.4

**Erlang:**
Erlang/OTP 24

**Elixir:**
Elixir (1.12.2)

**Plugin:**
- Version [11.12.0]

**Comment by theqp** [comment]
Hi
I could [build](https://a.uguu.se/AqyiZfs.zip) the latest version for 2021.2 with a little hacking. If you don't trust my build you can check the source [here](https://github.com/KronicDeth/intellij-elixir/pull/2035) and build it yourself with this command:
`gradle build -x test`

**Comment by theqp** [comment]
@KronicDeth This can be closed because fixed in https://github.com/KronicDeth/intellij-elixir/releases/tag/v11.13.0
