### ISSUE TITLE
Pressing return inside a comment can crash Java

### ISSUE THREAD

**Issue by Theemuts** [KronicDeth/intellij-elixir#208]
I was editing one of my comments in an elixir source file, and if I pressed return to split the lines Java started to use 103% of my CPU. The error didn't occur if I only edited the text in the comment, or pressed return on the line of code after the comment.

**Comment by Theemuts** [comment]
IDEA was unresponsive for half a minute when I tried to break the comment

    # Only activated users can have contacts, if not activated a user has requested one of their own ci's

at ci's. Removing the apostrophe solves that slowdown. The slowdown becomes noticeable again when I try to break the line at has. If I try to break it at at a, IDEA is unresponsive for about 20 seconds.

**Comment by KronicDeth** [comment]
It must have something do with the rest of the file.  I can't reproduce the bug locally when hitting enter immediately before "ci's".

**Comment by mathiasose** [comment]
I'm also noticing this issue.
On https://github.com/mathiasose/advent2015/blob/master/advent/A01.exs for example, I got a freeze when trying to replace the space after the comma on line 10 with a linebreak.

**Comment by KronicDeth** [comment]
Thanks for the full example @mathiasose

**Comment by KronicDeth** [comment]
Pausing the debugger after hitting enter on line 9, shows the parser running during the freeze.  Maybe it's the automatic errors recovery that's built into JetBrains API trying to make `given the same instructions, find the position of the first character that causes him to enter the basement (floor -1).` parse.  I'm going to attempt to shrink the test case to see if that makes the recovery sooner.  If it really the error recovery, I'll have to post to the OpenAPI forum and hope someone from JetBrains can explain how to make it faster.
