### ISSUE TITLE
renaming functions also renames def keyword

### ISSUE THREAD

**Issue by eagle-te** [KronicDeth/intellij-elixir#2094]
**Describe the bug**
Using the renaming functionality (Shift + F6), renames the function, but the def/defp keyword also.

**To Reproduce**
1. write a function
2. Click on the functions name
3. Press Shift+F6, rename the function and click on refactor
4. See changed function name and keyword

**Expected behavior**
Renaming the function, but not the keyword

**Screenshots**
![rename-issue](https://user-images.githubusercontent.com/13052115/133977028-cb8abba7-71ae-4750-a8bf-82af7f18a161.png)

**Desktop:**
 - OS: Linux
 - Version 5.13.15-1-MANJARO

**Erlang:**
- Installer asdf
- Version 23.3.4.4

**Elixir:**
- Installer asdf
- Version 1.11.4-otp-23

**Plugin:**
- Version 11.13.0

**Additional context**
Same Problem occurred on my colleague's System.

**Comment by KronicDeth** [comment]
I can reproduce.  This is a regression OR a change to the JetBrains API since this renaming code is years old.

**Comment by drl123** [comment]
Just ran across this myself on MacOS w/ plugin version 12.2.0 and RM 2021.3.1
