### ISSUE TITLE
Update tests to Elixir 1.1.1

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#210]
The test setup is still on Elixir 1.0.5 on OSX and 1.0.2 on travis-ci, but in homebrew I have Elixir 1.1.1 installed, so I see test failures for Elixir 1.1 changes that don't show up on travis-ci.  All the test environments should be update toe Elixir 1.1.1.

- [x] Remove `^^^` as a separate precedence level to match [elixir-lang/elixir@d235533b45ce4d8fb8ba1c1c35cd9377e49929f1](https://github.com/elixir-lang/elixir/commit/d235533b45ce4d8fb8ba1c1c35cd9377e49929f1#diff-dbe798b7d4bb8070f478211481ccf34a)
- [ ] The `\<terminator>` should be quoted as just `<terminator>` for a line sigil while all other potential escapes should quote as 2 characters `\` and `<non-matching-terminator>`.

**Comment by zyuyou** [comment]
I noticed that `intellij-erlang` had change their build-tool to the `gradle`, do you plan to use `gradle` in `intellij-elixir` too?

**Comment by KronicDeth** [comment]
I'm using Ant because IntelliJ had an option in the menu to generate the Ant files from the project configuration automatically and after that it was pretty simple XML to understand to extend.  I couldn't use maven because it relies so strongly on the dependencies being available in an online repositories somewhere.  I never looked into gradle.

**Comment by zyuyou** [comment]
OK, keep it simple is right!

**Comment by Havvy** [comment]
This issue should probably be closed.

**Comment by KronicDeth** [comment]
Tests are still failing, but only on Travis-CI (https://travis-ci.org/KronicDeth/intellij-elixir/builds/94087022).  I might have to convert the build over to CircleCI just so I can SSH into the CI server to determine what's different and if that difference is a Linux (CI) vs OSX (local) problem.

**Comment by KronicDeth** [comment]
I can reproduce the failures locally on OSX when running the ant build instead of the "org.elixir_lang" JUnit Run Configuration in IntelliJ, so there's been some drift between the ant build and the Run configuration + local environment setup.
