### ISSUE TITLE
New Elixir Module Kind: ExUnit Test

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#212]
1. Has a default passing test inside of it.
2. Makes sure the file ends with "_test.exs"

That's about it.

**Comment by KronicDeth** [comment]
@Havvy, can you explain the full use case?  I'm just wondering if what you actually want is the Go To Test functionality that Rubymine has for specs and if your actual use case is if Go To Test doesn't work, it prompts to create a test file for the current module?  I can do the template form first, but I want to know if I should be able to infer the test module name from the module under test as a follow on feature.

**Comment by DylanGriffith** [comment]
I'm not sure i understand the conversation on here but I also have a desire for the feature "New Elixir Module Kind: ExUnit Test"

Basically the problem I see it is that if I try to use the "New -> Elixir File" functionality right now I end up with a file that has a `.ex` extension and then I need to manually rename to `.exs`.

So ideally this functionality would simply be a new menu option in the file explorer thing where I say "New -> Elixir Test" and it will use the `.exs` extension. As a bonus the template could be the same as the test example `mix new` generates which has the `use ExUnit.Case` in it.

Of course the thing you are describing about "Go To Test" sounds useful but that wasn't how I understood this github issue and I have a need for what I think @Havvy is asking for.

**Comment by Havvy** [comment]
Basically what Dylan Griffith says.

The "Go To Test" thing sounds orthogonal, and potentially useful (to others). I just want a template for tests that ExUnit can be ran with without having to create a file and then rename. And I'm guessing so do others.
