### ISSUE TITLE
Allow environment variables to be set for Mix Run Configuration

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#216]
`mix test` and other mix task need to be able to have environment variables to set.  The Run Configurations for Rubymine and IntelliJ have this, so there might be a reusable UI component to add this.

**Comment by merqlove** [comment]
From #427 

Wow, i see it now. So 1 position already done.
ENV vars is extended feature & maybe not needed in dev/test env.

Also 2.2 too can be difficult now...
Maybe here something useful? I'm using it all the time:
https://github.com/JetBrains/intellij-scala/tree/idea163.x/src/org/jetbrains/plugins/scala

They have:
![screenshot 2016-09-12 05 23 15](https://cloud.githubusercontent.com/assets/18354/18422954/915a8db0-78b1-11e6-9c7a-ee555d370136.png)

**Comment by KronicDeth** [comment]
`"Environment variables"` -> `environment.variables.component.title` -> `EnvironmentVariablesComponent`
