### ISSUE TITLE
Add support for `x.{y, z, w}` expression

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#217]
Port https://github.com/elixir-lang/elixir/commit/a5a29dc47b6f486853eb92adee1281d26df14ccc

**Comment by smeevil** [comment]
When this error occurs it affects the syntax highlighting as well. For everything below this line it seems that the variables, ignored variables, and parameters are loosing their colouration. If commenting the alias or writing the alias in full, the highlighting is restored. (version 3.0.1.20160520213720)

**Comment by KronicDeth** [comment]
It makes sense that it would screw up the everything below since the parsing level will generate `PsiErrorElement`s, which stops the higher levels, like the syntax highlighting that is done by the annotators as opposed to the `ASTNode` level syntax highlighting

**Comment by merqlove** [comment]
@KronicDeth Hi, this is fixed?
I can't work with 4.0.0, highlighting/autocomplete is failed in 50% of project files within intellij/rubymine + elixir plugin.

**Comment by KronicDeth** [comment]
@merqlove if it was fixed this issue would have been closed with a pull request (or manually if I forgot to do `Fixes #217` in the PR description).  It's not closed, so it's not fixed.

**Comment by KronicDeth** [comment]
@merqlove do you have any open-source projects I can use to test the fix before releasing for your specific use cases.  My test cases are normally elixir-lang/elixir, but it hasn't converted to compact aliases really, so it won't make a good test case.

**Comment by merqlove** [comment]
@KronicDeth yeah, uploaded some my current docker testing project.
https://github.com/merqlove/elixir-docker-compose
Link to file with bug in readme.

**Comment by merqlove** [comment]
Also just extracted from this app PubSub wrapper.
https://github.com/merqlove/redix_pubsub_fastlane.
Root file has such aliases.
