### ISSUE TITLE
Warning after running ExUnit test

### ISSUE THREAD

**Issue by dmcollie** [KronicDeth/intellij-elixir#2182]
warning: TeamCityExUnitFormatting does not know how to process event ({:suite_finished, %{async: nil, load: nil, run: 41413}}).  Please report this message to https://github.com/KronicDeth/intellij-elixir/issues/new.
  /private/var/folders/my/j2z1h39s0mg2sg8hkyjlnh9w0000gp/T/intellij_elixir/exunit/1.6.0/team_city_ex_unit_formatting.ex:210: TeamCityExUnitFormatting.put_event/2
  /private/var/folders/my/j2z1h39s0mg2sg8hkyjlnh9w0000gp/T/intellij_elixir/exunit/1.6.0/team_city_ex_unit_formatter.ex:11: TeamCityExUnitFormatter.handle_cast/2
  (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
  (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
  (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by KronicDeth** [comment]
Fixed by #2074
