### ISSUE TITLE
TeamCityExUnitFormatting does not know how to process event ({:suite_finished, %{async: nil, load: nil, run: 77636}}).

### ISSUE THREAD

**Issue by sinobra** [KronicDeth/intellij-elixir#2183]
I am now running with Elixir 1.12.3 and I get the following error message when running ExUnit tests in the IDE...

warning: TeamCityExUnitFormatting does not know how to process event ({:suite_finished, %{async: nil, load: nil, run: 77636}}).  Please report this message to https://github.com/KronicDeth/intellij-elixir/issues/new.
  /tmp/intellij_elixir430/exunit/1.6.0/team_city_ex_unit_formatting.ex:210: TeamCityExUnitFormatting.put_event/2
  /tmp/intellij_elixir430/exunit/1.6.0/team_city_ex_unit_formatter.ex:11: TeamCityExUnitFormatter.handle_cast/2
  (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
  (stdlib 3.13) gen_server.erl:756: :gen_server.handle_msg/6
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

**Comment by KronicDeth** [comment]
Fixed by #2074
