### ISSUE TITLE
Build tool works but cannot format the output of 'mix test'

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2190]
Hit this error when trying to run the build through the Intellij build tool

`
Testing started at 15:15 ...
Compiling 3 files (.ex)
Suite started with seed 781418
warning: TeamCityExUnitFormatting does not know how to process event ({:suite_finished, %{async: 3466705, load: nil, run: 3466706}}).  Please report this message to https://github.com/KronicDeth/intellij-elixir/issues/new.
  /private/var/folders/b0/6t9wgds532zb8ndzjqlg205r0000gn/T/intellij_elixir/exunit/1.6.0/team_city_ex_unit_formatting.ex:210: TeamCityExUnitFormatting.put_event/2
  /private/var/folders/b0/6t9wgds532zb8ndzjqlg205r0000gn/T/intellij_elixir/exunit/1.6.0/team_city_ex_unit_formatter.ex:11: TeamCityExUnitFormatter.handle_cast/2
  (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
  (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
  (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3`

**Comment by KronicDeth** [comment]
Fixed by #2074
