### ISSUE TITLE
Syntax highlighting is broken by Elixir's stepped ranges

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2200]
**Describe the bug**
Elixir introduce stepped ranges in v1.12 https://hexdocs.pm/elixir/1.12/Kernel.html#..///3 .
But syntax highlighting is broken in intellij-elixir.

**To Reproduce**

```elixir
defmodule Work do
  def work do
    1..1//1 |> Enum.to_list()
  end
end
```

**Screenshots**
<img width="735" alt="スクリーンショット 2021-11-18 15 58 28" src="https://user-images.githubusercontent.com/1321120/142368381-8c242425-05a2-417c-a27a-fd3857f325cf.png">

**Logs**

**Desktop:**
 - OS: macOS Big Sur
 - Version 11.15.2

**Erlang:**
- Installer asdf
- Version 24.0.3

**Elixir:**
- Installer asdf
- Version 1.12.2-otp-24

**Editor:**
- IntelliJ IDEA 2021.2 (Ultimate Edition)

**Plugin:**
- Version 11.13.0

**Additional context**

**Comment by KronicDeth** [comment]
Missing this stuff is what I get for working on clients on older versions of Elixir ☹️ .  Thanks for the small reproduction case.

**Comment by KronicDeth** [comment]
Stepped ranges were added to Elixir in https://github.com/elixir-lang/elixir/pull/10810
