### ISSUE TITLE
ExUnit assert can bind variables, but intellj-elixir can not find it.

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2203]
**Describe the bug**
ExUnit assert can bind variables, but intellj-elixir can not find it.

**To Reproduce**

1. Write like below
```elixir
defmodule FooTest do
  use ExUnit.Case, async: true

  test "foo" do
    assert {:ok, datetime, _} = DateTime.from_iso8601("2015-01-23T23:50:07Z")
    assert %DateTime{} = datetime # Cmd + click at `datetime` do not work.
  end
end
```
2. Cmd + click at `datetime` do not work.

When I remove `assert`, It can go to declaration.

<img width="671" alt="スクリーンショット 2021-11-19 13 19 57" src="https://user-images.githubusercontent.com/1321120/142565205-71ca3c3e-ca05-4766-b443-613d58cb13fb.png">

Thank you for your current hard work!
I'm looking forward to the next release! ❤️

**Comment by KronicDeth** [comment]
This is fixed on `main`.  It was included in #2179 in https://github.com/KronicDeth/intellij-elixir/pull/2179/commits/ae2f5ddcd860c1ddb368800b8ddef64305a3829e.  It will be released in `12.0.0`.
