### ISSUE TITLE
Intellij IDEA can not find Mix version

### ISSUE THREAD

**Issue by dolphineor** [KronicDeth/intellij-elixir#224]
@KronicDeth Hi, I want to use elixir in IDEA, but I run into some trouble, 
![elixir](https://cloud.githubusercontent.com/assets/9883493/12005419/9bb42414-abdf-11e5-95ec-dd48c2aca661.png)

the version of IDEA is 15.0.2, I've installed Elixir successfully, it always shows N/A. Is there something wrong with me? Thanks in advance.

**Comment by zyuyou** [comment]
will be fixed by #220 ! thank you

**Comment by dolphineor** [comment]
I'm looking forward to it. Thanks.
