### ISSUE TITLE
Stacktrace linker is going to wrong file

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#229]
If there are multiple files with the same basename (e.g. `lib/api/relationship.ex` and `deps/ja_serializer/lib/ja_serializer/formatter/relationship.ex`), then the wrong file can be linked sometimes.

**Comment by PatinoBrian** [comment]
I'm having the same issue with a php project. Intellij opens up `conf.php` in a completely different folder even though `require_one('conf.php')` is directed towards the file in the same folder from where it's being called.

**Comment by KronicDeth** [comment]
It looks like the bug must be in [FileReferenceFilter](https://github.com/KronicDeth/intellij-elixir/blob/832dd7bcb9a788af71663428c4eea4c2e32b085e/src/org/elixir_lang/console/FileReferenceFilter.java) because it is used by [ElixirConsoleUtil#attachFilters](https://github.com/KronicDeth/intellij-elixir/blob/832dd7bcb9a788af71663428c4eea4c2e32b085e/src/org/elixir_lang/console/ElixirConsoleUtil.java#L17-L19), which is called by [MixRunningState#execute](https://github.com/KronicDeth/intellij-elixir/blob/832dd7bcb9a788af71663428c4eea4c2e32b085e/src/org/elixir_lang/mix/runner/MixRunningState.java#L29-L42).

**Comment by KronicDeth** [comment]
Looks like one bug is that the line parser is leaving a space in front of the path, so the first check to find the file always fails:
![screen shot 2016-07-17 at 8 42 02 am](https://cloud.githubusercontent.com/assets/298259/16900956/6ceac122-4bfa-11e6-9d68-b2c59bdc4a9c.png)
