### ISSUE TITLE
Latest RubyMine won't accept latest plugin version

### ISSUE THREAD

**Issue by drl123** [KronicDeth/intellij-elixir#2330]
**Describe the bug**
Rubymine updated this week to 2021.2, Build#RM-213.5744.254.  In doing so, it downgraded my plugin version to 11.10.0.  I tried to install the latest version of the plugin from zip file and got this message saying it needed build 212* or higher...last I checked 213 is higher than 212 ;-). 

Any suggestions?

![image](https://user-images.githubusercontent.com/568926/144717905-89db520b-9fd4-4ffe-a67b-10180d087e0e.png)

**To Reproduce**
1. Go to 'plugins'
2. Click on 'install from zip'
3. Select intellij-elixir-11.13.0.zip
4. See error above

**Expected behavior**
Would have expected the latest version of the plugin to be available in the marketplace or at least install

**Desktop:**
 - OS: macOS
 - Version 10.14.6

**Erlang:**
- Installer asdf
- Version 24.1.7

**Elixir:**
- Installer asdf
- Version 1.13.0-otp-24

**Plugin:**
- Version 11.10 -> 11.13.0

**Comment by KronicDeth** [comment]
Thank you @drl123 for noticing this!  I had to mark 64 issues as duplicate as other people were blindly installing an older version of the plugin on a newer IDE version.

I have closed all open compatibility ranges in the Market Place by setting the upper bound to build `211.*`, you should no longer be able to install any existing, incompatible versions of the Elixir plugin in 2021.3.

Downgrade your IDE from 2021.3 to 2021.2.3 and wait for the 12.0.0 release that will support 2021.3.

BTW, I'm releasing 12.0.0 once I go through all the unlabeled issues, so it'll be sometime today.

**Comment by drl123** [comment]
Thanks Elle.  I kind of figured that out after the fact.  Didn’t realize all of those automatic issues were due to downgraded plugin versions until later.  I did downgrade the IDE and have 11.13.0 running now.  I’ll watch for a post on the Elixir Forum for v12.

Thanks for all of your hard work on this plugin!


Don
