### ISSUE TITLE
JetBrains Plugin Repository still advertises v2.0.0-pre

### ISSUE THREAD

**Issue by weppos** [KronicDeth/intellij-elixir#234]
I read the [2.0 announcement here](https://groups.google.com/forum/#!topic/elixir-lang-talk/bMZN50zHiFw), but I noticed the IntellijIdea repo still advertises the 2.0.0-pre as the latest available release.

Are they the same release?

![screen shot 2016-01-08 at 16 28 13](https://cloud.githubusercontent.com/assets/5387/12201458/d6087f44-b624-11e5-8385-13089e42a79f.png)

**Comment by KronicDeth** [comment]
Crap, I forgot to remove [the -pre in the plugin.xml](https://github.com/KronicDeth/intellij-elixir/blob/master/src/META-INF/plugin.xml#L4).  Yeah, it is the right version, but I really should push up a fixed version.

**Comment by KronicDeth** [comment]
Removed the -pre for v2.1.0

![screen shot 2016-01-10 at 1 53 13 pm](https://cloud.githubusercontent.com/assets/298259/12223595/92423e5c-b7a1-11e5-9857-9bc6911de9fc.png)

Credited you in [the release announcement on elixir-lang-talk](https://groups.google.com/forum/#!topic/elixir-lang-talk/nAC-0UBOtp8).  Thanks.
