### ISSUE TITLE
Find Usages(⌥ F7) not working.

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2374]
**Describe the bug**
Find Usages(⌥ F7) not working in Plugin Version: 12.0.1 and IDEA 2021.3.
I rollbacked IDEA version to 2021.2.3 and It worked.

**To Reproduce**
1. Write
```elixir
defmodule Foo do
  def foo, do: "foo"
  def bar, do: foo()
  def baz, do: foo()
end
```
2. Move Cursor to `foo()` 
3. Do Find Usages(⌥ F7).
4. Find window is not activated.

**Logs**
No pop up events.

**System**

Plugin Version: 12.0.1
Application: IntelliJ IDEA Ultimate Edition (2021.3)
Operating System: Mac OS X (11.6.1)

**Comment by KronicDeth** [comment]
I swear JetBrains breaks the Find Usage API in every version of the IDEs now.  They probably messed with the `TargetElementEvaluator` API usage again.

**Comment by KronicDeth** [comment]
```java
  public void findUsages(@NotNull PsiElement psiElement, @Nullable PsiFile scopeFile, FileEditor editor, boolean showDialog, @Nullable("null means default (stored in options)") SearchScope searchScope) {
    ApplicationManager.getApplication().assertIsDispatchThread();
    FindUsagesHandler handler = getFindUsagesHandler(psiElement, showDialog ? OperationMode.DEFAULT : OperationMode.USAGES_WITH_DEFAULT_OPTIONS);
    if (handler == null) return;
```
https://github.com/JetBrains/intellij-community/blob/bb6036b52b52e67272543349ff2bb9b939275ee6/platform/lang-impl/src/com/intellij/find/findUsages/FindUsagesManager.java#L193-L194

It can't find the `FindUsagesHandler` and so returns before trying to find anything.

**Comment by KronicDeth** [comment]
That code was last change 2 years ago, so it's something deeper messing it up now.

**Comment by KronicDeth** [comment]
It annoys me to no end that Find Usages is broken, but the related highlighting of usages is not as `foo` is highlighted correctly when any of the `foo`s have the cursor on them.

![Screen Shot 2021-12-08 at 10 41 07 PM](https://user-images.githubusercontent.com/298259/145335748-ff55c257-a82b-4325-a65f-7b6ac29979cc.png)

**Comment by KronicDeth** [comment]
I think it is related to the new `SearchTargetVariantsDataRule` as that supplies the default value for the targets, which is giving the wrong element.

**Comment by odk211** [comment]
@KronicDeth  Thank you for great work! ❤️  I installed plugin v12.1.0 and check this issue's how to reproduce. but it shows like `No Usage found`.
I checked this combination.
- IDEA 2021.2.3, plugin v12.1.0 -> `No Usage found`
- IDEA 2021.3.1, plugin v12.1.0 -> `No Usage found`
- IDEA 2021.2.3, plugin v12.0.1 -> 3 usage found
<img width="406" alt="スクリーンショット 2022-01-08 8 35 53" src="https://user-images.githubusercontent.com/1321120/148620440-0595d6b9-db2d-44c9-aa47-d6a3b2df3f72.png">

**Comment by KronicDeth** [comment]
@odk211 In a scratch file for me, it works for both Find Usages and Show Usages. I'm running IDEA 2021.3 and that's what the plugin is tested against.

![Screen Shot 2022-01-07 at 8 26 22 PM](https://user-images.githubusercontent.com/298259/148628445-588dc5f5-d399-48d9-b9ba-2b45a0ce6dd3.png)
![Screen Shot 2022-01-07 at 8 27 40 PM](https://user-images.githubusercontent.com/298259/148628447-812394f9-59bd-48ca-af94-cd4d5b136818.png)
![Screen Shot 2022-01-07 at 8 27 51 PM](https://user-images.githubusercontent.com/298259/148628448-f23bf8cb-3118-4a9d-bac9-de55e896cdce.png)
![Screen Shot 2022-01-07 at 8 28 08 PM](https://user-images.githubusercontent.com/298259/148628450-a2e4a123-6ed3-415f-823a-72d73b8ee954.png)
![Screen Shot 2022-01-07 at 8 31 29 PM](https://user-images.githubusercontent.com/298259/148628451-4413d9b5-11e8-47a5-9867-9a7263f5bf58.png)
![Screen Shot 2022-01-07 at 8 32 14 PM](https://user-images.githubusercontent.com/298259/148628452-761690fb-fe75-4704-802a-9195737b16a8.png)
![Screen Shot 2022-01-07 at 8 32 32 PM](https://user-images.githubusercontent.com/298259/148628453-7985310d-f5b4-419e-8c61-b80ce6baf4eb.png)

If this is so IDE version dependent it's going to be really annoying to work-around.

**Comment by KronicDeth** [comment]
I have confirmed the difference between 2021.3 and 2021.3.1 in the tests too.  The tests fail when I change build to use 2021.3.1

![Screen Shot 2022-01-07 at 9 55 56 PM](https://user-images.githubusercontent.com/298259/148630652-5daddb7c-3f49-4044-89a7-6b3936f264c1.png)
![Screen Shot 2022-01-07 at 9 56 09 PM](https://user-images.githubusercontent.com/298259/148630653-d9847b17-4f55-4779-aac3-b72033b3d467.png)

**Comment by odk211** [comment]
Oh...  But thank you for quick looking and investigating!
