### ISSUE TITLE
select SDK

### ISSUE THREAD

**Issue by cjuexuan** [KronicDeth/intellij-elixir#238]
I install elixir with apt-get on ubuntu ,but how can I select the SDK,it doesn't work

**Comment by KronicDeth** [comment]
I need a more thorough explanation of the steps you're doing in the IDE:
* Which steps are you following?
* Which step does it fail?
* Do you get an error message?

**Comment by cjuexuan** [comment]
yeah ,when I  want to create the project ,
on step 4 ,like ![step4](http://7xnz7j.com1.z0.glb.clouddn.com/elixir.png),but when I click configure and select the sdk ,I find my elixir in `/usr/lib/elixir/bin`,but when I choose it ,ide report me that 'The selected directory is not a valid home  for Elixir SDK',it doesn't work

**Comment by cjuexuan** [comment]
select like:![select](http://7xnz7j.com1.z0.glb.clouddn.com/select.png)

error like :![error](http://7xnz7j.com1.z0.glb.clouddn.com/error.png)

when I run tree ,the pic is:![tree](http://7xnz7j.com1.z0.glb.clouddn.com/tree.png)

**Comment by zyuyou** [comment]
@cjuexuan the sdk path is `/usr/lib/elixir`, not `/usr/lib/elixir/bin`.

**Comment by cjuexuan** [comment]
when I try the way like you tell,ide report `Probadly SDK  installed in /usr/lib/elixir is corrupt`,and my elixir  version is `1.1.0-dev`,idea version is `15.02`

**Comment by KronicDeth** [comment]
This could either be another difference with how `elixir --version` and `mix --version` is formatted, or you're not using the latest version of IntelliJ Elixir, which has some fixes for the `--version` parsing.  Are you on version 2.1.0 of the plugin?

**Comment by cjuexuan** [comment]
@KronicDeth  my elixir version is `1.1.0-dev` ,my plugin version is `2.1.0`,my idea version is `15.02`,mix version same as elixir

**Comment by zyuyou** [comment]
@cjuexuan review the #220 , show the result of command `elixir --version` and `mix --version`

**Comment by cjuexuan** [comment]
@zyuyou @KronicDeth  ![version](http://7xnz7j.com1.z0.glb.clouddn.com/version.png)

**Comment by zyuyou** [comment]
It seems that `1.1.0-dev` did not match the version-regexp,  use the released version, `Elixir-1.1.0` or `Elixir-1.2.0`  instead.

**Comment by cjuexuan** [comment]
@zyuyou yeah, so I will try install 1.2.0 without using apt-get later,but I think this is a bug with plugin,

**Comment by cjuexuan** [comment]
@zyuyou yeah,I will install `1.1.0` without using `apt-get` later

**Comment by zyuyou** [comment]
@cjuexuan I recommend using use [kiex](https://github.com/taylor/kiex)

**Comment by cjuexuan** [comment]
@zyuyou  thanks
