### ISSUE TITLE
Commenting shortcut doesn't work.

### ISSUE THREAD

**Issue by wanderanimrod** [KronicDeth/intellij-elixir#247]
Hello all, 

The comment shortcut "CMD+/ " on mac is not working. That is, it doesn't introduce the "#" character at the beginning of highlighted lines.

Is anyone else experiencing this? I can look into adding the feature if it is indeed just a missing feature. 

- Enjoying elixir!

**Comment by KronicDeth** [comment]
It's not released yet.

**Comment by wanderanimrod** [comment]
Cool. I'll just wait then.

**Comment by KronicDeth** [comment]
@wanderanimrod, v2.2.0 has been released with the commenter.  Update your plugin and you should be able to use it.

**Comment by wanderanimrod** [comment]
I have already updated my plugin and I am delighted! Thanks for the good
work.

On Thu, 3 Mar 2016 at 22:32 Luke Imhoff <notifications@github.com> wrote:

> @wanderanimrod <https://github.com/wanderanimrod>, v2.2.0 has been
> released with the commenter. Update your plugin and you should be able to
> use it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KronicDeth/intellij-elixir/issues/247#issuecomment-192081570>
> .
>
-- 
Wandera Nimrod,
Software Developer
ThoughtWorks Inc,
New York, NY
