### ISSUE TITLE
intellij freezes with elixir plugin

### ISSUE THREAD

**Issue by suryatejamuthyala** [KronicDeth/intellij-elixir#2484]
whole IDE freezes when trying to edit an .ex file , find attached logs
[logs.zip](https://github.com/KronicDeth/intellij-elixir/files/7918605/logs.zip)

**Comment by steveops** [comment]
I have been experiencing the same

**Comment by steveops** [comment]
[freeze logs.zip](https://github.com/KronicDeth/intellij-elixir/files/7928829/freeze.logs.zip)

**Comment by steveops** [comment]
> > I have been experiencing the same
> 
> can you follow the instructions [here](https://plugins.jetbrains.com/plugin/7522-elixir/reviews#review=62758-62759) https://plugins.jetbrains.com/plugin/7522-elixir/reviews#review=62758-62759 , that may help the developer

Thanks

**Comment by KronicDeth** [comment]
This has the same root cause as #2457.  Please move all conversation to that issue.

**Comment by KronicDeth** [comment]
Duplicate of #2457
