### ISSUE TITLE
Command portion of Elixir Mix run configuration not persisting past restart

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#249]
If I restart IntelliJ, the Elixir Mix Run configurations I made before the start still exist and have their Name filled in, but they completely lose the Command, so can't actually do the run.  The empty command shows up in the Run tool window as `""`: `/usr/local/Cellar/elixir/1.2.3/bin/elixir /usr/local/bin/mix ""`

Any ideas why the Command field isn't saving @zyuyou?

**Comment by zyuyou** [comment]
Checking [MixRunConfigurationBase's writeExternal](https://github.com/KronicDeth/intellij-elixir/blob/master/src/org/elixir_lang/mix/runner/MixRunConfigurationBase.java#L62),  it should be `XmlSerializer.serializeInto(this, element)` .

**Comment by zyuyou** [comment]
@KronicDeth My local code is too old, can you help me testing this?

**Comment by KronicDeth** [comment]
@zyuyou yes, I'll attempt the change locally to test it out.

**Comment by zyuyou** [comment]
@KronicDeth I have already tested it out, it works with `XmlSerializer.serializeInto(this, element) `.

**Comment by KronicDeth** [comment]
I guess github didn't auto-detect the fix wording in #256, closing manually.
