### ISSUE TITLE
IntelliJ Ultimate 2021.3.1 and 2021.3.2: Elixir plugin intermittently fails to activate autocomplete for standard library 

### ISSUE THREAD

**Issue by jftaulbee** [KronicDeth/intellij-elixir#2501]
**Describe the bug**
I'm having difficulty with the Elixir plugin where it will intermittently stop providing autocomplete options when using standard library objects like Enum, Map, and others. 

I have Elixir v1.13.2 installed via Homebrew, and under Project Structure I have both the Erlang and Elixir SDKs set up. Invalidating the caches and restarting IntelliJ doesn't appear to correct the issue. 

Oddly enough if autocomplete stops working in my existing project and I use IntelliJ to create a new Elixir project, autocomplete works in both the new project and the already existing project.

Apologies if my terminology is incorrect, I am new to Elixir.

edit: After looking a bit closer at my current project which is not working and the new project which is, I see Elixir as an external library under the new project and nothing under the current project. Checking under modules for both, I see Elixir in the list of module dependencies and "No SDK" under the project that does not work. Any idea how/why this happens?

**To Reproduce**
I have been unable to find a way to reproduce the issue. It appears to happen at random right now.

**Expected behavior**
When typing `Enum.` I expect a list to pop up with the various functions available to that module. When attempting to force it via Ctrl + Space, IntelliJ says "No suggestions"

**Screenshots**
https://imgur.com/a/KOChQrf

**Logs**
If reporting a hang or other performance issue, please attach the [thread dumps](https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond).

**Desktop:**
 - OS: macOS
 - Version Monterey 12.1

**Erlang:**
- Installer homebrew
- Version 24.2.1

**Elixir:**
- Installer homebrew
- Version 1.13.2

**Plugin:**
- Version 12.2.0

**Additional context**

**Comment by benkeil** [comment]
Did you may updated elixir and the paths for the SDK are no longer valid?
Did you add for each module the SDK?

**Comment by jftaulbee** [comment]
> Did you may updated elixir and the paths for the SDK are no longer valid? Did you add for each module the SDK?

Hi Ben,

I only just installed Elixir this weekend and have not updated either elixir or erlang since then. 

If by module you mean Elixir module, I only have one currently which was missing the SDK under Module > Dependencies in Project Structure. Adding it back resolved the issue though.

For now everything seems working. Will try to narrow down the steps to reproduce the issue should the dependency mysteriously go missing again.

**Comment by grndsgn** [comment]
I found that I needed to manually add the Elixir libraries (ebin folder) under the Languages and Frameworks / Libraries for autocomplete to work, project dependencies such as Plug, HttpPoison however did automatically get included.
