### ISSUE TITLE
java.lang.NullPointerException at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:184)

### ISSUE THREAD

**Issue by guysbryant** [KronicDeth/intellij-elixir#2564]
# System

Plugin Version: 12.2.0
Application: IntelliJ IDEA Ultimate Edition (2021.3.3)
Operating System: Mac OS X (11.6.4)

# Event

## Message

Unhandled exception in [StandaloneCoroutine{Cancelling}@48f4ad80, EdtCoroutineDispatcher@5047f367]

### Stacktrace

```
java.lang.NullPointerException
	at org.elixir_lang.documentation.ElixirDocumentationProvider.fetchDocs(ElixirDocumentationProvider.kt:184)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.generateDoc(ElixirDocumentationProvider.kt:27)
```

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/blob/416d3487b2956fe190a852420a76e81ac8284c0e/src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt#L184

`containingFile` can be `null` and it's not handled.
