### ISSUE TITLE
Cannot add modules in umbrella project

### ISSUE THREAD

**Issue by rafal0p** [KronicDeth/intellij-elixir#2572]
### Describe the bug
After adding umbrella apps as modules IDE is unusable, and must be killed.

### To Reproduce
1. **Create new umbrella project**
```
mix new intellij_umbrella --umbrella
cd intellij_umbrella/apps
mix new app_one
mix new app_two
```
2. **Open it in IDE**
Everything should work flawlessly, project structure highlights `lib` and `test` dirs with appropriate colors, you can right click to run tests. We can see 3 modules created by default (click `File` -> `Project Structure` it should be in `Project Settings` -> `Modules`).
3. **Remove all 3 modules.**
Reopen the IDE to make sure that they are _really_ removed.
4. **Re-add them**
Importing it from external model using Mix.

### Error description
IDE is not freezed, but most of the buttons and keyboard shortcuts are not doing anything. You can't open a file, display files list, use git, etc; but for example it is still possible to resize panes.

### Expected behavior
IDE working exactly the same way as before removing and adding modules back.

### Screenshots
One of the problems, infinitely loading files list:
![image](https://user-images.githubusercontent.com/9382427/161433928-bd30e164-af7a-4bc0-a469-946eb8f53691.png)

### Logs
I took 10 thread dumps, at different stages, you can find them [here](https://gist.github.com/rafal0p/d699340cb21b3ba9d8dc285fdc809a9a).

### Desktop:
 - confirmed on both macOS and linux mint

### Erlang:
- Installer: both `asdf` and `homebrew`
- Version: 24

### Elixir:
- Installer: both `asdf` and `homebrew`
- Version: 1.13

### Plugin:
- Version 12.2.0

**Comment by KronicDeth** [comment]
I'm not able to reproduce this on Plugin 13.0.0 and IntelliJ IDE 2022.1.1.

**Comment by rafal0p** [comment]
I was hoping that bumping the IDE and/or Plugin will help, but it didn't. 

It seems that it behaves correctly if after removing modules you immediately re-add them. Problem is present only if you hit **Apply** and/or close the IDE with no modules present.

Why it is important? Because the project structure is not always picked up correctly by default, especially with bigger, more complicated repositories.

What should be my next steps if I want to debug it further?
