### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.ElixirScriptFileType at org.elixir_lang.FrameworkDetector.getFileType(FrameworkDetector.java:29)

### ISSUE THREAD

**Issue by kildo162** [KronicDeth/intellij-elixir#2617]
# System

Plugin Version: 12.2.1
Application: IntelliJ IDEA Ultimate Edition (2021.2.2)
Operating System: Linux (5.13.0-40-generic)

# Event

### Stacktrace

```
java.lang.NoClassDefFoundError: Could not initialize class org.elixir_lang.ElixirScriptFileType
	at org.elixir_lang.FrameworkDetector.getFileType(FrameworkDetector.java:29)
```

**Comment by KronicDeth** [comment]
I'm sorry, the stacktrace is too short for this to be reproducible.  If it still happens to you with the latest version of the plugin AND it happens reliably, then we can look into pairing where I show you how to setup a development environment to attach the debugger on error.  I'm closing the issue for now, but please leave a comment if it is reproducible for you and you want to pair.
