### ISSUE TITLE
Error running 'phx.server': Elixir SDK `1.13.4` is missing Erlang SDK

### ISSUE THREAD

**Issue by GiorgioG** [KronicDeth/intellij-elixir#2625]
Plugin Version: 12.3.0-pre+20220418164904
Application: IntelliJ IDEA Ultimate Edition (2022.1)
Operating System: Mac OS X (12.3.1)

Attempting to run a 'mix phx.server' run configuration yields this error:
Error running 'phx.server': Elixir SDK `1.13.4` is missing Erlang SDK

![image](https://user-images.githubusercontent.com/968113/166108590-c51fae8e-4db2-4129-827d-00915d4b4a56.png)

**Comment by KronicDeth** [comment]
You need to configure the version of Erlang SDK that backs the Elixir SDK.  It’s a drop down in the Elixir SDK configuration.  See [here in the README.md](https://github.com/KronicDeth/intellij-elixir#rich-ides)

**Comment by KronicDeth** [comment]
1. FIle > Project Structure
   ![Screen Shot 2022-04-30 at 7 56 50 PM](https://user-images.githubusercontent.com/298259/166127655-4331d612-4b41-43f6-afc2-2c939f6c7e7e.png)
2. Select SDKs  
   ![Screen Shot 2022-04-30 at 7 57 05 PM](https://user-images.githubusercontent.com/298259/166127656-f7c1d8b3-39c2-40d0-a19e-7f7e981b5e02.png)
3. Click the + Add New SDK
   ![Screen Shot 2022-04-30 at 7 57 12 PM](https://user-images.githubusercontent.com/298259/166127657-4fdf4417-51f4-41c9-ab18-66c61c235468.png)
4. Select Add Erlang for Elixir SDK as the SDK type
   ![Screen Shot 2022-04-30 at 7 57 27 PM](https://user-images.githubusercontent.com/298259/166127658-0e93a32f-e295-4f9a-a105-d9cdb3e4ebcb.png)
5. The plugin will auto-select the newest Erlang SDK of the package managers it knows to check for. If it doesn't find the one you want, change the directory manually.
  ![Screen Shot 2022-04-30 at 7 57 42 PM](https://user-images.githubusercontent.com/298259/166127660-efbea75c-1d6d-441e-b155-011d65011ad2.png)
6. With the directory you want selected click Open to create the SDK
  ![Screen Shot 2022-04-30 at 7 57 49 PM](https://user-images.githubusercontent.com/298259/166127661-1b34d79d-0bca-4ff8-a16a-5617f64efe90.png)
7. Check the name of the SDK and rename it if you like.
   ![Screen Shot 2022-04-30 at 7 58 00 PM](https://user-images.githubusercontent.com/298259/166127662-36a6fee1-39d0-4e31-915b-d3eb395a4658.png)
8. Go back to your Elixir SDK and you can set the Erlang SDK to use. Hit Apply or OK to save.
  ![Screen Shot 2022-04-30 at 7 58 14 PM](https://user-images.githubusercontent.com/298259/166127663-eb78926e-73a5-44c3-b4aa-f0f85d9425e5.png)
