### ISSUE TITLE
Every time I close Webstorm - it forgets my Elixir SDK

### ISSUE THREAD

**Issue by delmendo** [KronicDeth/intellij-elixir#2627]
**Describe the bug**
I have to set the Elixir SDK every time I close and re-open Webstorm. Also my .idea/project.iml is filled with refrences to my elixir version. It keeps adding them as I set it.

**To Reproduce**
I set the Elixir SDK in the Webstorm.
 I close webstorm. 
It requires me to set it again.

**Expected behavior**
I would expect it to stay set between restarts.

**Screenshots**
This is the error I get every time I close and re-open Webstorm and look at an elixr file
![NotDefined](https://user-images.githubusercontent.com/138773/166502465-f4de2c90-2057-499c-a4d6-58a13c2543ee.png)
![Setting](https://user-images.githubusercontent.com/138773/166502438-31f74683-94d1-44e3-aaca-c379006004fe.png)
![Project-iml](https://user-images.githubusercontent.com/138773/166502480-7151efa3-a2cb-4b59-9f5a-1a8c214dc412.png)

**Desktop:**
Ubuntu 21.10
**Erlang:**
asdf
otp 24
**Elixir:**
asdf
1.13.3

**Plugin:**
12.2.1

**Additional context**

**Comment by ghenry** [comment]
Hi,

How are you setting your SDK in the first place? I get these:

![Screenshot from 2022-05-22 21-32-28](https://user-images.githubusercontent.com/159608/169714693-5d90158b-f7b3-4212-99cf-4799ef9ac949.png)
![Screenshot from 2022-05-22 21-32-39](https://user-images.githubusercontent.com/159608/169714692-9c6a4a52-0e4c-456b-be64-a9add7e6eca3.png)
![Screenshot from 2022-05-22 21-32-47](https://user-images.githubusercontent.com/159608/169714691-c1744355-aa65-4e5e-8192-50cab28158b5.png)

**Comment by KronicDeth** [comment]
In 13.0.0 the Project select lists no projects as reported in #2656.  This bug is superseded by that bug until it is fixed.

**Comment by ghenry** [comment]
Thanks. I've binned .idea in this too to no avail. I have the "all ide" subscription, so I have to open up one I don't use just to use this...Is this your FL/OSS plugin or should Jetbrains be paying more attention to this? Happy to raise it via our paid sub if that helps.

**Comment by ghenry** [comment]
Sorted. Wrong paths for me.

![Screenshot from 2022-05-22 22-45-41](https://user-images.githubusercontent.com/159608/169717265-1cc28e80-8137-439f-9995-a029f0fa4a8d.png)
![Screenshot from 2022-05-22 22-45-35](https://user-images.githubusercontent.com/159608/169717267-f2f59fe3-5c81-4b00-a48d-d04480433d36.png)

**Comment by KronicDeth** [comment]
It looks like what is happening is that the facet is loaded before the SDKs are in general, so it thinks the facet has an SDK name set for a non-existent SDK and so doesn't retain changes correctly.

**Comment by KronicDeth** [comment]
@delmendo @ghenry Pre-release build from #2627 for you to try out for yourself too

[intellij-elixir-13.1.0-pre+20220524145449.zip](https://github.com/KronicDeth/intellij-elixir/files/8763999/intellij-elixir-13.1.0-pre%2B20220524145449.zip)
