### ISSUE TITLE
Can't select Elixir SDK

### ISSUE THREAD

**Issue by henriquezago** [KronicDeth/intellij-elixir#2649]
# System

Plugin Version: 13.0.0
Application: WebStorm (2022.1)
Operating System: Mac OS X (12.3.1)

<img width="981" alt="Screen Shot 2022-05-09 at 12 01 19" src="https://user-images.githubusercontent.com/5287289/167439067-c63bd381-3a8f-430a-896f-5680cd09dd2b.png">

# Event

**Comment by KronicDeth** [comment]
You see where it says “SDKs” and “Internal Erlang SDKs” as submenus to the “Elixir” one you have selected?  You go there to define the SDKs. Then come back the the Elixir menu and select the SDK you want to use for each project you have open.

**Comment by henriquezago** [comment]
but I have selected both Elixir and Erlang SDKs.
<img width="983" alt="Screen Shot 2022-05-13 at 15 52 22" src="https://user-images.githubusercontent.com/5287289/168354086-7d8040f4-a60b-48d2-8474-0391c4f66b50.png">
<img width="978" alt="Screen Shot 2022-05-13 at 15 53 47" src="https://user-images.githubusercontent.com/5287289/168354236-3fa8583f-8f55-485b-abcf-f1eb3a9e0eae.png">

**Comment by KronicDeth** [comment]
That’s not selecting them for the project.  Select the word Elixir in the left menu

**Comment by KronicDeth** [comment]
This is the same as #2656 and so was fixed by #2676, which was just released in 13.1.0.

**Comment by hernanvicente** [comment]
I was having this problem, and it was stopping me from updating RubyMine. The new version of the plugin works without problems. Thanks a lot!
