### ISSUE TITLE
Upon build: java.lang.NoClassDefFoundError: com/intellij/openapi/application/ApplicationManager

### ISSUE THREAD

**Issue by hengestone** [KronicDeth/intellij-elixir#2655]
**Describe the bug**
After upgrading to IDEA 2022.1, building a project results in:
* Elixir '<projectname>' java.lang.NoClassDefFoundError: com/intellij/openapi/application/ApplicationManager *

**To Reproduce**
1. Open an Elixir project
2. Go to Build -> Build the project
3. See error in the Build Output

**Expected behavior**
Build should run `mix compile` and the build should succeed.

**Screenshots**
![Screenshot from 2022-05-10 16-55-06](https://user-images.githubusercontent.com/362587/167742968-5248405a-6e76-4d06-94ff-880d05ad6417.png)

**Logs**
App doesn't crash or hang

**Desktop:**
```
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 11, 2022
Licensed to <me>
Subscription is active until April 3, 2023.
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-27-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry: ide.balloon.shadow.size=0
```

Non-Bundled Plugins:
org.elixir_lang (13.0.0)

Kotlin: 221-1.6.20-release-285-IJ5080.210
Current Desktop: ubuntu:GNOME

**Erlang:**
- Installer asdf
- Version 24.1.4

**Elixir:**
- Installer asdf
- Version 1.12.3

**Plugin:**
- Version [e.g. 10.3.0]

**Additional context**
Worked fine with older versions.

**Comment by KronicDeth** [comment]
I can reproduce this locally

**Comment by KronicDeth** [comment]
I can't reproduce with the latest pre-release build from `main` though, so I'm not sure why, but I'm counting this as fixed.

**Comment by hengestone** [comment]
Works here too, thanks!!!
