### ISSUE TITLE
Can't select SDK in RubyMine 2022.1

### ISSUE THREAD

**Issue by Nihisil** [KronicDeth/intellij-elixir#2656]
I was able to set up global Elixir and Erlang SDK, but I can't select SDK for the project, and the error message "Elixir Facet SDK is not defined" is always displayed on the top of each file.

There is message "Nothing to show" displayed in the section where I suppose select project level SDK.

Is there any known workaround? I didn't find similar issues on GitHub. Thanks.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/475367/167976520-0f1657bc-85c8-476d-b464-f56c69eba4f9.png">

Global Elixir SDK was configured:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/475367/167976792-963e3cc4-dcce-43a6-a440-8a12d7704f56.png">

Global Erlang SDK was configured:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/475367/167976818-f63d7885-a43f-455e-88d0-fc34947fb611.png">

*Desktop:**
 - OS: Mac OS
 - Version 12.3.1

**Erlang:**
- Installer homebrew
- Version 24.3.4

**Elixir:**
- Installer homebrew
- Version 1.13.4

**Plugin:**
- Version 13.0.0

**Comment by nmbrone** [comment]
+1 WebStorm

**Comment by KronicDeth** [comment]
The work-around would be to use IntelliJ Community (because it’s free) or IntelliJ Ultimate if you have a license for that while I figure this out.

I’m going to guess that something changed in the small IDEs in 2022 or one of deprecation warning fixes broke small IDEs.  The SDK support for an alternative language (Elixir) is a precarious port of the support normally only in IntelliJ (which allows any language) by making it be a Facet of the base Module in the IDE’s language still.

**Comment by ghenry** [comment]
I can't set this either in IntelliJ Ultimate:

```
IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 10, 2022
Licensed to Suretec Systems Limited / Gavin Henry
Subscription is active until November 29, 2022.
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.17.6-300.fc36.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    com.github.copilot (1.1.22.1530)
    org.elixir_lang (13.0.0)

Kotlin: 221-1.6.21-release-337-IJ5591.52
Current Desktop: GNOME
```

See:

![Screenshot from 2022-05-22 22-29-39](https://user-images.githubusercontent.com/159608/169716704-20ff7928-97c8-4ad1-b017-3e78960919eb.png)
![Screenshot from 2022-05-22 22-28-27](https://user-images.githubusercontent.com/159608/169716705-4a04d37a-2c48-4cd4-9dee-1b531fe7278b.png)
![Screenshot from 2022-05-22 22-28-23](https://user-images.githubusercontent.com/159608/169716706-0d8086f0-993b-4059-9c86-975a60be7d29.png)
![Screenshot from 2022-05-22 22-28-12](https://user-images.githubusercontent.com/159608/169716707-2f12355b-a8af-4adb-a0fb-597c21e099d1.png)
![Screenshot from 2022-05-22 22-28-04](https://user-images.githubusercontent.com/159608/169716708-9749b3fd-8055-4b1a-be51-46a3ff1dc812.png)


Thanks.

**Comment by ghenry** [comment]
Sorted. Wrong paths for me on  Fedora 36 64bit:

![Screenshot from 2022-05-22 22-45-41](https://user-images.githubusercontent.com/159608/169717265-1cc28e80-8137-439f-9995-a029f0fa4a8d.png)
![Screenshot from 2022-05-22 22-45-35](https://user-images.githubusercontent.com/159608/169717267-f2f59fe3-5c81-4b00-a48d-d04480433d36.png)

**Comment by MichaelHipp** [comment]
Same here using IntelliJ Ultimate 2022.1.1. Running on Windows doing a project in WSL under Ubuntu Linux. Elixir & Erlang are installed in /usr/lib (well \\wsl$\Ubuntu\usr\lib actually). But it will not accept any location in either of those dirs for the Erlang SDK for Elixir.

**Comment by KronicDeth** [comment]
@ghenry you have a different issue than the original issue.  The SDK system in different in IntelliJ vs the other small (language-specific) IDEs.  

@MichaelHipp I've never claimed support for WSL yet.  You also have a different issue.  See #1384

**Comment by KronicDeth** [comment]
> then doesn't always update after that, like when I install a new version of Erlang or Elixir via ASDF. I usually have to wipe the .iml or prune the entries after such change to get it working again. If I add a new version in ASDF, sometimes I have to manually add the entry and set the SDK by editing the file.

@drl123 There's no support for automatically detecting newly installed Elixir SDKs and creating entries in any of the Small IDEs.  IntelliJ has a subsystem that gives suggestions for new SDKs, but no SDK is every automatically created.  I would never expect this to work in any of the published releases of the plugin so far.

**Comment by KronicDeth** [comment]
13.0.0 changed to support build numbers covering WebStorm 2021.3 don't restore the Project Selection, so I believe the loss is not related to 2022 changes, but instead something in the deprecated warning fixes that broke the Project SDK selection in general.

**Comment by KronicDeth** [comment]
I'm going to through `git bisect` at the problem and see if it can find which specific fix broke the panel since no error is actually reported

**Comment by KronicDeth** [comment]
Panel works in 4e5cfc2

**Comment by KronicDeth** [comment]
Panel broken in 20f483f20ed2d4c5ff0c341438fc21749c5a4943

**Comment by KronicDeth** [comment]
Panel works in 389a76f17

**Comment by KronicDeth** [comment]
Panel broken in f8e2ba2d2

**Comment by KronicDeth** [comment]
Panel broken in ee8e59080

**Comment by KronicDeth** [comment]
Panel works in 9b3367c0a

**Comment by KronicDeth** [comment]
`git bisect` blames ee8e59080556fe91b511ab4ffa39c4e8b31427a9, but I was a dingus and fixed a bunch of warnings all at once, so I need to pick this apart.

```
    Fix plugin verifier deprecation and internal API warnings
    
    Not all warnings can be fixed as some require a greater rewrite of the Credo annotator or advice from JetBrains about how to avoid PlatformUtils.

 jps-builder/src/org/elixir_lang/jps/Builder.java   |  43 +-
 .../jps/builder/GeneralCommandLine.java            |  33 +-
 .../jps/compiler_options/Serializer.java           |  25 +-
 .../elixir_lang/jps/mix/SettingsSerializer.java    |  27 +-
 .../elixir_lang/jps/model/SerializerExtension.java |  83 ++--
 src/org/elixir_lang/beam/psi/BeamFileImpl.kt       |   1 -
 src/org/elixir_lang/code_insight/ParameterInfo.kt  |  26 +-
 .../configuration/ElixirCompilerSettings.java      | 140 +++----
 .../elixir_lang/console/FileReferenceFilter.java   |  10 +-
 src/org/elixir_lang/credo/Service.java             |  50 ---
 src/org/elixir_lang/credo/Service.kt               |  26 ++
 src/org/elixir_lang/debugger/Process.kt            | 202 +++++-----
 .../debugger/stack_frame/value/LazyContainer.kt    |   7 +-
 src/org/elixir_lang/distillery/State.kt            |   6 +-
 .../distillery/configuration/Editor.java           |  16 +-
 src/org/elixir_lang/elixir/State.kt                |   6 +-
 .../elixir_lang/elixir/configuration/Editor.java   |  16 +-
 src/org/elixir_lang/erl/configuration/Editor.java  |  13 +-
 .../elixir_lang/espec/configuration/Editor.java    |  13 +-
 .../elixir_lang/exunit/configuration/Editor.java   |  13 +-
 src/org/elixir_lang/facet/configurable/Project.kt  |  10 +-
 src/org/elixir_lang/folding/Builder.kt             | 416 ++++++++++---------
 .../elixir_lang/folding/ElixirFoldingSettings.java |  11 +-
 .../settings/CodeStyleSettingsProvider.java        |   5 +-
 .../LanguageCodeStyleSettingsProvider.java         | 439 ---------------------
 .../settings/LanguageCodeStyleSettingsProvider.kt  | 388 ++++++++++++++++++
 src/org/elixir_lang/iex/State.kt                   |   6 +-
 src/org/elixir_lang/iex/configuration/Editor.java  |  16 +-
 src/org/elixir_lang/iex/mix/State.kt               |   6 +-
 .../elixir_lang/iex/mix/configuration/Editor.java  |  15 +-
 src/org/elixir_lang/mix/State.kt                   |   8 +-
 src/org/elixir_lang/mix/Watcher.kt                 |  51 ++-
 src/org/elixir_lang/mix/configuration/Editor.java  |  13 +-
 .../mix/project/DirectoryConfigurator.kt           |  51 +--
 .../elixir_lang/notification/setup_sdk/Listener.kt |  22 +-
 .../elixir_lang/notification/setup_sdk/Notifier.kt |   4 +-
 .../elixir_lang/notification/setup_sdk/Provider.kt |  29 +-
 src/org/elixir_lang/scope_processor/Module.java    |   8 +-
 src/org/elixir_lang/sdk/elixir/Type.kt             |  12 +-
 .../sdk/erlang_dependent/SdkAdditionalData.java    |   6 +-
 .../elixir_lang/templates/ElixirContextType.java   |  24 --
 src/org/elixir_lang/templates/ElixirContextType.kt |  24 ++
 42 files changed, 1080 insertions(+), 1240 deletions(-)
 delete mode 100644 src/org/elixir_lang/credo/Service.java
 create mode 100644 src/org/elixir_lang/credo/Service.kt
 delete mode 100644 src/org/elixir_lang/formatter/settings/LanguageCodeStyleSettingsProvider.java
 create mode 100644 src/org/elixir_lang/formatter/settings/LanguageCodeStyleSettingsProvider.kt
 delete mode 100644 src/org/elixir_lang/templates/ElixirContextType.java
 create mode 100644 src/org/elixir_lang/templates/ElixirContextType.kt
```

**Comment by KronicDeth** [comment]
🤦🏻‍♀️ I dropped a `!` when converting from `equals` to `==`

**Comment by KronicDeth** [comment]
@Nihisil @nmbrone @drl123  Here's the pre-release build for everyone to test out 

[intellij-elixir-13.1.0-pre+20220523032019.zip](https://github.com/KronicDeth/intellij-elixir/files/8751254/intellij-elixir-13.1.0-pre%2B20220523032019.zip)

**Comment by ghenry** [comment]
> @ghenry you have a different issue than the original issue.  The SDK system in different in IntelliJ vs the other small (language-specific) IDEs.  
>

Thanks, understood. Thank you for the plug in.

**Comment by drl123** [comment]
> @Nihisil @nmbrone @drl123 Here's the pre-release build for everyone to test out
> 
> [intellij-elixir-13.1.0-pre+20220523032019.zip](https://github.com/KronicDeth/intellij-elixir/files/8751254/intellij-elixir-13.1.0-pre%2B20220523032019.zip)

Hey, now that's more better! Works like a charm. :-) 

Thanks for all of the hard work and effort resolving this and building such a fantastic plugin.
