### ISSUE TITLE
New Project does not allow Elixir to be selected in IDEs 2022.*

### ISSUE THREAD

**Issue by port513** [KronicDeth/intellij-elixir#2663]
Updated both plugins and now I can't see any project templates and it suggest JDK as the framework...

![IntelliJ Problem](https://user-images.githubusercontent.com/298259/168846162-a7cfd693-94eb-4138-9cd7-7a2829ba8058.PNG)
![Plugins IntelliJ IDEA](https://user-images.githubusercontent.com/298259/168846167-68e60b60-bf86-4721-a159-902fd2b1390f.PNG)

Have latest Erlang and Elixir installed and it worked before...

**Comment by KronicDeth** [comment]
I never supplied Erlang templates with this plugin.  The Erlang plugin is a separate project.

**Comment by KronicDeth** [comment]
I don't even remember making project templates for Elixir 🤔.  I always use `mix new` or `mix phx.new` and [Creating a project from Existing Sources](https://github.com/KronicDeth/intellij-elixir#import-project-from-external-model), so I don't really think about that.  I can see [it's in the README](https://github.com/KronicDeth/intellij-elixir#new) though, so I guess it was a thing. 

Since it disappeared for both Elixir and Erlang I assume what happened is JetBrains changed the API or something and it affected both projects because a lot of the early code in the Elixir plugin is adapted from the Erlang plugin, so we can break in similar ways.  You should report the loss of Erlang template to that plugin though.

**Comment by shahdeys** [comment]
Thank you for this beautiful plugin btw!

In terms of the functionality that is missing I think what a user is expecting is the following:

Button on the left to bootstrap an Elixir project, with the actual functionality being `mix new <project_name_here>`


@port513 as a workaround, you could simply do this for now until @KronicDeth works on this feature: https://www.jetbrains.com/help/idea/saving-project-as-template.html

**Comment by KronicDeth** [comment]
@shahdeys what you’re asking for is a new feature and so should be broken out as such.  What @port513 is reporting is loss of an existing feature.  Please don’t mix bug reports and feature requests.

**Comment by KronicDeth** [comment]
![Screen Shot 2022-05-24 at 9 00 57 PM](https://user-images.githubusercontent.com/298259/170163471-d72c62cc-2a7a-4529-8192-984f2bf50821.png)

This is where the tooltip comes from in

https://github.com/KronicDeth/intellij-elixir/blob/5bd4de6f783f31bf6790dd2b2dbfc9cd843f99d1/src/org/elixir_lang/module/ElixirModuleType.java#L41-L45

**Comment by KronicDeth** [comment]
The Java text in 2021.* is

![Screen Shot 2022-05-25 at 8 25 46 AM](https://user-images.githubusercontent.com/298259/170273069-08833cf2-09a8-44b1-a623-21aa2c52d5f1.png)


The java text in 2022.* isn't there, but neither is the word "Java".  Instead, it's in New Project as a Language select

![Screen Shot 2022-05-25 at 8 35 13 AM](https://user-images.githubusercontent.com/298259/170275696-89228056-a4bd-49fa-9545-d7d5cb34bdf3.png)
![Screen Shot 2022-05-25 at 8 35 22 AM](https://user-images.githubusercontent.com/298259/170275699-95692006-2e96-4797-bf0e-867a8b5d9c60.png)

So, the answer is that it wasn't a project template in 2021.* @port513, it was just the `ModuleType` and in 2022.* the IDEs no longer list all module types.

**Comment by KronicDeth** [comment]
It appears that that part of the UI is controlled by the `com.intellij.newProjectWizard.language` extension point

**Comment by KronicDeth** [comment]
It looks like `com.intellij.newProjectWizard.language` is not right because the API then creates the root project directory, which doesn't work since `mix new` also wants to create it.
