### ISSUE TITLE
Code Format not working with 13.1 and Webstorm 2022.2

### ISSUE THREAD

**Issue by delmendo** [KronicDeth/intellij-elixir#2700]
**Describe the bug**
The code format command is ignored when you use 13.1 and Webstorm 2022.2

**To Reproduce**
I updated to Webstorm 2022.2
I updated the plugin to 13.1

I choose Code Format from the menu and nothing happens.
Here is a small video of nothing happening when I hit code format
![13 1-no-reformat](https://user-images.githubusercontent.com/138773/171620535-61107515-4160-412e-9fb3-85512d1367ad.gif)

To fix a previous problem you gave me a pre-release version of 13.1 to fix problems with it not storing the Elixir SDK correctly.
[intellij-elixir-13.1.0-pre+20220524145449.zip](https://github.com/KronicDeth/intellij-elixir/files/8823303/intellij-elixir-13.1.0-pre%2B20220524145449.zip)

If I load 2022.2 with that pre-release version then it formats the code
![Pre-13 1-version](https://user-images.githubusercontent.com/138773/171620531-65d25e63-10bb-4c8b-9c52-407d4ad5086f.gif)

So something happened between that fix and the release. I'm hoping that helps narrow the hunt for the source of the problem

**Expected behavior**
I expected code to get formatted when I ask Webstorm to format Elixir

**Desktop:**
 - OS:  Ubuntu 
 - Version 21.10

**Erlang:**
- Installer asdf
- Version 24.0.1

**Elixir:**
- Installer asdf
- Version 1.13.3

**Plugin:**
- Version  13.1.0

**Comment by KronicDeth** [comment]
Can you please transcribe a complete code sample into a code block here, so I don’t need to copy it out of the video myself?

**Comment by delmendo** [comment]
test "should allow valid user", %{job_invitation: job_invitation} do
      user_uuid = UUID.uuid4()
      other_user = insert(
        :accounts_user_projection,
        uuid: user_uuid,
        email: "other@sample.com",
        warrant: build(
          :warrant,
          user_uuid: user_uuid,
          authorizations: [build(:accounts_user_projection, uuid: user_uuid),
            build(:personal_history_owner_projection, uuid: user_uuid, user_uuid: user_uuid)
          ]
        )
      )
    end

**Comment by delmendo** [comment]
I found the docs on turing off the external formatting  this solved the problem.
Settings > Code Style > Elixir  > uncheck "FOrmat files with 'mix format'
  I seem to be having other problems with  paths because I'm in an umbrella in a mix mono repo. Once I have a more reporducible problem I'll open an issue.
