### ISSUE TITLE
java.io.IOException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)

### ISSUE THREAD

**Issue by digitsu** [KronicDeth/intellij-elixir#2721]
# System

Plugin Version: 13.1.1
Application: IntelliJ IDEA Community Edition (2022.1.2)
Operating System: Mac OS X (12.4)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException
</summary>

```
java.io.IOException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)
```

</details>

**Comment by KronicDeth** [comment]
This means you should have gotten a Notification about why the `mix new` failed. I'll have to look into suppressing this reporting to the error report, but still failing the New Project Wizard.

**Comment by KronicDeth** [comment]
Duplicate of #2740
