### ISSUE TITLE
Don't know how to collect doc comments at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)

### ISSUE THREAD

**Issue by rbaezam** [KronicDeth/intellij-elixir#2774]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2)
Operating System: Mac OS X (12.5)

# Event

### Element

```
)
```

From: `/Users/rodolfo/Code/Personal/sales_point/lib/sales_point_web/live/sale_live/new.ex:295`

#### Context

```
      Decimal.sub(subtotal, Decimal.from_float(discount_amount))

    %{subtotal: subtotal, total: new_total}
  end

  defp get_default_assigns(socket) do
    new_sale = %{
      temp_id: 1,
      status: :active,
      subtotal: 0.0,
      discount_amount: 0.0,
```

From: `/Users/rodolfo/Code/Personal/sales_point/lib/sales_point_web/live/sale_live/new.ex:290-300`
            
### Element Class Name

```
com.intellij.psi.impl.source.tree.PsiErrorElementImpl
```

### Stacktrace

<details>

<summary>
java.lang.Throwable: Don't know how to collect doc comments
</summary>

```
java.lang.Throwable: Don't know how to collect doc comments
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:45)
	at org.elixir_lang.errorreport.Logger.error(Logger.kt:25)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:90)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:81)
	at org.elixir_lang.documentation.ElixirDocumentationProvider.collectDocComments(ElixirDocumentationProvider.kt:77)
```

</details>

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/blob/4ca4cd3ea8de3242c81d964ac6bf9087db1c4483/src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt#L84-L93

needs to ignore `PsiErrorElement` the same way it does for `DummyBlock` already.
