### ISSUE TITLE
Highlighting for def*

### ISSUE THREAD

**Issue by PragTob** [KronicDeth/intellij-elixir#278]
Hi there and thanks for creating intellij-elixir,

from the [screenshots](https://github.com/KronicDeth/intellij-elixir/raw/master/screenshots/annotator/Module%20Attribute.png?raw=true) it looks like `def`, `defp`, `defmacro`, `defmodule` and friends can be highlighted but I seem to be to dumb to find it. They also don't show up in the docs about highlighting (or under a different name).

in the colors & fonts menu (see below) it doesn't highlight anything above when I put the cursor on a `def*` and I failed to find an option changing its display.

![selection_285](https://cloud.githubusercontent.com/assets/606517/14065758/f1cda02e-f436-11e5-860c-710a1f7afb3d.png)

Now the question is, is it impossible (could we make it possible then pls?) or am I just too dumb? :) For me the highlights for `def*` are among the most important.

If that helps/is needed I'm running RubyMine 8.0.3 on Linux Mint 17.3 (based on Ubuntu 14.04 LTS) on OpenJDK 8.

Thanks!
Tobi

**Comment by NobbZ** [comment]
Def and it's siblings aren't keywords, but kernel or specialform macros.
Can't remember where exactly they are classified under.

Tobias Pfeiffer <notifications@github.com> schrieb am So., 27. März 2016
16:17:

**Comment by KronicDeth** [comment]
@NobbZ is right.  @PragTob you're just off by 2 in the screenshot you posted:  You have `Keywords` highlighted and you want [`Kernel Macros` to change the highlighting on `def*`](https://github.com/KronicDeth/intellij-elixir/blob/1d9b830bcbfbb214a2a51ca2f9cf280d39188050/src/org/elixir_lang/annonator/Kernel.java#L90-L136).

[Kernel Macros](http://elixir-lang.org/docs/stable/elixir/Kernel.html#macros) cover the following names:
* `@`
* `alias!`
* `and`
* `binding`
* `def`
* `defdelegate`
* `defexception`
* `defimpl`
* `defmacro`
* `defmacrop`
* `defmodule`
* `defoverridable`
* `defp`
* `defprotocol`
* `defstruct`
* `destructure`
* `get_and_update_in`
* `if`
* `in`
* `is_nil`
* `match?`
* `or`
* `put_in`
* `raise`
* `raise`
* `reraise`
* `reraise`
* `sigil_C`
* `sigil_R`
* `sigil_S`
* `sigil_W`
* `sigil_c`
* `sigil_r`
* `sigil_s`
* `sigil_w`
* `to_char_list`
* `to_string`
* `unless`
* `update_in`
* `use`
* `var!`

**Comment by KronicDeth** [comment]
@PragTob I opened #279 to cover updating the docs so that other users don't run into the same issue as you in the future.  Thank you for pointing out this usability issue.  Please close this issue if my instructions for changing the Kernel Macros highlighting wasn't clear.

**Comment by PragTob** [comment]
Hey there,

I did try Kernel macros/Kernel. SpecialForm macros and none of them worked when I tried it. There seems to be a bug in preview. I set them to bold now and as you can see in the screenshot it seems to apply to real code (background) but not in the preview window of Color & Fonts which is why I thought it didn't work.

![selection_006](https://cloud.githubusercontent.com/assets/606517/14074695/3d780054-f4d3-11e5-99e5-68c4ab7a92c5.png)

Should I close this and open a new bug for the preview?

Thanks for the help!

**Comment by KronicDeth** [comment]
@PragTob I had originally thought it was not possible to run annotators on the Colors & Fonts preview because only the syntax highlighter worked by default, but after researching stuff for @net on Slack, I found https://intellij-support.jetbrains.com/hc/en-us/community/posts/206140629-ColorSettingPage-for-annotator-highlighting on the OpenAPI forums, so yeah, open a new issue to run the annotators on the Color & Fonts Preview and close this issue.  You should open the issue so you show up as the reporter instead of me as I use issues not open by me as a priority.

**Comment by KronicDeth** [comment]
Just found out it **is** possible to set the attributes for the custom `TextAttributeKey`s using an `additionTextAttributes` key, which would allow to set the attributes in the default theme or Darcula.  That is now open as #299

**Comment by KronicDeth** [comment]
Resolved by #322.  Released in [v4.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v4.0.0)
