### ISSUE TITLE
Enumerate Kernel functions, macros, and Kernel.SpecialForm macros

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#279]
Both @PragTob in #278 and @thirdshift in https://github.com/KronicDeth/intellij-elixir/issues/250#issuecomment-196104377 assumed that `Keywords` would control the highlighting for `def`, so the README can't make the assumption that users know what's a keyword, kernel function, kernel macro or kernel special form in Elixir.  To help new users, the exact matched element should be enumerated for each category in the README and help text/tooltip in the Color & Fonts settings if that is possible.

**Comment by PragTob** [comment]
Little correction, I didn't assume keywords controlled `def*` it was just selected by accident as the last thing I had the cursor on that selected the right thing above was `do`. I did think that it was Kernel.Macros (or special form) but changing the color highliting for this didn't change the color highlighting in the preview window below + putting the cursor on `def*` didn't automatically select Kernel.Macros as it does with Strings, Keywords and everything else so I wrongfully assumed it wasn't possible, as live updating the preview below and auto selecting the fittign category seemed to work with everything else. :) Also see [comment with screenshot in the other issue](https://github.com/KronicDeth/intellij-elixir/issues/278#issuecomment-202309123).

Thanks for your work!
Tobi
