### ISSUE TITLE
Freeze/endless loop when trying to format an .ex file

### ISSUE THREAD

**Issue by Dreamer93** [KronicDeth/intellij-elixir#2811]
**Describe the bug**
When trying to format an .ex file, IDE freezes and seems to loop endlessly as it freezes my whole machine

**To Reproduce**
1. Open any .ex file
2. Change to invalid formatting state
3. Format file
4. Observe

**Expected behavior**
Working formatting

**Logs**
[threadDumps-freeze-20220824-152522-WS-222.3739.57.zip](https://github.com/KronicDeth/intellij-elixir/files/9416527/threadDumps-freeze-20220824-152522-WS-222.3739.57.zip)

**Desktop:**
 - OS: Ubuntu
 - Version 20.04.4 LTS

**Erlang:**
- Installer asdf
- Version 24.0.6

**Elixir:**
- Installer asdf
- Version 1.13.0-otp-24

**Plugin:**
- Version 13.2.0

**Comment by KronicDeth** [comment]
This should be fixed by #2800 as it is also due to decompiling and trying to parse files too deeply.
