### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file://E:/ideaUltimate/erlang/src/test.beam (invalid) is invalid, invalidated at: no info at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)

### ISSUE THREAD

**Issue by ozzyozbourne** [KronicDeth/intellij-elixir#2816]
# System

Plugin Version: 13.2.0
Application: IntelliJ IDEA Ultimate Edition (2022.2.1)
Operating System: Windows 10 (10.0)

# Event

### Stacktrace

<details>

<summary>
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file://E:/ideaUltimate/erlang/src/test.beam (invalid) is invalid
</summary>

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file://E:/ideaUltimate/erlang/src/test.beam (invalid) is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)
```

</details>

**Comment by KronicDeth** [comment]
Unfortunately the stack trace is too short to infer enough context to reproduce since I don't have the caller information.  This will have to wait until I can reproduce it under the debug and refile with the better stack trace.
