### ISSUE TITLE
Setup SDK is not defined(always....)

### ISSUE THREAD

**Issue by zhongwencool** [KronicDeth/intellij-elixir#285]
![image](https://cloud.githubusercontent.com/assets/3116225/14098169/adc8a2b8-f5ab-11e5-82de-7dac037de3b2.png)

event restart the mac OXS

**Comment by zyuyou** [comment]
@zhongwencool show the version of `idea` and the plugin please. Is there anything else wrong?

**Comment by zyuyou** [comment]
The latest version of plugin works fine in the `IDEA CE 15.02`, I just test it out.

**Comment by zhongwencool** [comment]
@zyuyou I reinstall intellij, it's ok now~~

IntelliJ IDEA 2016.1
Build #IC-145.258, built on March 17, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o


Thanks~
