### ISSUE TITLE
Cannot create SDK 

### ISSUE THREAD

**Issue by jtmarmon** [KronicDeth/intellij-elixir#2855]
**Describe the bug**
When attempting to create a New project or New project from existing sources, I get the "cannot create SDK" dialog: 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/4528076/190299461-9d753c75-dec5-4828-bcde-2f1093643d35.png">

When I click "OK", I get taken to the file browser of my laptop.

**Expected behavior**
I read in https://github.com/KronicDeth/intellij-elixir/issues/1132 that click OK should take me through the erlang setup process, so I expected something more specific than a file browser (e.g. I get offered a list of erlang versions or something).

**Desktop:**
 - OS: MacOS (M1)
 - Version 12.2.1 

**Erlang:**
- Homebrew
- Version 25.0.4

**Elixir:**
- Installer: Homebrew
- Version 1.14.0

**Plugin:**
- Version: 13.2.0

**Comment by KronicDeth** [comment]
The file browser opens to the newest detected Erlang SDK version.  This SDK system is part of the JetBrains API. I just use it.  If you want a different experience you can use the suggested SDK list at the bottom of the SDK type list.

**Comment by jtmarmon** [comment]
@KronicDeth It doesn't for me - it just opens up to the root of the same project (`hello/` in this case)
<img width="704" alt="image" src="https://user-images.githubusercontent.com/4528076/191093086-d6c34424-f27e-42c6-90ac-7dbdb15d8bea.png">

**Comment by jtmarmon** [comment]
I recognize it looks like I don't have elixir installed here, but I do. `elixir -v` gives me
```
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
```

`which elixir` gives `/opt/homebrew/bin/elixir`

**Comment by jtmarmon** [comment]
So I found your [helpful instructions](https://github.com/KronicDeth/intellij-elixir#default-sdk) in the readme and managed to set up the SDKs manually.  FYI I did get the missing SDK error:

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.0` is missing Erlang SDK
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.project._import.step.Root$1.run(Root.java:80)
```


But things seem to be working and i don't get it again when I restart the IDE.
