### ISSUE TITLE
Markdown rendered view do not show ` quoted term when it is not linked.

### ISSUE THREAD

**Issue by odk211** [KronicDeth/intellij-elixir#2867]
**Describe the bug**
Markdown rendered view do not show <code>`</code> quoted term when it is not linked.

This is plane view of `Task.Supervisor.async_stream_nolink/3` doc.
<img width="867" alt="スクリーンショット 2022-09-24 9 33 09" src="https://user-images.githubusercontent.com/1321120/192072506-d4201515-2e91-41a3-b702-f5307ff608d9.png">

In rendered view, `async_nolink/3`, `async_stream/6` is shown, but `function`, `enumerable` is ignored.
<img width="848" alt="スクリーンショット 2022-09-24 9 33 20" src="https://user-images.githubusercontent.com/1321120/192072521-c0dd4dab-ab88-4658-a342-844825c7a127.png">

**Desktop:**
 - OS: Mac OS X
 - Version 11.6.8

**Erlang:**
- Installer asdf
- Version 25.0.1

**Elixir:**
- Installer asdf
- Version 1.13.4-otp-25

**Plugin:**
- Version 13.2.0

**Additional context**
Thank you for your effort for this plugin! Markdown support is pretty good! Also thanks for the mention of me in ElixirConfEU. ❤️

**Comment by KronicDeth** [comment]
I think I recall seeing this when I was developing the feature.  I need to figure out if the linking API allows something for "cannot resolve link" OR if I need to not even generate the link tag if I can't resolve it.  Thanks for pointing to a specific file that I can use as a test case ❤️

**Comment by odk211** [comment]
https://github.com/KronicDeth/intellij-elixir/pull/3491 fix this issue, Thanks!!
