### ISSUE TITLE
kotlin.KotlinNullPointerException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:81)

### ISSUE THREAD

**Issue by HuseinJafari-Kargo** [KronicDeth/intellij-elixir#2903]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.3)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
kotlin.KotlinNullPointerException
</summary>

```
kotlin.KotlinNullPointerException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:81)
```

</details>

**Comment by KronicDeth** [comment]
Duplicate of #2740
