### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: ElixirHeredocImpl(HEREDOC).isValidHost() in class org.elixir_lang.psi.impl.ElixirHeredocImpl returned false so you mustn't inject here. at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.addPlace(InjectionRegistrarImpl.java:136)

### ISSUE THREAD

**Issue by RomanFechtchenko** [KronicDeth/intellij-elixir#2904]
# System

Plugin Version: 13.2.1
Application: WebStorm (2022.2.3)
Operating System: Linux (5.4.0-124-generic)

# Event

### Stacktrace

<details>

<summary>
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: ElixirHeredocImpl(HEREDOC).isValidHost() in class org.elixir_lang.psi.impl.ElixirHeredocImpl returned false so you mustn't inject here.
</summary>

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: ElixirHeredocImpl(HEREDOC).isValidHost() in class org.elixir_lang.psi.impl.ElixirHeredocImpl returned false so you mustn't inject here.
	at com.intellij.psi.impl.source.tree.injected.InjectionRegistrarImpl.addPlace(InjectionRegistrarImpl.java:136)
	at org.elixir_lang.injection.markdown.Injector.injectMarkdownInQuote(Injector.kt:145)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInjectInQuote(Injector.kt:30)
	at org.elixir_lang.injection.markdown.Injector.getLanguagesToInject(Injector.kt:24)
```

</details>

### `host.txt`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.
### `induced.txt`

Please copy the contents of the above path into this report: files are too long to include in the URL when opening the browser.  You can get the exact contents of that path when the error occurred from the Attachments tab of the IDE Fatal Errors dialog that you had open before clicking the button to submit this issue.

**Comment by KronicDeth** [comment]
In 13.2.1

https://github.com/KronicDeth/intellij-elixir/blob/60adacd4ee95612612f25a723571bfcd58295c5f/src/org/elixir_lang/injection/markdown/Injector.kt#L64-L150

**Comment by KronicDeth** [comment]
In `main`

https://github.com/KronicDeth/intellij-elixir/blob/571f1784e84d8f53af48863ef8dc7c7884574941/src/org/elixir_lang/injection/markdown/Injector.kt#L79-L165
