### ISSUE TITLE
java.io.IOException at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)

### ISSUE THREAD

**Issue by vicsstar** [KronicDeth/intellij-elixir#2910]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Community Edition (2022.2.3)
Operating System: Mac OS X (12.6)

# Event

### Stacktrace

<details>

<summary>
java.io.IOException
</summary>

```
java.io.IOException
	at org.elixir_lang.new_project_wizard.Step.setupProject(Step.kt:135)
```

</details>

**Comment by KronicDeth** [comment]
Duplicate of #2740
