### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.1` is missing Erlang SDK at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)

### ISSUE THREAD

**Issue by rsimoes-pagerduty** [KronicDeth/intellij-elixir#2918]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.2)
Operating System: Mac OS X (12.5.1)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.1` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.1` is missing Erlang SDK
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.project._import.step.Root$1.run(Root.java:80)
```

</details>

**Comment by felipeloha** [comment]
I did the following and couldn't reproduce this:
- ran the current master plugin
- started an elixir project with elixir 
<img width="563" alt="Screenshot 2023-03-10 at 08 51 28" src="https://user-images.githubusercontent.com/36071293/224333192-8c1b8cd6-fca3-4f0a-83bb-4756c31865e5.png">

I could compile and run tests without any trouble
