### ISSUE TITLE
WebStorm 2022.3 compatibility 

### ISSUE THREAD

**Issue by nichita-pasecinic** [KronicDeth/intellij-elixir#2942]
Elixir plugin is not compatible with the latest WebStorm build 2022.3

![image](https://user-images.githubusercontent.com/98735377/204724579-37ba8dd4-98ae-4af8-a0ac-6a17bf83588b.png)

**Comment by laibulle** [comment]
I built it for myself. 

[intellij-elixir-13.2.2-pre+20221104150809.zip](https://github.com/KronicDeth/intellij-elixir/files/10136744/intellij-elixir-13.2.2-pre%2B20221104150809.zip)

**Comment by uaru** [comment]
IntelliJ 2022.3 compatibility needed, too. Anyway, the new version of plugin compatible with 2022.3 version is needed.

**Comment by ViseLuca** [comment]
I've opened a PR: https://github.com/KronicDeth/intellij-elixir/pull/2946 I hope it will be merged soon, but it's not compiling 🤔

**Comment by KronicDeth** [comment]
> it's not compiling 🤔
I think kerl no longer ship Erlang 24.1.6.  Attempting with 24.1.7.

**Comment by KronicDeth** [comment]
This was fixed by [14.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v14.0.0) that was released on 2022-12-16.
