### ISSUE TITLE
Create additionalTextAttributes extension to set default attributes in Darcula

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#299]
It is possible to set the `TextAttribute`s and not just the `TextAttributeKey` in plugin following [the guide](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/color_scheme_management.html).  This would allow setting the colors for all the `TextAttributeKey`s that are currently grey or white to something useful in Darcula.

**Comment by VladShcherbin** [comment]
@KronicDeth hey, any news on this?

Atom and even github have better colors, it's a bit sad to see almost everything in one color.

Thank you!
