### ISSUE TITLE
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///home/mohsen/workspace/erlang-test/nuc/_build/dev/lib/nuc/ebin/Elixir.NUC.beam (invalid) is invalid, invalidated at: no info at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)

### ISSUE THREAD

**Issue by nik-kashi** [KronicDeth/intellij-elixir#2993]
# System

Plugin Version: 14.0.0
Application: IntelliJ IDEA Ultimate Edition (2022.3.1)
Operating System: Linux (5.15.0-56-generic)

# Event

### Stacktrace

<details>

<summary>
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///home/mohsen/workspace/erlang-test/nuc/_build/dev/lib/nuc/ebin/Elixir.NUC.beam (invalid) is invalid
</summary>

```
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.elixir_lang.beam.psi.BeamFileImpl #Elixir  because: file:///home/mohsen/workspace/erlang-test/nuc/_build/dev/lib/nuc/ebin/Elixir.NUC.beam (invalid) is invalid
invalidated at: no info
	at org.elixir_lang.beam.psi.BeamFileImpl.getContainingFile(BeamFileImpl.kt:216)
```

</details>

**Comment by KronicDeth** [comment]
There isn't enough context in the stacktrace to determine what was calling `BeamFileImpl.getContainingFile`.   The trimming of the stacktrace needs to add back in more lines of context to determine what caused this type of error in the future.
