### ISSUE TITLE
Syntax Highlight troubles

### ISSUE THREAD

**Issue by smeevil** [KronicDeth/intellij-elixir#309]
Hi,

I'm still confused on what should or should not work regarding syntax highlighting.

I often see screenshots in your twitter feed that has a lot more highlighting than what I am experiencing. Using the default darcula theme the highlighting is very minimal, creating my own scheme and assigning a specific color to every element and never using the "use inherited attributes" option does make it a little better, but still missing a lot. For example variables are not coloured, nor are things like function names or Module names etc.

I've added two screenshots with code to show how it is being highlighted, as well as a screenshot of the highlighting settings. I hope you can spot what might be causing this ?

Currently using IntelliJ Ultimate 2016.2. 

![2016-05-17 at 14 31](https://cloud.githubusercontent.com/assets/13874/15322329/6c961890-1c3c-11e6-8ec1-fc4232ed30b3.png)
![2016-05-17 at 14 32](https://cloud.githubusercontent.com/assets/13874/15322335/7157e516-1c3c-11e6-9092-27768dd22fca.png)
![2016-05-17 at 14 25](https://cloud.githubusercontent.com/assets/13874/15322340/76670050-1c3c-11e6-801a-e94a339c0367.png)

All the best,

Gerard

**Comment by KronicDeth** [comment]
Variable coloring is not supported yet.  The support you've seen on twitter is probably the screenshots I posted for the in-development work on https://github.com/KronicDeth/intellij-elixir/tree/call-references.  It can [annotate variables, ignored variables, and parameters](https://github.com/KronicDeth/intellij-elixir/blob/call-references/src/org/elixir_lang/annonator/Callable.java#L76-L83).

If you want the build I'm currently using I can start sending you the in-development builds.  You'll get features a few weeks early, but you'll get more errors too.

As for modules, I could have sworn I had that working but there is no usage of `ElixirSyntaxHighlighter.ALIAS` besides the usage on the Color Settings Page, so yeah, that's missing.  Any coloration you've seen in my tweets were the annotations for Cmd+Hovering (underlined) or the shared-reference highlight (color background with white foreground).

**Comment by smeevil** [comment]
I would be happy to receive development builds! If there are any game breaking errors I could always switch back to the regular build.

I've often wished I could help you with contributing to the development, but the entry barrier is really quite high :/ Got a lot of respect for you diving so deep into the bowels of the IDEA api !

**Comment by KronicDeth** [comment]
It looks like JetBrains made it possible to build plugins with Gradle and they documented it even! http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html.  Importantly, if I used Gradle, I can publish to different channels automatically, so I can have a canary build automatically

**Comment by KronicDeth** [comment]
I need to convert to a gradle build before I can publish to alternative (canary, eap, etc) channels on the JetBrains plugin repo, so for now I'll make "pre-release" releases here on github.  First one: https://github.com/KronicDeth/intellij-elixir/releases/tag/v3.0.1.20160520213720.  You'll have to uninstall the current version of the plugin, restart IntelliJ, then install the zip for that release from disk.

**Comment by smeevil** [comment]
The coloration is already a huge improvement and helps a lot ! I will look forward to the future pre-releases :)

Thanks once again for all your effort, hugely appreciated.
