### ISSUE TITLE
WebStorm `2023.1` compatibility

### ISSUE THREAD

**Issue by nichita-pasecinic** [KronicDeth/intellij-elixir#3147]
WebStorm latest build (`2023.1`) it is not compatiblity with this amazing Elixir plugin

![image](https://user-images.githubusercontent.com/98735377/228614227-ec55d9da-a86f-4040-8abd-94257cc12074.png)

**Comment by amirkhaki** [comment]
+ Intellij IDEA

**Comment by slava-vishnyakov** [comment]
> * Intellij IDEA

Not compatible either

<img width="480" alt="image" src="https://user-images.githubusercontent.com/817931/229125688-ebb39689-53e2-4234-b167-d86f2616fb2f.png">

**Comment by KronicDeth** [comment]
Fixed by #3146
