### ISSUE TITLE
ANSI Escape Codes are not processed in Run configuration console output

### ISSUE THREAD

**Issue by Nihisil** [KronicDeth/intellij-elixir#315]
I have tried https://github.com/elixirkoans/elixir-koans

And in intellij idea I can see this output of "meditate" command:

![1](https://cloud.githubusercontent.com/assets/475367/15769250/d63e829e-298b-11e6-842f-e20b9ec2d35f.png)

In console same output looks like this:
![2](https://cloud.githubusercontent.com/assets/475367/15769257/e177a8ac-298b-11e6-93c3-ab7bd35be6d5.png)

I guess it related somehow with file path highlight, but not sure why all this strange symbols were added to output.

**Comment by KronicDeth** [comment]
Those strange additional symbols are [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code).  They are how terminals display colors.  In your console, the terminal emulator is changing the ANSI escape codes into colored text, the Run Configuration does not do that.  I'll look into it to see if I can make it process ANSI escape codes.
