### ISSUE TITLE
Release not being published on Intellij Marketplace

### ISSUE THREAD

**Issue by prertik** [KronicDeth/intellij-elixir#3186]
Hi,

I've noticed that there were a couple of releases since `v14.0.1`, which do not seem to be published in [Intellij IDEs Plugin Marketplace](https://plugins.jetbrains.com/plugin/7522-elixir/versions/stable). Strangely, a pre-release for v15.0.0 is available for canary release. 
<img width="1072" alt="Screenshot 2023-04-23 at 4 38 58 PM" src="https://user-images.githubusercontent.com/12194950/233835661-57f06fc2-d344-4b80-b7b8-6fcf721ad85e.png">

**Comment by prertik** [comment]
One suggestion, I think can be done is, to create a `release` workflow for just creating the release and manually, trigger this when drafting a new release(which will automatically, publish to IntelliJ plugins), while the current canary releases can be done via `release-nightly` kind of workflow.

**Comment by KronicDeth** [comment]
They are being released onto the market place.  JetBrains is not releasing them from review.
