### ISSUE TITLE
Gutter doesn't show ExUnit run tests

### ISSUE THREAD

**Issue by delmendo** [KronicDeth/intellij-elixir#3223]
**Describe the bug**
This feature https://github.com/KronicDeth/intellij-elixir/pull/1807  seems to have disappeared in the new 2023.1.1

**To Reproduce**
Open a test file and try to click on the left gutter to run a test.

**Expected behavior**
I really liked having them in the gutter

**Screenshots**
v 2023.1.1
![image](https://github.com/KronicDeth/intellij-elixir/assets/138773/ba184f85-6dfa-4cc5-bbcf-169e931f2374)
v 2022.3.4
![image](https://github.com/KronicDeth/intellij-elixir/assets/138773/0daee05a-2c18-4dcf-95fc-b9e4a83ed011)

This is the same code, machine - but the top is with plugin 15 on 2023 and the bottom is plugin 14 on 2022  - THe little green arrows in the gutters are gone.

**Logs**
If reporting a hang or other performance issue, please attach the [thread dumps](https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond).

**Desktop:**
 - OS: Ubuntu 
 - Version 22.04

**Erlang:**
- Installer asdf
- Version 25.3

**Elixir:**
- Installer asdf
- Version  1.14.4-otp-25

**Plugin:**
- Version 15.0.1

**Comment by KronicDeth** [comment]
Likely caused by #3158

**Comment by KronicDeth** [comment]
The icons show up after #3158 was fixed.
