### ISSUE TITLE
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented at org.elixir_lang.psi.impl.PsiNamedElementImpl.setName(PsiNamedElementImpl.kt:71)

### ISSUE THREAD

**Issue by Satheesh-KM** [KronicDeth/intellij-elixir#3283]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Community Edition (2022.2.5)
Operating System: Windows 11 (10.0)

# Event

### Stacktrace

<details>

<summary>
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented
</summary>

```
kotlin.NotImplementedError: An operation is not implemented: Rename not implemented
	at org.elixir_lang.psi.impl.PsiNamedElementImpl.setName(PsiNamedElementImpl.kt:71)
	at org.elixir_lang.psi.impl.ElixirPsiImplUtil.setName(ElixirPsiImplUtil.java:1666)
	at org.elixir_lang.psi.impl.ElixirAliasImpl.setName(ElixirAliasImpl.java:77)
```

</details>

**Comment by KronicDeth** [comment]
13.2.1 was released in October 2022.  It is no longer supported and this bug report does not include enough information to reproduce the bug in newer versions.  Please upgrade to a newer version and see if your bug still exists there.
