### ISSUE TITLE
mix --version format changed for 1.3.0+

### ISSUE THREAD

**Issue by Nicholi** [KronicDeth/intellij-elixir#329]
When importing a Mix project or checking the "Elixir External Tools" settings the Version field is populated with: ```N/A: Error: ** (Mix) Cannot implicitly pass flags to default Mix task, please invoke instead "mix run"```

The path to mix is valid: ```/usr/local/bin/mix``` and I can run it with --version in my terminal no problem.

> $ /usr/local/bin/mix --version
> Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
> 
> Mix 1.3.0

Also you simply can't import the mix project unless you uncheck "Fetch dependencies". Compiling and running mix tasks doesn't seem to be a problem after the project is imported (haven't added any dependencies to see though).

I am running Ubuntu 16.04 with recommended repo installation of erlang and elixir. Both Elixir and Mix are version 1.3.0. IntelliJ is 2016.1.3. Plugin installed via JetBrains repository, version reported as 4.0.0.

**Comment by KronicDeth** [comment]
I think they changed how the mix command is wrapped again.  It seems to change with every version of Elixir, so it is really hard to get a machine parseable version out of it.  I can confirm I can reproduce this locally now that I'm on Elixir 1.3.0.

**Comment by alexandru-calinoiu** [comment]
Same here on a linux machine with elixir 1.3.0

**Comment by KronicDeth** [comment]
It looks like the change is that "Mix <version>" is no longer the first line.  In 1.3.0, they started printing the Erlang version header on the first line and "Mix <version>" is on the last line.

**Comment by n2o** [comment]
I am still having this issue with `mix 1.3.1`, `Elixir 1.3.1` and `intellij-elixir 4.0.0`

**Comment by KronicDeth** [comment]
@n2o you should still have the issue in 4.0.0.  It wasn't fixed in 4.0.0, it was reported against 4.0.0 and closed with a commit to master.  It will be in the v4.1.0 release.  If you would install [the canary build of v4.1.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/4.1.0-dev%2B20160712024727), you can confirm it works for your before v4.1.0 is officially released.

**Comment by n2o** [comment]
@KronicDeth thanks, works as expected!
