### ISSUE TITLE
New Project on Windows 10 shows error Internal Erlang SDK is not in Elixir SDK.  Set it before picking this Elixir SDK

### ISSUE THREAD

**Issue by paetztm** [KronicDeth/intellij-elixir#3313]
**Describe the bug**
On Windows 10, when trying to create a new project, Intellij IDEA Ultimate shows an error during the New Project flow saying:
Internal Erlang SDK is not in Elixir SDK.  Set it before picking this Elixir SDK

**To Reproduce**
1. File -> New -> Project
2. Enter valid Name, Location, Language (Elixir)
3. Click Elixir SDK dropdown and select Add Elixir SDK
4. Dialog pops up saying "Cannot Create SDK" title with description "You need to configure an Erlang SDK for Elixir SDK. Click OK to be taken through the Erlang SDK for Elixir SDK configuration. Click Cancel to stop configuring this SDK AND the Erlang SDK for Elixir SDK."
5. Click OK
6. Select C:\Program Files\Erlang OTP (installation directory for Erlang)
7. Click OK
8. Select C:\Program Files\Elixir
9. Click OK
10. Dialogs are dismissed
11. Click Create in the New Project Window
12. Elixir SDK is highlighted in red and an error pops up if you hover over it: Internal Erlang SDK is not in Elixir SDK.  Set it before picking this Elixir SDK

**Expected behavior**
When clicking Create, the new project is created

**Screenshots**
After selecting the Elixir and Erlang SDK:
![image](https://github.com/KronicDeth/intellij-elixir/assets/8438825/ea17db9c-6831-490b-af6d-6cebd7a451ae)

Error when hovering over Elixir SDK:
![image](https://github.com/KronicDeth/intellij-elixir/assets/8438825/61cb4f1e-2032-43e2-bde8-21f5f95824bb)

**Logs**
If reporting a hang or other performance issue, please attach the [thread dumps](https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond).

**Desktop:**
 - OS: Windows
 - Version 10

**Erlang:**
- Installer Prebuilt Windows 64 bit installer from https://www.erlang.org/downloads.html
- Version 26

**Elixir:**
- Installer Prebuilt Windows installer from https://elixir-lang.org/install.html#windows
- Version 1.15.2

**Plugin:**
- Version 15.1.0

**Additional context**
IntelliJ IDEA 2023.1.4 Ultimate Edition

**Comment by kuranai** [comment]
Hi @paetztm,
I had the same problem and could somehow get it working.
Try to open some folder/project so that you can open the full menu.
Then go to File -> Project Structure and add your SDKs there.
![image](https://github.com/KronicDeth/intellij-elixir/assets/90623/6f002f83-2007-4f8f-a6ed-2e40f7cc8b5c)
Maybe you can document the steps better than me 🤷‍♂️

**Comment by paetztm** [comment]
@kuranai Thanks for pointing me in the right direction.
First, I had to follow these steps to set up Erlang:
https://www.jetbrains.com/help/idea/erlang-start-project.html

Then within 
File -> Project Structure -> Platform Settings -> SDKs
I had to + and added Erlang for Elixir SDK
Then I had to + and added Elixir SDK and selected the Internal Erlang SDK

![image](https://github.com/KronicDeth/intellij-elixir/assets/8438825/01346a20-313f-476e-905f-fb372455b933)
