### ISSUE TITLE
JetBrains has incremented the build and I can no longer install the plugin

### ISSUE THREAD

**Issue by smashedtoatoms** [KronicDeth/intellij-elixir#3343]
**Describe the bug**
Plugin 'Elixir' (version '15.1.0') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62

**To Reproduce**
1. Install the latest IntelliJ.
2. Watch it complain because it broke existing functionality when it updated.

**Expected behavior**
I kind of expected this, but in a universe where JetBrains didn't force all plugin maintainers to be constantly updating their plugins to keep up with JetBrains rando changes, this plugin would have just kept on working after I updated.

**Logs**
Plugin 'Elixir' (version '15.1.0') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62

**Desktop:**
 - OS: macOS
 - Version 13.5.1

**Erlang:**
- Installer asdf-vm
- Version 26.0.2

**Elixir:**
- Installer asdf-vm
- Version 1.15.5

**Plugin:**
- Version 15.1.0

**Additional context**
I know this isn't you all's doing.  I maintain a really simple IntelliJ theme, and it is a time Vampire because JetBrains can't maintain backward compatibility with themselves.  I just wanted to get this opened in case you didn't already know.

**Comment by alexandergitter** [comment]
This has already been reported in #3325 and #3326.
There's a PR where someone provided a zip file with an updated version of the plugin: https://github.com/KronicDeth/intellij-elixir/pull/3327#issuecomment-1672963999
