### ISSUE TITLE
Elixir Plugin not supported in latest 2023.3 JetBrains IDEs

### ISSUE THREAD

**Issue by billylaing** [KronicDeth/intellij-elixir#3494]
**Describe the bug**
Elixir plugin does not appear in the latest JetBrains 2023.3.* IDEs since it is not supported.

**To Reproduce**
1. Go to Setting -> Plugins
2. Search for "Elixir"
3. Elixir plugin does not appear for the user to install

**Expected behavior**
The plugin should be available in 2023.3 IDEs.

**Desktop:**
 - OS: macOS
 - Version 14.2.1

**Plugin:**
- Version 16.0.0

**Comment by danielveleba** [comment]
The build failed: https://github.com/KronicDeth/intellij-elixir/actions/runs/7147009230/job/19465756149

**Comment by billylaing** [comment]
I used the canary build found [here](https://github.com/KronicDeth/intellij-elixir/releases/download/v16.0.1-pre%2B20231208222626/intellij-elixir-16.0.1-pre+20231208222626.zip) and loaded directly from disk to work around the issue. 

https://github.com/KronicDeth/intellij-elixir/releases/download/v16.0.1-pre%2B20231208222626/intellij-elixir-16.0.1-pre+20231208222626.zip

**Comment by szymon-jez** [comment]
A different workaround is to just disable the plugin in "Settings > Plugins > Installed > Elixir" and then reenable it and it will start working again.

**Comment by billylaing** [comment]
17.0 was released so I am closing this issue. Cheers
