### ISSUE TITLE
Lastest IntelliJ is not compatible with Elixir 17.0.0

### ISSUE THREAD

**Issue by port513** [KronicDeth/intellij-elixir#3620]
IntelliJ 2024.1.4 is not working with Elixir 17.0.0
Would be nice if this could be fixed ASAP

**Comment by joshuataylor** [comment]
KronicDeth, the maintainer is the one with access ATM, and their life is a bit busy atnm - I've emailed them to get this submitted dto JetBrains for review, then it's off to them to review.

For now, you can manually insta the zip file that the release has for 18.0.1 and it will work.

We're also working on getting an EAP and BETA channels setup so you can test them without manually installing on newer IDEs or for testing a minor release.

Typically:
Major = New version of IntelliJ, breaking change.
Minor = Something really big changed (rare)
Patch - Bug fixes.

Eg 18 is major
0 is minor
1 is patch

**Comment by bstime-tol** [comment]
> For now, you can manually insta the zip file that the release has for 18.0.1 and it will work.

@joshuataylor, it looks like the 18.0.1 release currently has only source artifacts attached--no pre-compiled binary .zip:

![image](https://github.com/user-attachments/assets/d5cd1f60-011b-4856-9083-07909ad2e5b8)

**Comment by joshuataylor** [comment]
🤦 

I'll get that sorted, I thought it would create a new release with the actual artifacts.

**Comment by joshuataylor** [comment]
Fixed
