### ISSUE TITLE
Typo in release notes for 18.0.1 – Does 18.0.1 work at all?

### ISSUE THREAD

**Issue by nkanellopoulos** [KronicDeth/intellij-elixir#3622]
Apparently the phrase "Drop support for <= 2024.2.4 IDEs" contains a typo since 2024.2 is not out yet.

Apart from this, I installed the plugin from source, and I think it is not functioning properly.
I click "Create new project" and nothing happens.
It seems to **break IntelliJ completely**. The "new project" popup does not appear at all.
If I uninstall the plugin, The "new project" functionality is restored.

**EDIT:**
Be sure to install the zip from disk, **not** the jar file from ./build/libs.
The zip is:
`./build/distributions/intellij-elixir-18.0.0-pre+20240804181153.zip`

My environment:
IntelliJ Ultimate 2024.1
macOS 14.6
Macbook Pro M1 Max, 32GB RAM

**Comment by joshuataylor** [comment]
What OS are you using?

We really need to get better at tracking errors, as a lot of the issues at the moment is that things get blocked by the EDT, basically you can't run things in the UI thread anymore.

I've been using the plugin for a few weeks with 2024.1, and have been testing it with 2024.2 as well.

Unfortunately there are quite a few times the EDT window is hit that blocks things like SDK adding etc, as these are slow.

**Comment by nkanellopoulos** [comment]
Sorry I forgot to mention these, I will edit the initial message.

**Comment by joshuataylor** [comment]
All good, I'm also going ask the JetBrains Platform Slack channel about a good way to report errors (it's obvious for these, it's the little red button at the bottom right of the screen that flashes annoyingingly), as grepping through logs is painful
The plugin has almost a decade worth of development, so random things will change that break others - figuring out the main pieces causing dramas is the priority right now .

Thanks for the report!

**Comment by nkanellopoulos** [comment]
@joshuataylor where could we have a short chat?

**Comment by joshuataylor** [comment]
I am on the Elixir Slack channel, I'll make sure my notifications is on. (Not a huge fan of Slack, though everyone uses it).

Also feel free to email me. I will also try and figure out a good way to provide logs when makin a bug report - user privacy is my #1 concern.

**Comment by nkanellopoulos** [comment]
Le me see if I still have Slack installed :D

**Comment by joshuataylor** [comment]
The web browser works well, just don't let it trick you into downloading the app. 🙃

My name on the Elixir Slack is joshx.
