### ISSUE TITLE
The 18.0 version is not listed in the JetBrains Market place

### ISSUE THREAD

**Issue by szymon-jez** [KronicDeth/intellij-elixir#3624]
The new version was released but is not listed in the JetBrains Market place https://plugins.jetbrains.com/plugin/7522-elixir/versions. The IDE does also not list the plugin when I search in it for "elixir":

![Screenshot 2024-08-05 at 10 05 08](https://github.com/user-attachments/assets/9e24cf96-6243-489d-abe9-80da6abd0adc)

<details>

<summary>Environment</summary>

```
IntelliJ IDEA 2024.1.4 (Community Edition)
Build #IC-241.18034.62, built on June 20, 2024
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
Kotlin: 241.18034.62-IJ
```

</details>

**Comment by joshuataylor** [comment]
We need KronicDeth to submit, and they're quite busy due to personal life ATM.

Then it has to go through the JetBrains plugin review process.

Right now you'll need to install the ZIP file manually, I'll see why it didn't generate new assets.

I'll also make a note about this.

**Comment by joshuataylor** [comment]
Didn't mean to close this, will keep it open until it's in.

**Comment by joshuataylor** [comment]
19.0.0 is now in, and all future releases will be immediately uploaded, and pending Jetbrains approval should be in within 2 business days. They're usually pretty quick!
