### ISSUE TITLE
Allow folding of alias, use, require to be disabled in Editor > General > Code Folding

### ISSUE THREAD

**Issue by drathier** [KronicDeth/intellij-elixir#368]
I'm unable to disable folding for import and use statements. All of the options under Settings -> Editor -> General -> Code Folding are disabled, but still, this fold happens.

```
use Thing
```
gets collapsed to
```
use ...
```
which really isn't helpful for me at all. Same thing with `import`, `alias` and `require`. Doesn't save space and forces me to click to see the text.

Please either add a configuration option, remove folding for `use`, `require`, `alias` and `import`, or let me know where this setting is :)

**Comment by KronicDeth** [comment]
There is no setting in Editor > General > Code Folding.  I'd have to look how to add one to there to turn it off permanently.

You can manually expand auto-folded regions in numerous ways:
* Click on the folded text
* Cmd++ on the folded line
* Clicking the + Square next to the line.

To expand everything in an editor tab, you can use Code > Folding menu.  You can either do Code > Folding > Expand All (Shift+Cmd++) or Code > Folding > Expand Recursively (Alt+CMD++).

**Comment by smeevil** [comment]
+1 not folding use, alias, require and import by default would be good

**Comment by smeevil** [comment]
Ok, I'm fine either way as long as it's configurable :) currently I catch myself always unfolding them when looking at a file to get the bigger picture.

**Comment by drathier** [comment]
The difference is that in Java, folding saves lines of code, and you never really look at the imports in Java. In Elixir, I look at the imports quite often, and the folds are only saving a few characters of space. It doesn't save any lines, which is where folding really is useful. I vote for making these unfolded by default, but either way, it should be configurable.

**Comment by KronicDeth** [comment]
The Extension Point to add new options to that menu is called [`codeFoldingOptionsProvider`](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/application/options/editor/CodeFoldingOptionsProviderEP.java)
