### ISSUE TITLE
Incorrectly adding matched end for one-liners

### ISSUE THREAD

**Issue by smeevil** [KronicDeth/intellij-elixir#376]
The new pair matching works really well and helps a lot :)

I did notice one case where it's to eager though, which is : 
def my_func, do:  end

It will add the matching `end` of the `do` here when it should not

**Comment by KronicDeth** [comment]
I think this is because I'm asking if the last character is space and the preceding token is `DO` and it so happens that with the lexer, it is `DO` for both `def foo do ` and `def foo, do: `.  I probably need to make the check stronger than just is the last token `DO`.
