### ISSUE TITLE
Redirects with CMD+B, ... not works for aliased modules

### ISSUE THREAD

**Issue by merqlove** [KronicDeth/intellij-elixir#377]
Example code:
https://gist.github.com/merqlove/9787f2116283d276ef14a7c1ad1df37d

**Comment by KronicDeth** [comment]
It's not a bug.  It's a feature that's not implemented yet.  I don't see an open issue for it though, so I guess before now, it was just in my head, so we'll use this for it.

**Comment by KronicDeth** [comment]
@andshape wanted alias references [in](https://github.com/KronicDeth/intellij-elixir/issues/307#issuecomment-219944051) #307 too

**Comment by merqlove** [comment]
Yep, found this feature working in the VS Code Elixir module. 
https://github.com/mat-mcloughlin/vscode-elixir
Seems they used Alchemist for Go-To definition and so on.
