### ISSUE TITLE
Using `nil` as a key in a map or a keyword list causes error, breaks syntax highlighting

### ISSUE THREAD

**Issue by robertpeacock22** [KronicDeth/intellij-elixir#494]
Elixir plugin v4.5.0
IntelliJ IDEA Community v2016.2.5

When using a map or a keyword list as a module attribute and using `nil` as a key...

```
@test_attribute %{nil: "test"}
```

...there is an error on `@test_attribute` that says "Unresolved module attribute"
There is also an error on the map itself that says the following (had to screenshot since you can't copy tooltip text in IntelliJ):
![screen shot 2016-11-07 at 4 58 24 pm](https://cloud.githubusercontent.com/assets/608951/20077718/819a62ac-a50b-11e6-9697-0ebf7d693e3e.png)

When the map or keyword list is not a module attribute (e.g. within a function) only the latter error happens.

In both cases, they are (incorrectly) marked as errors and syntax highlighting is broken from that point in the code onward.

**Comment by KronicDeth** [comment]
Confirms this breaks parsing [`IEx.Config.default_colors/1`](https://github.com/elixir-lang/elixir/blob/v1.4.0/lib/iex/lib/iex/config.ex#L84) in Elixir `v1.4.0`.

**Comment by KronicDeth** [comment]
`NIL` already jumps to `KEYWORD_PAIR_MAYBE`, so the lexer is expecting `nil` can be a keyword key:

```
 {NIL}                                      { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.NIL; }
```
-- https://github.com/KronicDeth/intellij-elixir/blob/v4.7.0/src/org/elixir_lang/Elixir.flex#L660-L661

**Comment by KronicDeth** [comment]
`NIL` is missing from `keywordKey` in the parser grammar:

```

keywordKey ::= AFTER |
               ALIAS_TOKEN |
               AND_OPERATOR |
               ARROW_OPERATOR |
               ASSOCIATION_OPERATOR |
               AT_OPERATOR |
               BIT_STRING_OPERATOR |
               CAPTURE_OPERATOR |
               CATCH |
               COMPARISON_OPERATOR |
               DO |
               DUAL_OPERATOR |
               ELSE |
               IDENTIFIER_TOKEN |
               IN_MATCH_OPERATOR |
               IN_OPERATOR |
               MAP_OPERATOR |
               MATCH_OPERATOR |
               MULTIPLICATION_OPERATOR |
               OR_OPERATOR |
               PIPE_OPERATOR |
               RESCUE |
               RELATIONAL_OPERATOR |
               STAB_OPERATOR |
               STRUCT_OPERATOR |
               TUPLE_OPERATOR |
               TWO_OPERATOR |
               UNARY_OPERATOR |
               WHEN_OPERATOR |
               quote
```
- - https://github.com/KronicDeth/intellij-elixir/blob/v4.7.0/src/org/elixir_lang/Elixir.bnf#L2942-L2971
