### ISSUE TITLE
Congrats on v4.7.0 Release

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#553]
I don't really know how to contact you outside of Github, so sorry for the extraneous issue, but I just want to know your hard work is appreciated out there.

**Comment by NobbZ** [comment]
There is a number of ways. His email address should be in the gut history,
he uses twitter and is a member of the elixirforum.com.

These 3 are the most obvious.

Also at the end of the README there is a donation button hidden 😃

Ryan Scheel <notifications@github.com> schrieb am Di., 6. Dez. 2016, 11:12:

**Comment by KronicDeth** [comment]
My email is also listed in my github profile, https://github.com/KronicDeth.  But, I'm fine with opening issues, then people can pile on with public support.  I'll leave the issue open for a bit.
