### ISSUE TITLE
Compilations errors do not mark entire test run as failed

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#560]
![](http://i.imgur.com/855imov.png)

A compile error in a test file causes Elixir to abort the test, but the Mix ExUnit task thinks everything succeeded.

**Comment by KronicDeth** [comment]
I can replicate, as long as I test more than one file in run by adding `raise "BOOM"` to the body of any test `.exs` in C-S-D/alembic.

**Comment by KronicDeth** [comment]
I've been able to make it show an indicator when there's an error, but only if the OK (green circle) button to show successful results is only.  The indicator is the red ! in the lower-left corner.  Unfortunately, it's completely passed on parsing strings from stderr.

![screen shot 2017-07-11 at 4 50 16 pm](https://user-images.githubusercontent.com/298259/28092528-53f95118-6659-11e7-86ba-ac792e5a258e.png)

**Comment by KronicDeth** [comment]
If I make the exceptions into a `testFailed` message, it shows both failure and then properly shows the overall run as Terminated

![screen shot 2017-07-11 at 10 00 47 pm](https://user-images.githubusercontent.com/298259/28099841-70c7e626-6684-11e7-998d-8a890481eb82.png)

**Comment by KronicDeth** [comment]
Figured out how to parse the path to fake to module name, so they appear as test failures now.  Video attached to [tweet](https://twitter.com/KronicDeth/status/885263354239102976)
