### ISSUE TITLE
Restrict test/mix generators for Elixir projects only

### ISSUE THREAD

**Issue by merqlove** [KronicDeth/intellij-elixir#562]
The new generators menu should be hidden in non elixir projects.

Currently i see it in anyone opened project.
Example from Rails project.

![screenshot 2016-12-12 12 41 13](https://cloud.githubusercontent.com/assets/18354/21094557/89ae4530-c068-11e6-9604-47b8fa48af42.png)

**Comment by KronicDeth** [comment]
Maybe it's a subtle hint that you should convert the project to Elixir 😁 .  I should be able to detect the language of the Module or Project of the directory, so it doesn't show up unless Elixir.

**Comment by merqlove** [comment]
No, it's more than one project :)) Try someone rubymine project with Rspec tests :)

**Comment by merqlove** [comment]
I think i haven't seen this bug before 4.6.0

**Comment by KronicDeth** [comment]
It would only be in 4.7.0.  That's the first with Run Configuration from Context support.
