### ISSUE TITLE
Link to file goes to wrong file when multiple files share same filenames

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#564]
I have a convention in my code that when I have a directory the same name as a module (when it has submodules), I name the module as `mod.ex` in that directory. So I have a lot of files that are named `mod.ex`. When clicking on a link to a file, e.g. `lib/gald/screen/test/mod.ex:20` it will go instead to a different file e.g. `lib/gald/player/mod.ex:20`.

**Comment by KronicDeth** [comment]
There was an old bug like this that I fixed, but I have noticed a similar problem since then.  I had assumed it was related to the files being cross-module in an umbrella project where each OTP app is a module, but that can't be the case in your example.

**Comment by KronicDeth** [comment]
Note to self: `src/org/elixir_lang/console/FileReferenceFilter.java` is the file that does the linking.  I always forget that and can't find it because I look for "link" or "stacktrace".

**Comment by Havvy** [comment]
<3
