### ISSUE TITLE
Highlight elixir code injected into template

### ISSUE THREAD

**Issue by Lukom** [KronicDeth/intellij-elixir#565]
Currently I have no highlighting of elixir code in templates.

This is an example of `*.eex` file threated as HTML in the latest Intellij Idea:
<img width="608" alt="app_html_eex_-_hello_-____my_projects_hello_" src="https://cloud.githubusercontent.com/assets/187657/21241795/061c9348-c31a-11e6-8c17-6adc104fb248.png">

This is an example of `*.slim` file in Intellij Idea:
<img width="655" alt="article_html_slim_-_lb_wiki_-____projects_lb_wiki_" src="https://cloud.githubusercontent.com/assets/187657/21241823/2a1d642a-c31a-11e6-9e0b-dc649739fc12.png">

This is an example of `*.slim` file in the latest Rubymine with Elixir plugin:
<img width="644" alt="article_html_slim_-_lb_wiki_-____projects_lb_wiki_" src="https://cloud.githubusercontent.com/assets/187657/21241847/48180b60-c31a-11e6-8e1e-bb81118e6cb0.png">

**Comment by KronicDeth** [comment]
That format is called `EEx`.  There is already a feature request open for that, #186.  Please upvote that by adding a 👍  to the description.
