### ISSUE TITLE
Configurable Code Folding for module attributes

### ISSUE THREAD

**Issue by artemrizhov** [KronicDeth/intellij-elixir#567]
It displays the module attribute values instead of `@name`. This constantly makes me confused. Is it possible to disable this feature? I can fork if needed, just please tell me what code should be commented out.

**Comment by KronicDeth** [comment]
That's part of code folding, but unlike Elixir module directive there's not a check box to control the configuration of it right now.  You can turn it off in a file by unfolding everything

![screen shot 2016-12-19 at 5 43 50 pm](https://cloud.githubusercontent.com/assets/298259/21333096/c537b65e-c612-11e6-9d2a-364969ccc1ea.png)

The PR to allow directives to be configured was https://github.com/KronicDeth/intellij-elixir/pull/403, so you can base a PR to allow module attribute code folding on that.

Module attribute usage folding to value is done by https://github.com/KronicDeth/intellij-elixir/blob/627b8ad95512b4b6811ded266f3a5041fe2cd885/src/org/elixir_lang/folding/Builder.java#L295-L323

**Comment by artemrizhov** [comment]
Thanks a lot!

**Comment by artemrizhov** [comment]
Unfortunately I have not achieved any success with configuring of all those paths and libraries in IDEA because of absence of experience in Java.  :disappointed: 

It would be nice if you can disable that code and build this for me and possible for others who want to disable this annoying folding.
