### ISSUE TITLE
`do:` in Color & Fonts preview is highlighted as Keyword instead of Atom

### ISSUE THREAD

**Issue by judgedim** [KronicDeth/intellij-elixir#573]
**do:** has incorrect highlighting  
![selection_600](https://cloud.githubusercontent.com/assets/3140807/21523684/12b559ce-cd19-11e6-8c5a-187eec8278e0.png)

**Comment by KronicDeth** [comment]
This is how it looks for me in 4.7.0.

![screen shot 2016-12-28 at 10 46 30 am](https://cloud.githubusercontent.com/assets/298259/21526621/125a0c96-cceb-11e6-855f-6e7cf4a2c257.png)

The colors in the preview aren't applied by the real annotators, but manually using xml tags.  (I assume it's a speed thing or so there's not a chance of annotator exceptions in the settings page.)  The orange `do` plus `:` should be colored purple, the Atom color as you can see in my above screenshot, so it's a bug in the preview text.

I'm not sure why the `do:` in your source isn't colored as an atom although, the annotator for the module attributes hasn't shown up in your code either, so `@greeting` is not purplish either.

Do you have an errors reported in the bottom right corner?  Certain exceptions could stop the annotators from running leaving the partial highlight you're showing.

**Comment by judgedim** [comment]
no, I don't have any errors

By the way, why `do:` should be colored purple ? I expected orange :)

**Comment by KronicDeth** [comment]
Because when `do` is used as a JSON style atom, `do:`, it's an Atom, not a keyword.
