### ISSUE TITLE
syntax highlighting: predefined vs  macro call

### ISSUE THREAD

**Issue by mbriggs** [KronicDeth/intellij-elixir#578]
Given

```elixir
defmodule Foo do
  def get_products(store, opts \\ %{}) do
    get(store, "products.json")
  end

  defp query(path, params) when params == [], do: path
  defp query(path, params) when params == %{}, do: path
  defp query(path, params), do: "#{path}?#{URI.encode_query(params)}"
end
```

I am getting

![image](https://cloud.githubusercontent.com/assets/89260/21593811/46326b88-d0e9-11e6-8fb1-cedfc455b172.png)

1. Configure `Calls -> Predefined`  to Teal
2. Configure `Calls -> Macro` to Read

The issue is that the middle `defp query` goes from predefined call style to macro call style.

When I remove the def, stuff gets highlighted correctly

![image](https://cloud.githubusercontent.com/assets/89260/21593835/9dcb324e-d0e9-11e6-89c3-d78039b6de02.png)

**Comment by KronicDeth** [comment]
I think it may have to do with guards (`when ...`) on the no parentheses calls since that's a different element in the grammar.  There are other bugs with similar example code.

**Comment by KronicDeth** [comment]
## [v4.7.0](https://github.com/KronicDeth/intellij-elixir/tree/v4.7.0)

<img width="505" alt="screen shot 2017-03-11 at 10 44 21 am" src="https://cloud.githubusercontent.com/assets/298259/23825925/bdcd956c-0647-11e7-9d64-a5fadbb25e80.png">

## `master@`https://github.com/KronicDeth/intellij-elixir/commit/627b8ad95512b4b6811ded266f3a5041fe2cd885

<img width="507" alt="screen shot 2017-03-11 at 11 46 44 am" src="https://cloud.githubusercontent.com/assets/298259/23826414/72738af0-0650-11e7-8a1d-6f9136729205.png">

So... that's fun.
