### ISSUE TITLE
Syntax: getting confused about double quote balancing

### ISSUE THREAD

**Issue by mbriggs** [KronicDeth/intellij-elixir#582]
version 4.7

I tried to simplify this more, but couldnt figure out what element was actually causing it. so hunk of code from an app. Seems to be a weird corner case, but figured i would log anyways

```elixir
defmodule Foo do
  defp wrap_url_for(key) when Mix.env == "dev" do
    "http://localhost:4000/#{Wrap.url({nil, key}, :original)}"
  end
end
```

I had the inner string quotes unbalanced, when I try to close the double quote, it autopairs it for me, but considers it balanced. I backspace the end pair, and that makes it treat it as unbalanced, even though it is. In that state, when I do something to force quote re-evaluation (i think thats what im doing), like deleting the when clause, it treats it as balanced again.

note that its not the when clause doing it. i can just delete one of the double quotes on the when, re-add, and its good again

![weirdness](https://cloud.githubusercontent.com/assets/89260/21724445/5f060bc6-d402-11e6-9dda-3609a0ac4141.gif)

**Comment by KronicDeth** [comment]
There are some mechanisms to tell the API to reparse in a certain range.  I guess I have to figure out a heuristic for the range so it works in this case.
