### ISSUE TITLE
No feedback setting up Elixir SDK

### ISSUE THREAD

**Issue by yordis** [KronicDeth/intellij-elixir#586]
@KronicDeth from the conversation on the Elixir Channel. I was setting up the Elixir SDK and didn't give me any feedback about the paths.

I used `/bin` file and nothing happen, just keep saying to setup the SDK.

**Comment by nulian** [comment]
I had the problem it said can't find elixir had to hardcode the environment path in intellij before it worked.

**Comment by KronicDeth** [comment]
It looks like I may be able to override the message by throwing my own exception as the code in `intellij-community` indicates a bad directory and set the message in a thrown exception:

> ```java
>   private static FileChooserDescriptor createCompositeDescriptor(final SdkType... sdkTypes) {
>     return new FileChooserDescriptor(sdkTypes[0].getHomeChooserDescriptor()) {
>       @Override
>       public void validateSelectedFiles(final VirtualFile[] files) throws Exception {
>         if (files.length > 0) {
>           for (SdkType type : sdkTypes) {
>             if (type.isValidSdkHome(files[0].getPath())) {
>               return;
>             }
>           }
>         }
>         String key = files.length > 0 && files[0].isDirectory() ? "sdk.configure.home.invalid.error" : "sdk.configure.home.file.invalid.error";
>         throw new Exception(ProjectBundle.message(key, sdkTypes[0].getPresentableName()));
>       }
>     };
> ```
> -- https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/openapi/projectRoots/impl/SdkConfigurationUtil.java?utf8=%E2%9C%93#L115-L130
