### ISSUE TITLE
StackOverflow in an empty project with Elixir 1.4 source code attached

### ISSUE THREAD

**Issue by develop7** [KronicDeth/intellij-elixir#598]
Repro:

1. Having Elixir 1.4 installed and registered as an SDK, download Elixir 1.4 source code, unpack it somewhere and attach its' `lib` directory as only "sourcepath" (removing other entries like `/usr/lib/elixir/lib` etc.) in Elixir SDK settings
2. Create new project with `mix new einprojekt`
3. Import it from Mix, adding above SDK as project SDK
4. Open `mix.exs`
5. Put caret on `Mix.Project` occurrence and navigate to its' source

Expected: file is properly highlighted and no unhandled `StackOverflow` exceptions

Instead: 
*   syntax highlighting is buggy — 
    * `defmodule` in L1 isn't highlighted properly
    * L19 & 20 aren't too
*   Multiple unhandled `StackOverflows` (see stacktraces in #589) 

![image](https://cloud.githubusercontent.com/assets/89889/22217583/9aaa9b0a-e1b4-11e6-829d-1f06f6e61d86.png)

**Comment by elvanja** [comment]
Having same `StackOverflows` with Elixir 1.3.4.
Elixir installed via https://github.com/mururu/exenv and set as projects SDK.
Using IntelliJ IDEA 2016.3.4:
- Build #IU-163.12024.16, built on January 31, 2017
- JRE: 1.8.0_112-release-408-b6 x86_64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Let me know if you need any other details.
Thank you for the plugin!

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/commit/93e3c3d80a14ed647428e793b1689bcc3f47b2ac may have fixed this.  Wait until the next release to test it out.

**Comment by develop7** [comment]
@KronicDeth thanks for quick fix! Can't really wait to test it, is there a nightly build around?

**Comment by KronicDeth** [comment]
@develop7 sorry, no automated nightlies yet and I've been holding off on a cutting a build because there are performance issues with bare words completions now that they can see all the standard library functions/macro.  I won't cut a build until I fix that issue.

**Comment by KronicDeth** [comment]
@develop7, 5.0.0 is out.  Please update and let me know if you still see this error.

**Comment by elvanja** [comment]
Been using it for last 24 hours, no errors at all. 👍

**Comment by develop7** [comment]
@KronicDeth the exception is certainly gone, but built-in macros are highlighted with wrong color. Should I report separate issue?

**Comment by KronicDeth** [comment]
@develop7 yes, always open new issue as new github issues.  I'm closing this as fixed.
