### ISSUE TITLE
Find usages does not work for functions

### ISSUE THREAD

**Issue by Lokeh** [KronicDeth/intellij-elixir#602]
When I `CMD+Click` on a private function (`defp some_fn ...`), it brings up "No usages found in project files," despite using the function inside the module.

Likewise, when `CMD+Clicking` on a public function used in another file (referenced as `MyModule.public_fn`), it also is unable to find any usages.

**Comment by KronicDeth** [comment]
I think it has something to do with the way "words" are generated from the files.  Find Usage depends on the names appear in the word list generated from each file before references are even checked.

**Comment by KronicDeth** [comment]
Find usage has never work, so I'm counting this as a blend of bug and enhancement.

**Comment by KronicDeth** [comment]
I may need to implement a [ReferenceSearcher](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000515030/comments/115000483664)

**Comment by KronicDeth** [comment]
Find Usage for functions was added in [7.5.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v7.5.0), which was released on 2018-06-03.  Sorry for not updating this bug @Lokeh.
