### ISSUE TITLE
Mix path is not quoted correctly on Windows

### ISSUE THREAD

**Issue by HangingClowns** [KronicDeth/intellij-elixir#603]
```
"C:\Program Files (x86)\Elixir\bin\elixir.bat" -r C:\Users\allenw\AppData\Local\Temp\intellij_elixir_modules2\team_city_ex_unit_formatter.ex -r C:\Users\allenw\AppData\Local\Temp\intellij_elixir_modules2\test_with_formatter.ex "C:\Program Files (x86)\Elixir\bin\mix" test_with_formatter --formatter TeamCityExUnitFormatter ""
Testing started at 4:05 AM ...
\Elixir\bin\mix was unexpected at this time.
```

**Comment by vhiroki** [comment]
+1

**Comment by KronicDeth** [comment]
@HangingClowns, @vhiroki are you able to manually change the mix path and set it to the space-less DOS 8.3 name for "Program Files (x86)", `PROGRA~1` and have it work?  Just to confirm it is the quoting of spaces that is not working.

**Comment by vhiroki** [comment]
@KronicDeth, yes. It's worked. Thank you!

**Comment by HangingClowns** [comment]
Okay, for those of you who don't know how to change your mix path:

File > Settings > Other Settings > Elixir External Tools

**Comment by KronicDeth** [comment]
@HangingClowns you didn't have to close the issue, it's still a bug that the spaces aren't being quoted correctly.  `PROGRA~1` is just a work-around

**Comment by stefanjarina** [comment]
For windows 10 x64 you can use `%ProgramFiles(x86)%` (note the trailing percent sign) if Elixir is nstalled as 32bit.

**Comment by KronicDeth** [comment]
The entire mix path is quoted, but quoting the entire mix path does not work for the argument even though it works for exe path (elixir's path).  This seems to be just how Windows quoting works because it gives the same error in `cmd.exe`.  I'm going to try using the `%...%` variables and see if they pass through `GeneralCommandLine` cleanly since adding my own quotes didn't work.

**Comment by KronicDeth** [comment]
Using `%ProgramFiles(x86)%` still gets the same error, so those variables are expanded too early

**Comment by KronicDeth** [comment]
Opened https://github.com/elixir-lang/elixir/issues/6455 as I don't think `elixir.bat` should have this quoting problem, but I have a work-around too to close this bug.
