### ISSUE TITLE
Credo integration

### ISSUE THREAD

**Issue by relwell** [KronicDeth/intellij-elixir#608]
Is there a plan to make it easier to use [Credo](https://github.com/rrrene/credo) as a tool for inspections?

**Comment by KronicDeth** [comment]
I had planned to add support for calling credo as an external annotation contributor, but never opened an issue, so this will be it.

**Comment by svarlet** [comment]
Hello there,
Some people in my team would also like this feature so +1!
Have you started to work on it? Do you know a temporary work around to get credo results inside intellij?
