### ISSUE TITLE
Map render lag's

### ISSUE THREAD

**Issue by merqlove** [KronicDeth/intellij-elixir#619]
Any IDE (RubyMine, IDEA)

![screenshot 2017-02-15 23 27 28](https://cloud.githubusercontent.com/assets/18354/22994057/5ecd2880-f3d6-11e6-9a17-04fd52cc1797.png)

```elixir
defmodule InFactApi.Actors.ModelPreparePipeline do
  use ExActor.GenServer, export: :model_prepare_server

  alias InFactApi.TaskLogger, as: Logger
  use InFactApi.Actors.Statuses, statuses: %{
    prepare_initial: -1,
    prepare_parse_error: 0,
    prepare_parsed: 1,
    prepare_error: 10,
    prepare_fetching: 11,
    prepare_waiting: 12,
    prepare_prepared: 13,
    prepare_query_gen_error: 20,
    prepare_success: 21
  }, error_statuses: [0, 10, 20]
end
```

**Comment by KronicDeth** [comment]
Thanks for including the code in the description, so I don't have to transcribe it from the screenshot.

**Comment by KronicDeth** [comment]
```
defmodule InFactApi.Actors.ModelPreparePipeline do
  use ExActor.GenServer, export: :model_prepare_server

  alias InFactApi.TaskLogger, as: Logger
  use InFactApi.Actors.Statuses, statuses: %{
    prepare_initial: -1,
    prepare_parse_error: 0,
    prepare_parsed: 1,
    prepare_error: 10,
    prepare_fetching: 11,
    prepare_waiting: 12,
    prepare_prepared: 13,
    prepare_query_gen_error: 20,
    prepare_success: 21
  }, error_statuses: [0, 10, 20]
end
```

renders as

![screen shot 2017-02-22 at 10 01 29 pm](https://cloud.githubusercontent.com/assets/298259/23244400/84958b24-f94a-11e6-9df2-524cf1b03f65.png)

in a scratch tab for me.  The golden color applied to the `0,` and `ching` part of `prepare_fetching` is used for types and specs.  Do you have one later in the file?

**Comment by KronicDeth** [comment]
The golden color is definitely #626.  Marking as a duplicate.
