### ISSUE TITLE
How to get Suggestion or Intellisense   

### ISSUE THREAD

**Issue by aliabbas-2012** [KronicDeth/intellij-elixir#648]
Hello , I am using the above plugin ,  but I am not getting any Suggestion or Intellisense from the built in elixer api , if you can tell me the steps to do that

**Comment by KronicDeth** [comment]
This is not a very detailed bug report.  The first thing that jumps to mind is that you don't have your Elixir SDK setup in the project, so it can't decompile the .beam files to complete modules and their functions from the SDK.  Make sure you follow the [Import project from external model](https://github.com/KronicDeth/intellij-elixir#import-project-from-external-model) steps when opening your project and that your SDK is set.

**Comment by KronicDeth** [comment]
No feedback in a month.  Closing.  Leave a comment and I'll reopen
