### ISSUE TITLE
Broken highlighting when using sigils in arguments

### ISSUE THREAD

**Issue by feymartynov** [KronicDeth/intellij-elixir#674]
Version: 5.1.0

![screen shot 2017-04-24 at 08 59 11](https://cloud.githubusercontent.com/assets/1500700/25324084/57f35c0c-28cc-11e7-97a1-5b5a6c55b3f6.png)

```elixir
def test(~s'"' <> value) do
  {:ok, value}
end
```

**Comment by KronicDeth** [comment]
The lexer is treating `'"'` as a heredoc promoter.  I need to figure out why it's mixing the two quote types in the regex.

**Comment by KronicDeth** [comment]
🤦‍♂️

> ```
> SIGIL_HEREDOC_PROMOTER = ({SIGIL_DOUBLE_QUOTES_PROMOTER}|>
> {SIGIL_SINGLE_QUOTES_PROMOTER}){3}
> SIGIL_HEREDOC_TERMINATOR = ({SIGIL_DOUBLE_QUOTES_TERMINATOR}|>
> {SIGIL_SINGLE_QUOTES_TERMINATOR}){3}
> ```
> -- https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/src/org/elixir_lang/Elixir.flex?utf8=%E2%9C%93#L524-L525

The `|` is inside group that is then `{3}`'d, so it allows either `'` or `"` in groups of three.  This is only applies to the sigils.  It's correct for normal string and charlist heredocs:

> ```
> CHAR_LIST_HEREDOC_PROMOTER = {CHAR_LIST_PROMOTER}{3}
> CHAR_LIST_HEREDOC_TERMINATOR = {CHAR_LIST_TERMINATOR}{3}
> 
> STRING_HEREDOC_PROMOTER = {STRING_PROMOTER}{3}
> STRING_HEREDOC_TERMINATOR = {STRING_TERMINATOR}{3}
>
> QUOTE_HEREDOC_PROMOTER = {CHAR_LIST_HEREDOC_PROMOTER} | {STRING_HEREDOC_PROMOTER}
> QUOTE_HEREDOC_TERMINATOR = {CHAR_LIST_HEREDOC_TERMINATOR} | {STRING_HEREDOC_TERMINATOR}
> ```
> -- https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/src/org/elixir_lang/Elixir.flex?utf8=%E2%9C%93#L441-L448
