### ISSUE TITLE
no match of right hand side value: {:error, :on_load_failure}

### ISSUE THREAD

**Issue by hopewise** [KronicDeth/intellij-elixir#681]
I have installed this plugin, when I debug, I get this error:

```
/usr/local/Cellar/elixir/1.4.1/bin/elixir -pa /private/var/folders/m4/b74csk195j1f1x4vdpp6m6x80000gp/T/intellij_elixir_debugger3.tmp /usr/local/bin/mix intellij_elixir.debug_task --debugger-port 52151 -- ""

** (MatchError) no match of right hand side value: {:error, :on_load_failure}
18:03:23.955 [warn]  The on_load function for module lz4 returned {:error, {:upgrade, 'Upgrade not supported by this NIF library.'}}
    int.erl:531: anonymous fn/3 in :int.load/2

    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    lib/debug_task.ex:17: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

Any idea?

**Comment by hopewise** [comment]
I trired to remove _build folder, and rebuild again:

    rm -rf _build

but that did not solve the problem, please help :)

**Comment by KronicDeth** [comment]
From your original stacktrace, `lib/debug_task.ex:17`:

> ```elixir
> interpret_modules_in(Mix.Project.build_path)
> ```
> -- https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/resources/debugger/lib/debug_task.ex#L17

which calls

> ```elixir
> defp interpret_modules_in(path) do
>    path
>    |> Path.join("**/*.beam")
>    |> Path.wildcard
>    |> Enum.map(&(Path.basename(&1, ".beam") |> String.to_atom))
>    |> Enum.filter(&(:int.interpretable(&1) == true && !:code.is_sticky(&1) && &1 != __MODULE__))
>    |> Enum.each(&(:int.ni(&1)))
>  end
> ```
> -- https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/resources/debugger/lib/debug_task.ex#L58-L65

The ` (elixir) lib/enum.ex:645: Enum.each/2` is probably `|> Enum.each(&(:int.ni(&1)))`, so some `.beam` file you have say it's interpretable and not sticky (because ` |> Enum.filter(&(:int.interpretable(&1) == true && !:code.is_sticky(&1) && &1 != __MODULE__))` passed), but it's not actually safe to call `:int.ni` on it.

We can change the pipeline to wrap each `:int.ni/1` call, so we can report better errors.

For now, to figure out which module is causing the problem, can you give me a list of your dependencies.  Most importantly, we're looking for anyones that define NIFs.  It may be that the NIF modules are not properly setting that they're not interpretable (assuming that's a thing NIFs can do)

**Comment by hopewise** [comment]
Here is my dependencies:

```
defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, ">= 3.2.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:ex_aws, "> 1.0.0"},
     {:sweet_xml, "~> 0.5"},
     {:poison, "~> 2.0"},
     {:httpoison, "~> 0.9.0"},
     {:joken, ">= 1.3.2"},
     {:edeliver, "~> 1.4.0"},
     {:distillery, ">= 0.8.0", warn_missing: false},
     {:exrm, "~> 1.0.3"},
     {:cqex, "~> 0.2.0"},
     {:nimble_csv, "~> 0.1.0"},
     {:cqerl, github: "matehat/cqerl"},
     {:uuid, "~> 1.1", override: true},
     {:logger_file_backend, ">= 0.0.9"},
     {:cors_plug, "~> 1.2"},
     {:timex, "~> 3.0"},
     {:guardian, "~> 0.14"},
     {:apartmentex, git: "https://github.com/freiden/apartmentex.git"},
     {:remote_monitor, "~> 0.1.0", only: :dev}]
  end
```
Can you tell which dependency makes the problem?

**Comment by hopewise** [comment]
Any update?

**Comment by KronicDeth** [comment]
No, I'm working on the formatter now for #98.

**Comment by hopewise** [comment]
But, I can't debug now 😢

**Comment by KronicDeth** [comment]
There's only one me and I do this at night.  The code with the bugs is Elixir code (links in https://github.com/KronicDeth/intellij-elixir/issues/681#issuecomment-297888961) though, so you might be able to fix it yourself and PR it back.

**Comment by hopewise** [comment]
Thanks, but I am a newcomer to Elixir, I think this an advanced feature to work on?

**Comment by KronicDeth** [comment]
@hopewise when then version is released, it will contain #717, which added support for `INTELLIJ_ELIXIR_DEBUG_BLACKLIST` environment variable, which you can set in your Run Configuration to not interpreter `lz4`.  Let me know if it's still a problem after release.

**Comment by hopewise** [comment]
@KronicDeth Thanks, I have used the env var `INTELLIJ_ELIXIR_DEBUG_BLACKLIST ` to exclude `lz4 ` now, I get different error:

```
16:48:36.901 [warn]  The on_load function for module re2 returned:
{:error, {:upgrade, 'Upgrade not supported by this NIF library.'}}

** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    int.erl:531: anonymous fn/3 in :int.load/2
    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    /private/var/folders/m4/b74csk195j1f1x4vdpp6m6x80000gp/T/intellij_elixir/debugger/lib/debug_task.ex:19: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

**Comment by hopewise** [comment]
I am still having an error:

```
17:45:29.885 [warn]  The on_load function for module lz4 returned:
{:error, {:upgrade, 'Upgrade not supported by this NIF library.'}}

** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    int.erl:531: anonymous fn/3 in :int.load/2
    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:678: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:678: Enum.each/2
    /private/var/folders/m4/b74csk195j1f1x4vdpp6m6x80000gp/T/intellij_elixir740/debugger/lib/debug_task.ex:19: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

I have set `re2, lz4` as the value of `INTELLIJ_ELIXIR_DEBUG_BLACKLIS`
