### ISSUE TITLE
What is the "extension point" that IntelliJ has but derived IDEs lack?

### ISSUE THREAD

**Issue by gkoller** [KronicDeth/intellij-elixir#682]
In: https://github.com/KronicDeth/intellij-elixir#project you write that 

> NOTE: This feature only works in IntelliJ IDEA as it depends on an extension point unavailable in language-specific IDEs, like Rubymine.

Could you provide a little bit more detail regarding this extension point (eg. the name) so that I can update my bug report/feature request with Jetbrains: https://youtrack.jetbrains.com/issue/PY-23672

**Comment by KronicDeth** [comment]
intellij-community in its source refers to IntelliJ IDEA as a Rich IDE while the language-specific stuff IDEs is referred to as "Small IDEs".  The extension points common to both are used in the base [`plugin.xml` extensions](https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/resources/META-INF/plugin.xml#L2389-L2500) while those that are only available from Rich IDEs are in the [`rich-platform-plugin.xml` extensions](https://github.com/KronicDeth/intellij-elixir/blob/v5.1.0/resources/META-INF/rich-platform-plugin.xml#L6-L24):

```xml
 <extensions defaultExtensionNs="com.intellij">
      <moduleType id="ELIXIR_MODULE" implementationClass="org.elixir_lang.module.ElixirModuleType"/>

      <projectStructureDetector implementation="org.elixir_lang.module.ElixirProjectStructureDetector"/>

      <projectImportProvider implementation="org.elixir_lang.mix.importWizard.MixProjectImportProvider" />
      <projectImportBuilder implementation="org.elixir_lang.mix.importWizard.MixProjectImportBuilder" />

      <!-- for doQuickImport when open directory which contains mix.exs file -->
      <projectOpenProcessor implementation="org.elixir_lang.mix.importWizard.MixProjectOpenProcessor" />

      <!-- Specifies semicolon-separated list of paths which should be added to the classpath of the compile server -->
      <compileServer.plugin classpath="jps-builder.jar;jps-shared.jar"/>

      <!-- project compiler configurable -->
      <projectConfigurable instance="org.elixir_lang.configuration.ElixirCompilerOptionsConfigurable"
                           parentId="project.propCompiler" id="Elixir Compiler" displayName="Elixir Compiler" />
      <projectService serviceImplementation="org.elixir_lang.configuration.ElixirCompilerSettings" />
  </extensions>
```

So, that means it's these extension points (as of version 5.1.0 of IntelliJ Elixir):
* `moduleType`
* `projectStructureDetector`
* `projectImportProvider`
* `projectImportBuilder`
* `projectOpenProcessor`
* `compileServer.plugin`
* `projectConfigurable`
* `projectService`

**Comment by gkoller** [comment]
Thank you for the detailed answer!

I've updated the issue for PyCharm (https://youtrack.jetbrains.com/issue/PY-23672) with it. However given the clear distinction Jetbrains seems to be making between Rich IDE's and Small IDE's -- a distinction I was unaware of until you mentioned it -- I doubt I can ever expect these extension points to make their appearance in PyCharm.
