### ISSUE TITLE
Incorrect highlighting when using SDK with source code

### ISSUE THREAD

**Issue by develop7** [KronicDeth/intellij-elixir#684]
Repro:

1. `mix new something`
2. Import this project to IDEA
3. Select Elixir SDK with source code available
4. Open up any module

Expected: `defmodule` is highlighted same way `def` is

Instead: `defmodule` is highlighted with mix of "Variables → Parameter" and "Calls → Macro" styles. See screenshot below (don't mind weird colors):

![screenshot from 2017-04-30 21-17-18](https://cloud.githubusercontent.com/assets/89889/25566950/2d4bd11c-2dec-11e7-8ccd-cc4bca06e033.png)

**Comment by KronicDeth** [comment]
This doesn't happen for me in [current master](https://github.com/KronicDeth/intellij-elixir/commit/5cf4b4393d9371ccad230b258781387c02342a05).  I think this was fixed by #736.  Leave a comment if it's not fixed after the next release.
