### ISSUE TITLE
{:error, :etimedout} when running debugger

### ISSUE THREAD

**Issue by thewoolleyman** [KronicDeth/intellij-elixir#689]
Hi,

I can't create any breakpoints (by clicking gutter or Cmd+F8.  Also, when I open the breakpoints dialog, I don't see any "Elixir" section, just Java.

I am able to successfully run a test in ExUnit via "Run", but when I run it via "Debug" it just times out:

```
/usr/local/Cellar/elixir/1.4.2/bin/elixir -r /private/var/folders/vz/ymfb7l8d59389w2yktx7gwyr0000gn/T/intellij_elixir_modules2/team_city_ex_unit_formatter.ex -pa /private/var/folders/vz/ymfb7l8d59389w2yktx7gwyr0000gn/T/intellij_elixir_debugger1 /usr/local/bin/mix intellij_elixir.debug_task --debugger-port 50381 -- test --formatter TeamCityExUnitFormatter test/cli_test.exs --trace
Testing started at 8:57 PM ...
** (EXIT from #PID<0.70.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :etimedout}
        lib/debug_server.ex:9: IntellijElixir.DebugServer.init/1
        (stdlib) gen_server.erl:328: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I might be missing something, but I believe I followed the docs, and everything else about the plugin seems to be working.

Here's my Plugin and IntelliJ versions:
----
Plugin version 5.1.0
----
IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
Licensed to Chad Woolley
Subscription is active until December 21, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

Thanks,
-- Chad

**Comment by thewoolleyman** [comment]
Update: OK, I realized I can only put breakpoints in `*.ex` files, not `*.exs` files (i.e., not in the test files themselves.

However, I'm still getting timeout errors when I try to run a test via Debug (I can rename this issue to be more appropriate or open a new one if you want).

**Comment by KronicDeth** [comment]
@JakeBecker any ideas?

**Comment by JakeBecker** [comment]
Unfortunately, the actual source of the problem is likely in the Java code. The IDE opens a local port for the debugger to connect to, and that connection is timing out: https://github.com/KronicDeth/intellij-elixir/blob/master/resources/debugger/lib/debug_server.ex#L9

I'm unfortunately busy with other projects and won't be able to debug it anytime soon.

**Comment by thewoolleyman** [comment]
OK, thanks for the response and pointer to code.  I'll try to look into it eventually.
