### ISSUE TITLE
ugly sigil highlighting in the default theme

### ISSUE THREAD

**Issue by nhooyr** [KronicDeth/intellij-elixir#693]
The way sigils are highlighted by default in the default theme is very ugly:
<img width="394" alt="screen shot 2017-05-06 at 8 14 20 pm" src="https://cloud.githubusercontent.com/assets/10180857/25776860/a1f07454-3298-11e7-882f-5fa3c6c1ea80.png">

It gets much better in the darcula theme:
<img width="402" alt="screen shot 2017-05-06 at 8 15 23 pm" src="https://cloud.githubusercontent.com/assets/10180857/25776867/c4b65080-3298-11e7-8c45-8860948d58bd.png">

I think that in the default theme, the colour for the sigils should be changed.

**Comment by KronicDeth** [comment]
I assume you mean that you don't like the black background.  You really need to be more specific than "ugly".

**Comment by nhooyr** [comment]
Yea, it is really hard to read on my screen. Contrasts hard with everything else. I'll come up with some colours I think look nice.

**Comment by nhooyr** [comment]
Ok, what do you think of an only `#005700` foreground?

<img width="526" alt="screen shot 2017-05-08 at 5 33 47 pm" src="https://cloud.githubusercontent.com/assets/10180857/25826369/908a5a54-3414-11e7-9ffd-413b2eb3195e.png">

**Comment by nhooyr** [comment]
Could also do a bold only `#007366` foreground (darker than strings and a bit blue) . Strings are bold, so I think perhaps sigils should too?

<img width="581" alt="screen shot 2017-05-08 at 5 39 24 pm" src="https://cloud.githubusercontent.com/assets/10180857/25826569/57f335de-3415-11e7-9c64-12bf98fff522.png">

**Comment by KronicDeth** [comment]
Miss labeled branch for #751 as 693 instead of 683.

**Comment by KronicDeth** [comment]
@nhooyr, [Char List, String, and Sigil hues are 90° from each other (using HSB color system) on purpose to make them more obviously different](https://github.com/KronicDeth/intellij-elixir/blob/master/COLOR_SCHEME_DESIGN.md#textual).  I'm going to drop the black background, but leave the color, `#996C18` unless you can find a combination of Textual (Char List, String, Escape Sequence, and Sigil) attributes that have better readability.

**Comment by nhooyr** [comment]
Sounds good to me.

**Comment by nhooyr** [comment]
Also, you forgot to update the description for the sigil text attribute in your link.

https://github.com/KronicDeth/intellij-elixir/blob/e83bfcc99a378cefa9bd82f662b15055b4995660/COLOR_SCHEME_DESIGN.md#textual

**Comment by KronicDeth** [comment]
Thanks @nhooyr, fixed it in #765
