### ISSUE TITLE
show inline documentation

### ISSUE THREAD

**Issue by nhooyr** [KronicDeth/intellij-elixir#697]
title.

**Comment by KronicDeth** [comment]
You mean you want Cmd+P to work where it shows the docs and parameter names as you type?

**Comment by nhooyr** [comment]
Yup. And also F1 documentation. https://www.jetbrains.com/help/idea/2017.1/viewing-inline-documentation.html

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
