### ISSUE TITLE
live templates should not be applicable in strings

### ISSUE THREAD

**Issue by nhooyr** [KronicDeth/intellij-elixir#698]
For erlang, IntelliJ offers a bunch of different contexts in which Erlang live templates can be applied. Like, "statement", "expression" etc. But with elixir, the live templates are shown regardless of the context, even in strings.

**Comment by KronicDeth** [comment]
Well, if it in intellij-erlang we can just port it from there.  That's how a lot of the features here start: software archeology on the pre-existing open source plugins and intellj-community.  Can you read enough Java to figure out how they did it?

**Comment by nhooyr** [comment]
I will try and see if I can figure it out.

**Comment by nhooyr** [comment]
I've tried searching through the code but I can't even find the place where this stuff is handled. I used `rg` to look for the different contexts and all I could find was the place where the live templates are stored. Sorry, I've got no idea how they did it. :(

Is it ok to @ the creator of the Erlang plugin so that he can explain?

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
