### ISSUE TITLE
Add a way to select Erlang version

### ISSUE THREAD

**Issue by raul782** [KronicDeth/intellij-elixir#701]
This is an issue explaining the issues that this raises, when Erlang is not set:
 [https://github.com/KronicDeth/intellij-elixir/issues/190](#190)

I personally believe that giving the user the option to choose and set the Erlang Path is the best approach
@KronicDeth what do you think is the best approach here?

I've started working on this PR:
https://github.com/KronicDeth/intellij-elixir/compare/master...raul782:issue-701?expand=1

**Comment by raul782** [comment]
I'm having the following error:
<img width="653" alt="screen shot 2017-05-22 at 12 03 48 am" src="https://cloud.githubusercontent.com/assets/181557/26293447/53362fe8-3e82-11e7-8559-dfc3e1f7cac3.png">
Even as the binding class is correctly setup.
<img width="574" alt="screen shot 2017-05-22 at 12 05 35 am" src="https://cloud.githubusercontent.com/assets/181557/26293453/6de3ddc2-3e82-11e7-8be9-2ef2c158216d.png">

**Comment by KronicDeth** [comment]
Yes, I think the Erlang path needs to be selectable and this does mimic what's done for mix, but I think now that mix and Erlang path should be a setting on the SDK or Project at least because you will use a different Erlang version for compatibility with different Elixir versions.
