### ISSUE TITLE
No Elixir SDKs are shown when trying to make a new project

### ISSUE THREAD

**Issue by RyanKim01** [KronicDeth/intellij-elixir#706]
#Hi,
I'm currently using IntelliJ ULTIMATE 2017.1.3, Mix 1.4.4, Elixir 1.4.4.

I installed the Elixir plugin using "Inside IDE using JetBrains repository" way. When I'm creating a new Elixir project, I am having a problem of not seeing Elixir SDKs listed as in the guide. Any thoughts on what I am doing wrong?

I did update my homebrew and elixir before I tried making the Elixir project in IntelliJ.

<img width="1019" alt="elixir-sdk-not-shown" src="https://cloud.githubusercontent.com/assets/10735853/26744109/63b99baa-4799-11e7-96b1-e059dc7b4789.png">

**Comment by KronicDeth** [comment]
@RyanKim01 did you try clicking "Configure..." ?

**Comment by RyanKim01** [comment]
It wasn't working previously since I was keep trying to open "usr/local/Cellar/elixir/1.4.4/bin". I tried to open "usr/local/Cellar/elixir/1.4.4" and it just worked. I'm closing the issue. Thanks @KronicDeth
