### ISSUE TITLE
If you give no options to ExUnit runner, it sends an empty string as the pattern instead of just running mix test without any pattern

### ISSUE THREAD

**Issue by thewoolleyman** [KronicDeth/intellij-elixir#709]
It's a bug that empty arguments aren't handled.

As a work-around, you could just make a fake flag, like --include not_a_tag.

See more details on this PR: https://github.com/KronicDeth/intellij-elixir/pull/707#issuecomment-306063341

**Comment by vanburg** [comment]
This work-around doesn't work for me either (v5.1.0), still empty quotes passed:
```
No file named
```
This does :)
```elixir
defp deps do
  [{:mix_test_watch, "~> 0.3", only: :dev, runtime: false}]
end
```
