### ISSUE TITLE
Running a cowboy/Elixir project in intelliJ

### ISSUE THREAD

**Issue by epborsato** [KronicDeth/intellij-elixir#712]
Hello, 

I'm trying to run/debug a Elixir project that runs on a Cowboy server. when I start the project via the command line (iex -S mix)  the project starts just fine and I can check the web-browser and see the page is being served. However I'm not able to start via intelliJ and debug it. I can run the project, but that does not start cowboy with the configuration "run". Thank you.

**Comment by KronicDeth** [comment]
The debug configurations are normally meant for debugging ExUnit configurations.  Are you saying that you normally run the cowboy server when running mix test?

**Comment by epborsato** [comment]
@KronicDeth, we have an Elixir web application that run on Cowboy web server. what we want is the ability to debug it using intelliJ. Do you know if that is possible with the intelliJ/Elixir plugin?
Thanks

**Comment by KronicDeth** [comment]
`iex -S mix` Run/Debug Configurations were added in #1175 and shipped in [v8.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v8.0.0) on 2018-08-16.
