### ISSUE TITLE
Strip trailing spaces

### ISSUE THREAD

**Issue by mariuszzak** [KronicDeth/intellij-elixir#715]
Thank you so much for awesome plugin!

I experienced a problem with striping trailing spaces after saving a file.

Let's say we have a code:

```elixir
defmodule Foo do
  def bar do
  end
  
  def baz do
  end
end
```

I would expect that after saving a file those spaces in the line between functions will be striped. RubyMine behaves like that in case of Ruby code. 

What do you think?

**Comment by KronicDeth** [comment]
Strip trailing spaces on save is a general editor setting.  It's not implemented as a language-specific extension.  You should already have access to it. If you're using IntelliJ it's

1. Select from the main menu IntelliJ IDEA  > Preferences
   ![screen shot 2017-06-22 at 8 28 27 pm](https://user-images.githubusercontent.com/298259/27462943-e3d4a712-5789-11e7-8c65-24a12d5318fe.png)
2. In the Preferences dialog go to Editor > General
   ![screen shot 2017-06-22 at 8 28 41 pm](https://user-images.githubusercontent.com/298259/27462967-0e1dfb68-578a-11e7-819d-2ec74b3cabd1.png)
   ![screen shot 2017-06-22 at 8 28 50 pm](https://user-images.githubusercontent.com/298259/27462985-3c59b18e-578a-11e7-8c34-5e4a4890825f.png)
3. Select "All" from the  "Strip trailing spaces on Save" dropdown    
  ![screen shot 2017-06-22 at 8 28 55 pm](https://user-images.githubusercontent.com/298259/27462990-49db45d4-578a-11e7-9c8b-944ea714937c.png)

4. Click "OK"

If those instructions don't work for you let me know.

**Comment by mariuszzak** [comment]
Yup, I enabled this option.

![image](https://user-images.githubusercontent.com/4352899/27638535-e16fc090-5c13-11e7-869d-ca58374450e8.png)

Generally trailing spaces works fine in case I have some code at this line and white spaces at the end of line. It doesn't work if the line contains only white spaces. 

In case of Ruby code it works fine, which is really weird. 

Another example that illustrates the issue:

```
defmodule Foo do
  def bar do
  end  #spaces here will be removed
  #spaces here will not be removed
end
```

**Comment by KronicDeth** [comment]
This might be fixed when #98 lands, but I'll leave it open until I can confirm.

**Comment by mariuszzak** [comment]
@KronicDeth Awesome! Thank you so much! ![](https://media.giphy.com/media/l2JhBOWhKWH7n4c6I/giphy.gif)

**Comment by KronicDeth** [comment]
This is fixed when I test it on [master](https://github.com/KronicDeth/intellij-elixir/commit/45a6863fe174009344a08bdcbe21eec1233faaf7)

**Comment by mariuszzak** [comment]
Works fine! Thank you!
