### ISSUE TITLE
`{:error, :ehostunreach}` when running debugger

### ISSUE THREAD

**Issue by CatTail** [KronicDeth/intellij-elixir#721]
After add debug configuration and run debugger, the following error message popup,

```
/usr/local/Cellar/elixir/1.4.5/bin/elixir -pa /private/var/folders/gt/r1p1xhl93h5d5nh0tvwtjckw0000gn/T/intellij_elixir_debugger /usr/local/bin/mix intellij_elixir.debug_task --debugger-port 62494 -- ""
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :ehostunreach}
        lib/debug_server.ex:9: IntellijElixir.DebugServer.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

Intellij version

```
IntelliJ IDEA 2016.3.7
Build #IC-163.15529.5, built on May 19, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Elixir version: 1.4.5
Plugin version 5.1.0

**Comment by KronicDeth** [comment]
At the very end of the commandline it says `""` which means it is sending an empty argument to `mix`, so it isn't starting anything besides the debugger, so there's nothing to debug.  Can you show a screenshot of the Run Configuration?

**Comment by CatTail** [comment]
My configuration is this

![image](https://user-images.githubusercontent.com/1606069/27844304-2c4541ba-6152-11e7-9fc0-f23623770514.png)

But even I add something in configuration, still the same problem.

```
/usr/local/Cellar/elixir/1.4.5/bin/elixir -pa /private/var/folders/gt/r1p1xhl93h5d5nh0tvwtjckw0000gn/T/intellij_elixir_debugger1 /usr/local/bin/mix intellij_elixir.debug_task --debugger-port 51571 -- run --no-halt
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :ehostunreach}
        lib/debug_server.ex:9: IntellijElixir.DebugServer.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by CatTail** [comment]
@KronicDeth Actually, I'm new to Elixir & Intellij, can you provide an simple hello world project that able to work with intellij-elixir? That will be very helpful.

**Comment by KronicDeth** [comment]
@CatTail if you're still getting `:ehostunreach`, I'm going to have to assume that something is weird with your firewall where it's not allowing a loopback connection on the shown ports.  What OS are you on and which firewall are you using?

Projects that are known to work with the debugger:
* https://github.com/C-S-D/alembic
* https://github.com/C-S-D/calcinator

Open them using the ["Import project from External Model"](https://github.com/KronicDeth/intellij-elixir#import-project-from-external-model) steps in the README.

**Comment by CatTail** [comment]
Have the same issue with

* Firewall closed
* Using project https://github.com/C-S-D/alembic

I'm using macOS Sierra, Version 10.12.5

![image](https://user-images.githubusercontent.com/1606069/27848440-c229562e-6177-11e7-879e-1b99577c9b37.png)

**Comment by KronicDeth** [comment]
I'm not sure how the host can be unreachable with macOS firewall off.

**Comment by CatTail** [comment]
Close since this issue is not active for a long time.
