### ISSUE TITLE
SDK Path invalid if Elixir is installed anywhere outside of C:/Program FIles (x86)/ on Windows.

### ISSUE THREAD

**Issue by bredmor** [KronicDeth/intellij-elixir#733]
Attempting to select the Elixir/bin directory as the SDK path if you have installed Elixir anywhere but the default suggested path results in the attached error.
![image](https://user-images.githubusercontent.com/8249823/28237246-b951eb22-6908-11e7-9594-b347904f5ce3.png)

**Comment by KronicDeth** [comment]
The SDK path is not the `bin` directory, it's the parent of the bin directory because the SDK is both the binaries and the libs.  If selecting the parent of the `bin` does not work for you, I'll reopen.

**Comment by SyedWasiHaider** [comment]
Hi @KronicDeth. I just ran into a similar issue. I have my windows Elixir installation in the D:/ drive and I just ran into this issue. The error that I specifically get is this:

![image](https://user-images.githubusercontent.com/3202990/30841719-b70551de-a232-11e7-8abb-4f4236ecd90b.png)

I'm fairly certain the Elixir installation is not corrupt. Any help is appreciated.

**Comment by DRogueRonin** [comment]
The same happened for me. I installed Elixir at `F:\Windows\Programme\Elixir`. I then tried to symlink the directory from **F:** to **C:**, but it still says it's corrupt. I thought maybe I have to adjust the PATH, but that didn't do anything either.

**Symlink Command**
```
mklink /D "C:\Program Files\Elixir" F:\Windows\Programme\Elixir
```
