### ISSUE TITLE
Regex ungreedy modifier "U" breaks formatting

### ISSUE THREAD

**Issue by h4cc** [KronicDeth/intellij-elixir#752]
The new Regex ungreedy modifier at the end of a regex "U" breaks formatting. The old value was/is "r":

> ungreedy (U) - inverts the “greediness” of the regexp (the previous r option is deprecated in favor of U)
https://hexdocs.pm/elixir/Regex.html#module-modifiers

Examples:

`~r/foo(.*)bar/i` is ok
`~r/foo(.*)bar/iU` breaks formatting

**Comment by KronicDeth** [comment]
It's a new feature for Elixir, so it'll count as an enhancement even though you experience as a bug.

**Comment by h4cc** [comment]
perfectly fine :+1:

**Comment by KronicDeth** [comment]
This will be a port of https://github.com/elixir-lang/elixir/pull/2774 for cross-reference.
