### ISSUE TITLE
Debugging doesn't work when :int isn't installed in Ubuntu

### ISSUE THREAD

**Issue by wooque** [KronicDeth/intellij-elixir#753]
Tried to start debugger for mix phoenix server, but it fails with exception:
```
/usr/local/lib/elixir/bin/elixir -pa /tmp/intellij_elixir_debugger246 /usr/local/bin/mix intellij_elixir.debug_task --debugger-port 38233 -- phoenix.server
** (UndefinedFunctionError) function :int.interpretable/1 is undefined (module :int is not available)
    :int.interpretable(Hello.Endpoint)
    lib/debug_task.ex:63: anonymous fn/1 in Mix.Tasks.IntellijElixir.DebugTask.interpret_modules_in/1
    (elixir) lib/enum.ex:2857: Enum.filter_list/2
    lib/debug_task.ex:63: Mix.Tasks.IntellijElixir.DebugTask.interpret_modules_in/1
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    lib/debug_task.ex:16: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
```
Non-debug session starts fine.
OS: Ubuntu 17.04
Erlang: 20
Elixir: 1.5
Phoenix: 1.2.1

**Comment by KronicDeth** [comment]
`:int` is part of a normal Erlang install, but I think Ubuntu packages some of the Erlang OTP applications is separate debs.  Please check if you have all the optional parts of Erlang OTP installed.  `:int` is related to the debugger (`:int` is short for "interpret"), so if there's a debugger deb for Erlang, `:int` may be in there.

**Comment by wooque** [comment]
Yes you are right. Installing erlang-debugger package solved the issue

**Comment by KronicDeth** [comment]
Thanks for the confirmation @wooque.  I'll add the information to the README.
