### ISSUE TITLE
SDK Paths for Nix on Linux, NixOS

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#762]
This was partially solved for MacOS. As far as I can tell, the same logic should work for Linux as it does for MacOS.

The location for Elixir SDKs with Nix or NixOS is /nix/store/<hash>-elixir-<version>/. For example, for Elixir v1.1.1, the store location is /nix/store/408lfdw0l4fzds3mkzp57gwfpgpq0w5h-elixir-1.1.1/.

**Comment by KronicDeth** [comment]
@Havvy I just realized I may be able to test this using a docker container on Mac, but if you have a better suggestion for how to confirm it works on Linux let me know.

**Comment by Havvy** [comment]
How do you test that the current "setup" works on Linux?

I can definitely test it manually, if anything.

**Comment by KronicDeth** [comment]
Well, I don't do any manual testing on Linux current, the automated tests are all on Linux though because that's what Travis-CI runs, but for these project setup and SDK finding feature, I've always had to test them manually because there isn't a good test harness for them in OpenAPI.
