### ISSUE TITLE
Decompilation not working with OTP 20 using AtU8 chunk for ASCII atoms

### ISSUE THREAD

**Issue by tzveeJ** [KronicDeth/intellij-elixir#772]
Hey - Autocomplete isn't working for me for standard modules - it only looks at local project modules for me (including modules in dependencies). I saw here https://github.com/KronicDeth/intellij-elixir/issues/301 that it's supposed to be working. I'm on version 5.1, and I even tried reinstalling the plugin and restarting. Any idea what I might be doing wrong? Thanks.

**Comment by KronicDeth** [comment]
1. Do you have your SDK setup?
2. What IDE are you using?

**Comment by tzveeJ** [comment]
1. I believe I do. If I go into File -> Project Structure, I see Project SDK as "Elixir 1.4.5". In case this helps, I went to "Edit" and found that "/usr/local/Cellar/elixir/1.4.5". Just now, I also tried following the existing "Create project from existing sources" instructions to ensure that I followed setup steps precisely, but at step #10 instead of showing "Next", I only have a "Finish" option, likely because my SDK is already set up.

2. I am using IntelliJ IDEA 14.1.7.

**Comment by KronicDeth** [comment]
@tzveeJ somethings to check, can you see the decompiled modules?  If you use the Shift Shift search, and type `Kernel.beam`, do you see `Elixir.Kernel.beam` and can you select it and it opens to decompiled code?  Do you have any error indicator?  It will be in the lower right corner of the window edge.

**Comment by tzveeJ** [comment]
When I hit Shift Shift to search, I have to check off "Include non-project items" to get it to find `Elixir.Kernel.beam`, otherwise it doesn't find it. When I then open it, all I see is a file containing the text "Decompilated Error". I do not see an error indicator.

**Comment by KronicDeth** [comment]
Include non-project items is correct.  Your SDK is not part of your project.  It's a library.

Are you using OTP 20 or have the `Elixir.Kernel.beam` files installed with restrictive permissions @tzveeJ?  "Decompilated error" occurs if any of the following

1. The `.beam` file cannot be read
2. The `Atom` chunk cannot be found
3. The `Atom` chunk is too short
4. The `Atom` chunk is empty, and so there is no 0th entry for the module name

You should be able to attach your `Elixir.Kernel.beam` to your next Github comment by putting it into a zip.

**Comment by tzveeJ** [comment]
I am using OTP 20. I did not install Elixir with any restrictive permissions as far as I know. I installed using brew, and I'm on a Mac running Sierra. I'd be happy to check the permissions if you point me at how to do so.

Here is the file you asked for:
[Elixir.Kernel.beam.zip](https://github.com/KronicDeth/intellij-elixir/files/1203647/Elixir.Kernel.beam.zip)

**Comment by KronicDeth** [comment]
Added some extract information to the decompilation output when there's an error and it confirms that the OTP20 beams don't have an `Atom` chunk, which makes sense since a [big feature of OTP20 was the addition of the UTF8 atom support, which added the new `AtU8` chunk](https://github.com/erlang/otp/pull/1078).

**Comment by tzveeJ** [comment]
@KronicDeth Thanks for looking into this, I'm looking forward to the fix! Really enjoying the plugin otherwise, thanks x10!
