### ISSUE TITLE
New Elixir Project

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#78]
There should be a option to create a new Elixir Project in the Intellij Project dialog.  Requested by @prodev42 in #77 and @andreacfm on [stackoverflow.com](https://stackoverflow.com/questions/27730087/new-elixir-project-in-intellij#comment43899731_27730087)

- [ ] Elixir Project in Intellij Project dialog

**Comment by andreacfm** [comment]
@KronicDeth Thanks for opening this.

**Comment by jacek99** [comment]
+1

That seems to be the obvious missing feature from the plugin (preferably with mix support built right in)

**Comment by zyuyou** [comment]
+1, look forward this feature!!

**Comment by KronicDeth** [comment]
Closing as a duplicate of #22.  Looks like I can't keep track of multiple pages of issues.  Everyone over to #22 with :+1: so I don't lose track and you'll get notifications when I close it.
