### ISSUE TITLE
using auto completion on do puts cursor on wrong location

### ISSUE THREAD

**Issue by nulian** [KronicDeth/intellij-elixir#793]
When you already have def test and you use the autocompletion on do your cursor goes to the next line but at the same place as the def instead of tabbed in.
```
def method do
"hallo"
end
```

**Comment by KronicDeth** [comment]
The formatter infers the location of a new line by using the previous child's indent when it is a available.  I'll have to change `getChildAttributes` to handle the first line of a do block, so that it's indented too.
