### ISSUE TITLE
Run configuration

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#80]
A run configuration, such as `iex -S mix`, `elixir <project>`, or exrm's `<project> start` for running an Elixir program.  Requested by @prodev42 in #77.

- [ ] `iex -S mix`
- [ ] `elixir <project>`
- [ ] distillery's `<project> start`
- [x] `mix` (#167)
- [x] `mix test` (#482)
- [x] `mix test` debug (#643)

**Comment by KronicDeth** [comment]
@prodev42, supporting iex as an interactive console or supporting running an program non-interactively, with `elixir` or exrm's release commands should be different features, so which would you like first?

**Comment by prodev42** [comment]
Supporting running an program non-interactively first please. Thanks

**Comment by KronicDeth** [comment]
#167 will resolve this issue

**Comment by KronicDeth** [comment]
#167 only supplied Mix Configurations, so this should remain open for `iex` console sessions, `elixir` runs , and exrm support.

**Comment by KronicDeth** [comment]
#482 added context derived ExUnit run configurations

**Comment by KronicDeth** [comment]
#643 added debugger run configurations
