### ISSUE TITLE
Debugger configuration

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#81]
There is no Elixir native debugger, so allow running with the Erlang debugger attached to a project.  This may involve just using the Erlang debugger support from intellij-erlang.  Requested by @prodev42 in #77.

**Comment by williamgueiros** [comment]
ok i will try developer debugger.
in projet intellij-erlang the first commit is:
 https://github.com/ignatov/intellij-erlang/commit/e4d9fbd3d2798692af935cc4564f4d8112f35978

and if you have more official information from jetbrains, how developer this, please send to me.

**Comment by KronicDeth** [comment]
Completed by @JakeBecker in #643
