### ISSUE TITLE
`end` is not an allowed keyword key

### ISSUE THREAD

**Issue by IcyEagle** [KronicDeth/intellij-elixir#821]
Hi.

This code works good, but there is a problem with highlighting.
Is it possible to fix it?

![4d7ee25922](https://user-images.githubusercontent.com/298259/30041883-1dc97ef8-91b3-11e7-92cd-36a89b8bdeb5.jpg)

Thanks!

**Comment by KronicDeth** [comment]
Yeah, I noticed that `end` had to be protected as `"end":` when helping @StabbyMcDuck with her talk for ElixirConf.  Definitely a bug.  `END` is not a listed token in `keywordKey` grammar rule

https://github.com/KronicDeth/intellij-elixir/blob/634747502e54993af47a08305bad126c9f037b0d/src/org/elixir_lang/Elixir.bnf#L2833-L2881

It may also need to have proper lexer changes to check for `:` after it like `do` has.
