### ISSUE TITLE
Use Dbgi chunk to show Elixir source in .beam files

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#826]
Use Elixir source stored in [the Dbgi chunk](https://github.com/erlang/otp/pull/1367) in the .beam to show the original source on a second tab next to the decompilation that the `.beam` decompiler already shows.

**Comment by OvermindDL1** [comment]
That means the beam files could also show the original source too, not just elixir, but also erlang, lfe, and more that use the new dbgi chunk.

**Comment by KronicDeth** [comment]
@OvermindDL1 that's a good point.  I'll have to check how to make `intellij-erlang` automatically highlight Erlang when it's Erlang in the Dbgi.

**Comment by KronicDeth** [comment]
Function bodies were decompiled from DbgI in https://github.com/KronicDeth/intellij-elixir/commit/749a43240f891a1bcabdf299a1c7ed53399bd833, which was first released in [v12.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v12.0.0) on December 5th 2021.
