### ISSUE TITLE
Autocomplete Erlang SDK module names

### ISSUE THREAD

**Issue by Romain-P** [KronicDeth/intellij-elixir#829]
I don't know if this feature is already done, but it does not work on my Intellij.
I have the plugin installed correctly, and wrote an empty module

```
IO.puts("Hello Word")

#atoms & var
sortArray = :lists.sort([1,3,5,2])
IO.inspect(sortArray)
```
IO.inspect was written by autocompletion
But :lists.sort didn't purpose me nothing :(

**Comment by KronicDeth** [comment]
`:lists` would autocompleting, but the Erlang SDK beams aren't being scanning.  It will work once I add that.
