### ISSUE TITLE
`not in` form is not supported by parser

### ISSUE THREAD

**Issue by JanStevens** [KronicDeth/intellij-elixir#844]
Following elixir code is perfectly valid but gives syntax highlighting

```elixir
def row_color(%Scan{exported_code: status}) when status not in ["ok", "scanout", "refer"], do: "danger"
```

![screen shot 2017-10-05 at 10 04 58](https://user-images.githubusercontent.com/1540483/31216660-b3cb949a-a9b4-11e7-9b6b-cb0d8df36d9e.png)

**Comment by KronicDeth** [comment]
`not in` was added in Elixir 1.5.  Port https://github.com/elixir-lang/elixir/pull/5620.
