### ISSUE TITLE
Cannot run program "elixir" in PHPStorm

### ISSUE THREAD

**Issue by Barno** [KronicDeth/intellij-elixir#858]
I have an error when try to use debug

My configuration in Elixir Mix is:
Working directory: Absolute path of my project
https://ibb.co/hTNQD6

When click Play I have two alert
`Cannot run program "elixir" (in directory "/Users/Barno/Documenti/Lavori/garage/Elixir/hello_exunit"): error=2, No such file or directory`
and 
`Mix executable path is not specified correctly`

My configuration of Elixir ExternalTools is correct
Path is my absolute Path and even SDK path is ok
https://ibb.co/jsUi0m

PHPStorm 2017.2.4

**Comment by KronicDeth** [comment]
@Barno I think you're running 6.2.0 of the plugin.  Update to 6.3.0.

**Comment by Barno** [comment]
Thanks for reply, now I have 6.3.0 but I have the same problem

`Mix executable path, elixir executable path, or erl executable path is not specified correctly`

**Comment by KronicDeth** [comment]
It looks like you're using homebrew's Elixir install, so it may be that however you're launching PHPStorm, your `PATH` isn't preserved, so while the path to `elixir` is configured, the path to `erl` is not and it's not on the `PATH` environment variable PHPStorm is using.  For the Rich IDEs (IntelliJ IDEA CE/UE) I recently added support for configuring the path to the Erlang SDK separately to work-around this issue.  You have a few work-arounds:

1. Launch to inherit homebrew paths
  1. Close PHPStorm
  2. Launch PHPStorm from a terminal with the correct `PATH` set: `phpstorm`
2. Use IntelliJ IDEA CE/UE, so you can set the path to erlang explicitly in the Erlang Internal SDK on the Elixir SDK.

I'll be adding support for configuring the path to Erlang SDK in External Erlang Tools soon (1 or 2 releases) also.  Let me know if you're using Erlang NOT installed by homebrew, as it could be that too.

**Comment by DominikGuzei** [comment]
Starting Webstorm with `PATH=$PATH wstorm .` solved the issue for me.

**Comment by KronicDeth** [comment]
I just need to port the "Internal Erlang SDK" support to the Small IDEs by adding the option to set the path to the Erlang SDK in the Elixir settings

**Comment by DominikGuzei** [comment]
Yes please 👍

**Comment by nitingupta910** [comment]
`PATH=$PATH clion .` for clion worked for me.

**Comment by KronicDeth** [comment]
Internal Erlang SDK support was added to the Elixir Facet (small IDE support) in ea69e22a6d9601b30aa1aa72aa2dabd7db082151, which was released in 7.1.0.
