### ISSUE TITLE
Support colors in run configurations

### ISSUE THREAD

**Issue by kwando** [KronicDeth/intellij-elixir#875]
It would be nice if mix tasks runned through a "mix run configuration" showed colors in the "console window".
The elixir Logger emits colorized messages when run in the "terminal" panel but not when running through a run configuration.

**Comment by KronicDeth** [comment]
Duplicate of #315.  Resolved in #863.  Wait for next release.

**Comment by kwando** [comment]
Whoops, sorry for the noise. I missed that issue while glancing through the list.

**Comment by KronicDeth** [comment]
Not surprising, the issue title and comments don't contain "color" in them since it's talking directly about how colors are implemented: ANSI escape codes.  You weren't likely to know that unless you do a lot of terminal programming.
