### ISSUE TITLE
Why does it keep recompiling when I switch between 'mix test' and Ctrl-Shift-R ?

### ISSUE THREAD

**Issue by raarts** [KronicDeth/intellij-elixir#899]
When I work in IntelliJ, I can just do the regular Edit-Debug cycle, then when I switch to the command line and run `mix test`, mix recompiles everything, and when I go back to the IDE, that recompiles everything again. (Working on OSX). Is it a bug? Does the IDE do something special?

**Comment by KronicDeth** [comment]
Usually for me, this happens when I misconfigured the SDK version in the IDE, so the version in command line is different and so Elixir detects that it should rebuild
