### ISSUE TITLE
Sluggish IDE after upgrading to version 6.5.1 of plugin

### ISSUE THREAD

**Issue by andshape** [KronicDeth/intellij-elixir#909]
OS: Windows 10
IntelliJ: 2017.2.6
Elixir-plugin: 6.5.1

After upgrading to 6.5.1 from 6.1.1, IntelliJ has become quite sluggish. I've tried reinstalling the plugin to no avail. Though I noticed no sluggishness once the plugin was uninstalled. I've looked at #822 and  #580 but they seem to describe a different issue than the one I am experiencing. I experience the sluggishness even for "small"  .ex files (100 lines) without nested anonymous functions.

Has there been introduced new options for the plugin I should be aware of (turn off) to get back to the old performance? Or is there a way I can revert back to old version of the plugin?

**Comment by KronicDeth** [comment]
@andshape I'd recommend doing a bisecting install of the versions from 6.1.1 to 6.5.1.

- [ ] Start in the middle at [v6.4.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v6.4.0)
  - [ ] If slow go earlier [6.3.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v6.3.0)
    - [ ] If slow then go earlier [6.2.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v6.2.0)
      - [ ] If slow then `6.2.0` is the problem.
      - [ ] If fast then `6.3.0` is the problem.
    - [ ] If `6.3.0` is fast then `6.4.0` is the problem.
  - [ ] If fast go later [6.5.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v6.4.0)
    - [ ] If slow then `6.5.0` is the problem
    - [ ] If fast, then `6.5.1` is the problem

**Comment by andshape** [comment]
@KronicDeth
Thanks for the quick response. I've done the bisecting install and here are the results:

- v6.4.0 is fast (The initial indexing is also fast)
- v6.5.0 Something is wrong with the release found in https://github.com/KronicDeth/intellij-elixir/releases  the zip is only 14.4 KB and I can see that a lot of files inside the zip are missing compared to the other releases.
- v6.5.1 is slow (The initial indexing is also extremely slow)

For now I'll use the 6.4.0 version. It seems the problem is either in v6.5.0 or v6.5.1.

If you have time to (re)create the v6.5.0 release I'll try installing that version as well.

**Comment by take-five** [comment]
I can confirm the issue. On 6.5.1 my IDE became too slow, so I had to switch to 6.4.0

**Comment by KronicDeth** [comment]
Sluggishness could be a memory difference.  The JetBrains IDEs ship with a very low max-memory size of like 256MB. They can try their best to garbage collect and just get sluggish before they'll prompt you to increase the JVM memory limit.

Turn on the memory indicator
1. Preferences > Appearance & Behaviour > Appearance
2. Scrool to Window Options
3. Check "Show memory indicator"

Let me know the numbers with fast vs slow versions that work for you @andshape and @take-five.

**Comment by KronicDeth** [comment]
https://youtrack.jetbrains.com/issue/WEB-30049

**Comment by nikshik** [comment]
@KronicDeth I attached IDEA log file to intellij ticket: https://youtrack.jetbrains.com/_persistent/idea.log?file=74-472910&c=true

**Comment by KronicDeth** [comment]
@andshape, @Kalaww, @komlanvi, @nikshik: Update to 6.7.0 and let me know if you're still seeing performance problems.  If you are, then I'll reopen this because it will mean that this issue did not have the same root cause as #580.

**Comment by nikshik** [comment]
@KronicDeth thanks for the fix! I installed Elixir 6.7.0 and worked for couple of days and don't see any performance problems now. If there will be some I will report you back

**Comment by RazgrizHsu** [comment]
thanks for the fix! 6.7.0 perfect performance!

**Comment by komlanvi** [comment]
Upgraded to 6.7.0 and it solved the performance issue. Thank you!

**Comment by KronicDeth** [comment]
@andshape answer the questions in https://github.com/KronicDeth/intellij-elixir/issues/949#issuecomment-351389274 to help figure out if the `mix credo` external annotator.

**Comment by KronicDeth** [comment]
@andshape try the new Credo [configuration options](https://github.com/KronicDeth/intellij-elixir#configuration) in [v7.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v7.0.0) and let me know if you still have sluggishness when you have credo doing less.

**Comment by take-five** [comment]
After upgrading to 7.0.0 and turning Credo annotations off, IDE became fast again. Thanks a lot, @KronicDeth !

**Comment by miquecg** [comment]
IntelliJ IDEA 2017.3.2
Elixir plugin 7.2.1

Problem is still present for me. With `credo` inspections disabled project indexing takes forever and IDE becomes unusable. It freezes when changing between file tabs. Clearing cache and restarting doesn't help.

**Comment by KronicDeth** [comment]
@miquecg check for errors in status bar and open a new issue.  This one is closed.  Any "slowness" shouldn't pile on this issue.  Y'all probably don't have the same root cause, it makes no sense to group together.
