### ISSUE TITLE
erocksdb misreports as interpretable

### ISSUE THREAD

**Issue by zhaoyi0113** [KronicDeth/intellij-elixir#915]
I have a elixir mix project. I tried to debug it from IntelliJ but failed with below error. I am able to run the project in IntelliJ but not able to debug.

```
21:21:42.141 [warn]  The on_load function for module erocksdb returned:
{:error, {:upgrade, 'Upgrade not supported by this NIF library.'}}

** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    int.erl:531: anonymous fn/3 in :int.load/2
    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:675: Enum.each/2
    /private/var/folders/xs/y0pbzxkn7gqcdtrz4cpxtwrw0000gn/T/intellij_elixir/debugger/lib/debug_task.ex:19: Mix.Tasks.IntellijElixir.DebugTask.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2

```

Below is my project dependencies:

```
defp deps do
    [
        {:poison, "~> 2.0"},
        {:httpotion, "~> 3.0.0"},
        {:logger_file_backend, "~> 0.0.9"},
        {:erocksdb, "~> 0.4.1"},
        {:espec, "~> 1.4", only: :test},
		{:uuid, "~> 1.0"}
    ]
  end
```

**Comment by KronicDeth** [comment]
Unfortunately, there are some libraries that mis-report their `beam` being interpretable

https://github.com/KronicDeth/intellij-elixir/blob/314807fbfafc0ed34597406dd2c7bd16e2426e5e/resources/debugger/lib/debug_task.ex#L6

which is how it's decided whether it's safe to debug them. 

To not attempt interpret `erocksdb`, set an Environment Variable in your Run Configuration

| Name                                                     | Value           |
|--------------------------------------|-------------|
| INTELLIJ_ELIXIR_DEBUG_BLACKLIST | `erocksdb` |
