### ISSUE TITLE
IDEA becomes slow and unresponsive when using Elixir plugin

### ISSUE THREAD

**Issue by nikshik** [KronicDeth/intellij-elixir#941]
Don't have any details yet, just intellij support redirected me to the elixir plugin vendor:
https://youtrack.jetbrains.com/issue/WEB-30049

**Comment by KronicDeth** [comment]
@nikshik move any comments over to https://github.com/KronicDeth/intellij-elixir/issues/909 since that's a pre-existing general "it's slower" bug.
