### ISSUE TITLE
Use LanguageLevelPusher, pushLanguageLevel and getFileLanguageLevel for version dependent parsing

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#946]
> @KronicDeth, I also see an issue in how version dependent parsing works in Elixir. This can cause stub/psi mismatch problems which I see in the snapshot uploaded.Right now it checks the version of SDK directly during file parsing. This means that if SDK version changes between two parsings (first one is when index is built, the second one happens when someone accesses actual PSI tree) you may get a mismatch as the parsing tree changes and the index had not been rebuilt. In order to handle this properly, you'll need to implement LanguageLevelPusher.You can find an example here. In short, you should call pushLanguageLevel each time SDK version changes and call getFileLanguageLevel from the parser.
> @denofevil on [WEB-30049](https://youtrack.jetbrains.com/issue/WEB-30049#comment=27-2589027)

**Comment by KronicDeth** [comment]
@denofevil how do I get the `VirtualFile` to get its specific level? I know how to get the `Project` from `PsiBuilder#getProject`.  I don't have a direct `VirtualFile` in my `ifVersion` external rule.  

https://github.com/KronicDeth/intellij-elixir/blob/1faf2403fef6d6b3a79c4c733169131623537269/src/org/elixir_lang/parser/ExternalRules.java#L10-L49

**Comment by KronicDeth** [comment]
```
((PsiBuilderImpl)((Builder)psiBuilder).myDelegate).myFile.getVirtualFile()
```

is `null` when I'm in `parseContents`, so I'm not sure how to get a `VirtualFile` and then to a `Module`.

**Comment by KronicDeth** [comment]
Figured out I could use `UserData` to store the `VirtualFile` by overriding `parseContent` or `doParseContent`.  Sometimes, the `VirtualFile` is `null`, so it has to fallback to the `Project`, but it is available sometimes, such as when the file is open in the Editor.

**Comment by denofevil** [comment]
I'd probably pass it as an option to the parser in `parseContents` method. In `parseContents` you can get it via `psi.getOriginalFile().getVirtualFile()`
