### ISSUE TITLE
Go To Symbol Contributor

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#96]
Use [guide](https://confluence.jetbrains.com/display/IntelliJIDEA/Go+To+Symbol+Contributor) I can use Go To Symbol or Search Everywhere to search for calls by name.  Requested by @KronicDeth.

- [x] Functions
- [x] Macros
- [x] Callbacks
- [x] Modulars

**Comment by trungpham** [comment]
like
