### ISSUE TITLE
7.1.0 has lost code styling in IntellIJ Idea

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#960]
I've tried to Invalid Cache & Restart, but code styling does not work in in IntellIJ Idea

IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 26, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-21-generic

**Comment by KronicDeth** [comment]
What do you mean by Code Styling? Do you mean the annotator level highlighting or the lexer level highlighting?  Reformat code? All of those are working for me.  Some before and after screenshots would be helpful.

**Comment by KronicDeth** [comment]
This is probably related to #959.

**Comment by joshuataylor** [comment]
Sorry!
By code styling, I mean the colour scheme seems to be lost.
7.0:
![image](https://user-images.githubusercontent.com/225131/34454908-ab0659a0-edaf-11e7-9071-b03230e7495c.png)

7.1.0 (though now appears to have half formatting for this file):
![image](https://user-images.githubusercontent.com/225131/34454916-d1cb921c-edaf-11e7-891f-86c8932bc9db.png)

Though this one doesn't have any for the defs:
![image](https://user-images.githubusercontent.com/225131/34454919-da3751fc-edaf-11e7-9af5-df7cf52e9b85.png)

Reinstalling seems to now have inconsistent styling (sorry, not sure what IntelliJ calls this)

**Comment by KronicDeth** [comment]
It may be that the credo annotator is eating up too much memory or CPU.  `mix credo` is expensive in some projects, even when running on a single file, as the annotator is doing, so I added ways to dial it back in 7.0.0.  Try changing the [`credo` configuration](https://github.com/KronicDeth/intellij-elixir#configuration) and see if the code style annotations finish then.

If turning off the `credo` annotator doesn't fix the problem then all I can think is there's an error that's not being reported as an error that you can report, which will be hard to debug.

**Comment by joshuataylor** [comment]
Can confirm it was credo causing issues.
