### ISSUE TITLE
7.2.0 Freezes in intelij IDEA

### ISSUE THREAD

**Issue by sztosz** [KronicDeth/intellij-elixir#970]
It simply freezes when trying to open any menu with Elixir project opened. Happens with all recent versions of IDEA (stable, EAP) and only in Elixir projects (Rust or Java projects work normally) Has something to do with credo I think. Log is rather long so I'm pasting it here: https://pastebin.com/DBWNXMfs

**Comment by joffotron** [comment]
Leaving the credo inspection turned on for me, locks up the whole IDEA whenever I try and do pretty much anything. 

Disabling via Editor > Inspections > Elixir > Credo helps enormously

**Comment by sztosz** [comment]
@joffotron Thanks, turning them off really helps, and allows me to work.

**Comment by KronicDeth** [comment]
Also affected @PhillippOhlandt.

**Comment by KronicDeth** [comment]
I'm going to turn off credo annotator by default in 7.3.0 since it's not obvious why it behaves so poorly.
