### ISSUE TITLE
[idea 2017.3.2, plugin 7.2.0, elixir 1.5.3] Run mix task error on Windows

### ISSUE THREAD

**Issue by zhanghuabin** [KronicDeth/intellij-elixir#971]
Hi,

I created a Mix run conf as below,

![s1](https://user-images.githubusercontent.com/5813426/34469351-e7a37bbe-ef57-11e7-908b-da3e7dc1372e.png)

but got error,

![s2](https://user-images.githubusercontent.com/5813426/34469365-2cd39cfa-ef58-11e7-9c21-d51bc90a4156.png)

then I tried to run the command line in cmd, I got same error,

```batch
E:\dev\lang\erlang\otp\20\bin\erl.exe -pa E:/dev/lang/erlang/elixir/1.5.3/lib/eex/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/elixir/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/ex_unit/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/iex/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/logger/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/mix/ebin -noshell -s elixir start_cli -extra E:\dev\lang\erlang\elixir\1.5.3\bin\mix.bat compile
```

but it will work if I use `mix` instead of `mix.bat` in the command line,

```batch
E:\dev\lang\erlang\otp\20\bin\erl.exe -pa E:/dev/lang/erlang/elixir/1.5.3/lib/eex/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/elixir/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/ex_unit/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/iex/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/logger/ebin -pa E:/dev/lang/erlang/elixir/1.5.3/lib/mix/ebin -noshell -s elixir start_cli -extra E:\dev\lang\erlang\elixir\1.5.3\bin\mix compile
```

I see the method `JpsElixirSdkType.getExecutableFileName()` will handle the file name,  but I have no idea about the solution.

Thanks

**Comment by KronicDeth** [comment]
`mix.bat` would internally invoke `elixir`, which calls `erl.exe`.  Since the plugin calls `erl.exe` directory now, it's probably no long necessary to use `mix.bat`.

**Comment by KronicDeth** [comment]
Reproduced using [Windows 10 Development Environment VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines)

**Comment by zhanghuabin** [comment]
Thanks!
