### ISSUE TITLE
Error with Mix Tasks

### ISSUE THREAD

**Issue by amacgregor** [KronicDeth/intellij-elixir#977]
Error: Mix executable path, elixir executable path, or erl executable path is empty

Current SDK Configuration:
![screen shot 2018-01-05 at 10 03 36 am](https://user-images.githubusercontent.com/212169/34614511-bb4aa9c0-f1ff-11e7-93df-d16bde560710.png)

Configuration:
![screen shot 2018-01-05 at 10 04 46 am](https://user-images.githubusercontent.com/212169/34614564-e598fefc-f1ff-11e7-98c5-f2a4bdcbf20e.png)

Mix and Mix tests fail, however the run inspection credo works.

**Comment by KronicDeth** [comment]
Something is wrong with your Internal Erlang SDK selection: When an Internal Erlang SDK is changed or added to the Elixir SDK, the Erlang SDK code paths should be copied into the Elixir SDK. Your first picture should should show not just the Elixir ebin directories, but also the Erlang ones.

Try removing the Elixir SDK, removing the Erlang SDK and recreating both.  Once you've done that double check that the Elixir SDK is showing the ebin paths for both under Classpath tab.

**Comment by amacgregor** [comment]
Will do and report back

Sent from Astro <https://www.helloastro.com> for iOS


On Jan 5, 2018 at 10:35 AM, Luke Imhoff <notifications@github.com> wrote:


Something is wrong with your Internal Erlang SDK selection: When an
Internal Erlang SDK is changed or added to the Elixir SDK, the Erlang SDK
code paths should be copied into the Elixir SDK. Your first picture should
should show not just the Elixir ebin directories, but also the Erlang ones.

Try removing the Elixir SDK, removing the Erlang SDK and recreating both.
Once you've done that double check that the Elixir SDK is showing the ebin
paths for both under Classpath tab.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KronicDeth/intellij-elixir/issues/977#issuecomment-355583785>,
or mute the thread

**Comment by amacgregor** [comment]
In the end I had to manually add the libraries but that is working correctly now.

**Comment by KronicDeth** [comment]
Well, that's not good if it's not copying the ebin paths from the intellij-erlang's Erlang SDK.  I'll try to reproduce.
