### ISSUE TITLE
Code Style Settings

### ISSUE THREAD

**Issue by KronicDeth** [KronicDeth/intellij-elixir#99]
Use [guide](https://confluence.jetbrains.com/display/IntelliJIDEA/Code+Style+Settings) to add Code Style Settings to configuration #98 and auto-indenting.

**Comment by PhillippOhlandt** [comment]
Any news on this?

**Comment by KronicDeth** [comment]
It's being worked on as the same time as #98.  They are separate steps in the guide, but the formatter is kinda useless with out the configurations because you wouldn't be able to turn settings on and off to test that it's working.

**Comment by KronicDeth** [comment]
CodeStyleSettings were implemented to configure spaces and some alignment/indents as part of #98, so this is also closed by #724
