### ISSUE TITLE
Really slow editing 

### ISSUE THREAD

**Issue by antonmedv** [KronicDeth/intellij-elixir#990]
Hi,

Thanks for awesome plugin! But now editing elixr code really slow, UI frezzes for second. Other plugins: go, php, nodejs, java works normally everythings fly.

**Comment by yordis** [comment]
@antonmedv disable Credo from the project and the IDE in general.

**Comment by KronicDeth** [comment]
@antonmedv are you up-to-date with 7.2.1?  7.2.1 turns the credo annotator off by default.

**Comment by antonmedv** [comment]
Just updated to 7.2.1. Thanks! Credo was the problem.
