### ISSUE TITLE
Configuration to turn off showing alias references

### ISSUE THREAD

**Issue by antonmedv** [KronicDeth/intellij-elixir#991]
Hi,

Is is possible disable alias declarations? And jump to file imidialty?

**Comment by zoltanmaric** [comment]
It could also be just off by default, or just off without a configuration. I don't see it particularly useful to jump to the alias declaration, and other languages don't have it either. E.g. if you go to definition in Java or Scala, there's no option to jump to the `import` statement, which would be the equivalent of an alias in Elixir.
